'use strict';
const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('ltLanguageRuntime',Object.fromEntries(['info','status','connect','run','stop','kernel-file'].map(op=>[op,options=>ipcRenderer.invoke('language-'+op,options)])));
function call(op,...args){const res=ipcRenderer.sendSync('proof-operation',op,args);if(res.error)throw Error(res.error);return res.value;}
function javascript(source,options){return ipcRenderer.invoke('proof-javascript',source,options).then(result=>{if(result?.failed){const error=Error(result.error.message);error.location=result.error.location;error.logs=result.error.logs;throw error;}return result;});}
contextBridge.exposeInMainWorld('ltProof',{info:call('info'),exists:p=>call('exists',p),read:p=>call('read',p),stat:p=>call('stat',p),list:p=>call('list',p),real:p=>call('real',p),mkdir:p=>call('mkdir',p),write:(p,s)=>call('write',p,s),append:(p,s)=>call('append',p,s),calculate:s=>call('calculate',s),javascript:s=>javascript(s),cancelJavascript:()=>ipcRenderer.send('proof-javascript-cancel'),window:(action,args)=>call('window',action,args),onApp:cb=>{ipcRenderer.on('app',(_e,...args)=>cb(null,...args));},notifyInit:()=>ipcRenderer.send('initWindow'),newWindow:()=>ipcRenderer.send('createWindow')});
contextBridge.exposeInMainWorld('ltOpenTargets',{take:()=>call('open-targets-take'),onAvailable:callback=>ipcRenderer.on('revival-open-targets-available',()=>callback())});
contextBridge.exposeInMainWorld('ltDesktop',{open:opts=>call('dialog-open',opts),save:opts=>call('dialog-save',opts),menu:(kind,items)=>call('menu',kind,items),onMenu:cb=>ipcRenderer.on('revival-menu',(_e,id)=>cb(id)),clipboardRead:()=>call('clipboard-read'),clipboardWrite:text=>call('clipboard-write',text)});
contextBridge.exposeInMainWorld('ltProjectFiles',{info:()=>call('project-info'),preview:()=>call('project-preview'),pickParent:()=>call('project-parent'),create:(token,name,options={})=>call('project-create',token,name,options),open:()=>call('project-open'),reopen:path=>call('project-reopen',path),newFile:(name,expectedRoot)=>call('project-file',name,expectedRoot),run:(source,options)=>ipcRenderer.invoke('proof-javascript',source,options)});
contextBridge.exposeInMainWorld('ltSnapshots',{fingerprints:files=>call('fingerprints',files)});
contextBridge.exposeInMainWorld('ltLocalNode',{info:()=>call('node-info'),run:options=>ipcRenderer.invoke('local-node-run',options).then(result=>{if(result?.failed){const error=Error(result.error.message);error.location=result.error.location;error.logs=result.error.logs;throw error;}return result;}),onOutput:callback=>ipcRenderer.on('local-node-output',(_event,message)=>callback(message))});
contextBridge.exposeInMainWorld('ltFileActions',{unlink:path=>call('unlink',path),rename:(from,to)=>call('rename',from,to)});
function previewInvoke(channel,...args){return ipcRenderer.invoke(channel,...args).then(value=>{if(value?.failed){const error=Error(value.error.message);error.location=value.error.location;throw error;}return value;});}
// Return source-linked browser failures as data. contextBridge rejections retain an
// Error's message but lose custom source-location fields across isolated worlds.
contextBridge.exposeInMainWorld('ltBrowserPreview',{start:options=>ipcRenderer.invoke('browser-preview-start',options),updateWatches:(files,requestId)=>ipcRenderer.invoke('browser-preview-watches',files,requestId),evaluate:(source,options)=>ipcRenderer.invoke('browser-preview-evaluate',source,options),status:()=>previewInvoke('browser-preview-status'),stop:()=>previewInvoke('browser-preview-stop'),bounds:value=>ipcRenderer.send('browser-preview-bounds',value),onEvent:callback=>ipcRenderer.on('browser-preview-event',(_event,message)=>callback(message))});
contextBridge.exposeInMainWorld('ltProjectNpm',{start:options=>previewInvoke('project-npm-start',options),status:()=>previewInvoke('project-npm-status'),wait:id=>previewInvoke('project-npm-wait',id),stop:()=>previewInvoke('project-npm-stop'),onEvent:callback=>ipcRenderer.on('project-npm-event',(_event,message)=>callback(message))});

contextBridge.exposeInMainWorld('ltAssistant',{invoke:(op,args)=>ipcRenderer.invoke('assistant-action',op,args),onEvent:cb=>ipcRenderer.on('assistant-event',(_event,message)=>cb(message)),onMenu:cb=>ipcRenderer.on('assistant-menu',(_event,op)=>cb(op)),onEditorRequest:cb=>ipcRenderer.on('assistant-editor-request',(_event,request)=>cb(request)),editorResponse:response=>ipcRenderer.send('assistant-editor-response',response),previewBounds:bounds=>ipcRenderer.send('assistant-preview-bounds',bounds)});
