'use strict';
const fs=require('fs'), path=require('path'), crypto=require('crypto'), vm=require('vm');
const root=path.resolve(__dirname,'../..','.revival'), deploy=path.resolve(__dirname,'..'), user=path.join(root,'proof-user'), docs=path.join(root,'proof-files');
for(const dir of [user,docs]) fs.mkdirSync(dir,{recursive:true});
function seed(from,to){if(fs.existsSync(to))return;const stat=fs.lstatSync(from);if(stat.isSymbolicLink())throw Error('Template links forbidden');if(stat.isDirectory()){fs.mkdirSync(to,{recursive:true});for(const name of fs.readdirSync(from))seed(path.join(from,name),path.join(to,name));}else fs.copyFileSync(from,to);}
seed(path.join(__dirname,'User'),path.join(user,'User'));
const behaviors=path.join(user,'User','user.behaviors');const original=fs.readFileSync(behaviors,'utf8');if(original.includes('[:app :lt.objs.plugins/load-js "user_compiled.js"]'))fs.writeFileSync(behaviors,original.replace('[:app :lt.objs.plugins/load-js "user_compiled.js"]',';; Legacy sample plugin omitted from bounded revival.'));
if(!fs.existsSync(path.join(docs,'calculation.js')))fs.writeFileSync(path.join(docs,'calculation.js'),'(12 + 30)');
function inside(p,r){const rel=path.relative(r,p);return rel===''||(!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel));}
function checked(input,write=false){if(typeof input!=='string'||input.length>1024||input.includes('\0'))throw Error('Invalid path');const p=path.resolve(input);const allowed=write?[user,docs]:[deploy,user,docs];if(!allowed.some(r=>inside(p,r)))throw Error('Path outside proof roots: '+p);let cur=p;while(!fs.existsSync(cur)){const next=path.dirname(cur);if(next===cur)throw Error('Invalid ancestor');cur=next;}if(!allowed.some(r=>inside(fs.realpathSync(cur),fs.realpathSync(r))))throw Error('Resolved path outside proof roots');let walk=cur;while(walk!==path.dirname(walk)){if(fs.existsSync(walk)&&fs.lstatSync(walk).isSymbolicLink())throw Error('Links forbidden');walk=path.dirname(walk);}return p;}
function calculate(source){if(typeof source!=='string'||source.length>256||!/^\s*[0-9()+\-*/%.\s]+\s*$/.test(source)||!/[0-9]/.test(source))throw Error('Only numeric arithmetic is allowed');if(/\/\/|\/\*|\*\*/.test(source))throw Error('Comments/exponentiation forbidden');const hash=crypto.createHash('sha256').update(source,'utf8').digest('hex');const result=vm.runInNewContext('"use strict";('+source+')',Object.create(null),{timeout:50,contextCodeGeneration:{strings:false,wasm:false}});if(typeof result!=='number'||!Number.isFinite(result))throw Error('Expected finite number');return {source,sha256:hash,result};}
function operation(op,args){if(!Array.isArray(args)||args.length>8)throw Error('Invalid arguments');switch(op){case 'info':return {core:__dirname,deploy,user,docs,platform:process.platform,versions:{electron:process.versions.electron},windowId:1};case 'exists':try{return fs.existsSync(checked(args[0]));}catch(e){return false;}case 'read':{const p=checked(args[0]);if(fs.statSync(p).size>8*1024*1024)throw Error('Read too large');return fs.readFileSync(p,'utf8');}case 'stat':{const s=fs.statSync(checked(args[0]));return {directory:s.isDirectory(),file:s.isFile(),mode:s.mode,mtime:s.mtime.toISOString(),size:s.size};}case 'list':return fs.readdirSync(checked(args[0]));case 'real':return fs.realpathSync(checked(args[0]));case 'mkdir':return fs.mkdirSync(checked(args[0],true),{recursive:true});case 'write':case 'append':{const p=checked(args[0],true);if(typeof args[1]!=='string'||Buffer.byteLength(args[1])>65536)throw Error('Write exceeds bound');return op==='write'?fs.writeFileSync(p,args[1],'utf8'):fs.appendFileSync(p,args[1],'utf8');}case 'calculate':return calculate(args[0]);default:throw Error('Unsupported proof operation '+op);}}
module.exports={operation,calculate,checked,root,deploy,user,docs};