'use strict';
(()=>{
const b=window.ltProof, info=b.info;
window.ltDirname=info.core;
window.ltProcess={platform:info.platform,env:{LT_USER_DIR:info.user,USERPROFILE:info.user,LT_DEV_CLI:'true'},versions:info.versions,argv:[],execPath:'',cwd:()=>info.docs,nextTick:cb=>setTimeout(cb,0),on:()=>{}};
const unavailable=()=>{throw Error('Capability unavailable in bounded revival proof');};
const fs={existsSync:b.exists,readFileSync:b.read,readFile:(p,cb)=>{try{cb(b.read(p));}catch(e){console.error(e);}},writeFileSync:b.write,appendFileSync:b.append,mkdirSync:b.mkdir,readdirSync:b.list,realpathSync:b.real,statSync:p=>{const s=b.stat(p);return {...s,mtime:new Date(s.mtime),isDirectory:()=>s.directory,isFile:()=>s.file};},watchFile:()=>{},unwatchFile:()=>{},createWriteStream:p=>({write:s=>b.append(p,String(s)),end:()=>{}})};
function norm(p){let v=String(p).replace(/\\/g,'/');const prefix=/^[A-Za-z]:/.test(v)?v.slice(0,2):'';v=v.slice(prefix.length);const parts=[];for(const seg of v.split('/')){if(!seg||seg==='.')continue;if(seg==='..')parts.pop();else parts.push(seg);}return (prefix+(v.startsWith('/')?'/':'')+parts.join('/')).replace(/\//g,'\\');}
const fpath={sep:'\\',join:(...s)=>norm(s.join('/')),resolve:(...s)=>{let base=info.docs;for(const part of s){base=/^[A-Za-z]:/.test(part)?part:base+'/'+part;}return norm(base);},dirname:p=>norm(p).replace(/\\[^\\]*$/,''),basename:(p,ext)=>{let v=norm(p).split('\\').pop();return ext&&v.endsWith(ext)?v.slice(0,-ext.length):v;},extname:p=>{const v=norm(p).split('\\').pop();return v.includes('.')?v.slice(v.lastIndexOf('.')):'';},relative:(a,p)=>{const aa=norm(a).split('\\'),bb=norm(p).split('\\');while(aa.length&&bb.length&&aa[0].toLowerCase()===bb[0].toLowerCase()){aa.shift();bb.shift();}return [...aa.map(()=>'..'),...bb].join('\\');}};
class MenuItem{constructor(opts){Object.assign(this,opts);}}
class Menu{constructor(){this.items=[];}append(i){this.items.push(i);}popup(){console.info('Native popup menu unavailable in proof');}static setApplicationMenu(menu){window.ltProofMenu=menu;}}
const win={id:1,getSize:()=>b.window('size'),getPosition:()=>b.window('position'),isFullScreen:()=>b.window('fullscreen'),focus:()=>b.window('focus'),minimize:()=>b.window('minimize'),maximize:()=>b.window('maximize'),setSize:()=>{},setPosition:()=>{},setFullScreen:unavailable,close:unavailable,destroy:unavailable};
const remoteFacade={getCurrentWindow:()=>win,app:{getAppPath:()=>info.core},getGlobal:name=>name==='browserOpenFiles'?[]:{},process:{argv:['proof','core']},Menu,MenuItem,dialog:{showOpenDialog:()=>[fpath.join(info.docs,'calculation.js')],showSaveDialog:()=>fpath.join(info.docs,'calculation.js')}};
let zoom=1;const electron={remote:remoteFacade,webFrame:{getZoomFactor:()=>zoom,setZoomFactor:v=>{zoom=v;document.body.style.zoom=String(v);}},ipcRenderer:{on:(channel,cb)=>{if(channel==='app')b.onApp(cb);},send:(channel)=>{if(channel==='initWindow')b.notifyInit();else console.info('IPC feature unavailable',channel);}},shell:{openExternal:unavailable,openItem:unavailable,showItemInFolder:unavailable},clipboard:{writeText:unavailable,readText:()=>''}};
const emitter={on:()=>emitter,send:()=>{},kill:()=>{},stdout:{on:()=>{}},stderr:{on:()=>{}}};
const cp={fork:()=>{console.info('Background worker disabled in bounded proof');return emitter;},spawn:unavailable,exec:(cmd,cb)=>{if(cmd==='wmic logicaldisk get name')cb(null,'Name\r\nE:\r\n','');else unavailable();}};
const shell={mkdir:(flag,p)=>b.mkdir(p||flag),cp:unavailable,rm:unavailable,exec:unavailable,test:(flag,p)=>flag==='-d'?fs.statSync(p).isDirectory():b.exists(p),which:()=>null};
window.ltRequire=name=>{const leaf=String(name).replace(/\\/g,'/').split('/node_modules/').pop();switch(leaf){case 'electron':return electron;case 'fs':return fs;case 'path':return fpath;case 'os':return {EOL:'\r\n',homedir:()=>info.user};case 'util':return {inspect:v=>{try{return JSON.stringify(v);}catch{return String(v);}}};case 'child_process':return cp;case 'net':return {createServer:unavailable,connect:unavailable};case 'shelljs':return shell;case 'request':return Object.assign(unavailable,{get:unavailable,defaults:()=>unavailable});case 'tar':case 'zlib':return {};case 'socket.io':return {listen:unavailable};default:throw Error('Module not allowed: '+name);}};
})();