'use strict';
(()=>{
const token=__PROOF_TOKEN__,send=self.postMessage.bind(self),stringify=JSON.stringify,evaluate=(0,eval);
const nativeSetTimeout=self.setTimeout.bind(self),nativeClearTimeout=self.clearTimeout.bind(self),resolve=Promise.resolve.bind(Promise),then=Function.call.bind(Promise.prototype.then);
const NativeBlob=Blob,createURL=URL.createObjectURL.bind(URL),revokeURL=URL.revokeObjectURL.bind(URL);
const encoder=new TextEncoder();
const keys=Object.keys,finite=Number.isFinite,timers=Object.create(null),join=Function.call.bind(Array.prototype.join),encode=encoder.encode.bind(encoder);let finished=false,totalTimers=0,liveTimers=0;
const logs=[];let logBytes=0;
const watchValues=Object.create(null);let watchIds,watchBytes=0,watchFailure;
function watch(id,value){try{if(!watchIds?.has(id))throw Error('Unknown expression watch');let result;try{result=typeof value==='undefined'?'undefined':typeof value==='function'?'[Function]':typeof value==='bigint'?String(value)+'n':typeof value==='symbol'?String(value):typeof value==='number'&&!finite(value)?String(value):stringify(value);}catch(_){result='[Value cannot be serialized]';}if(typeof result!=='string')result=String(value);const size=encode(result).byteLength,next=watchBytes+size-(watchValues[id]?encode(watchValues[id]).byteLength:0);if(size>1024||next>16384)throw Error('Watch values exceed 1 KiB each / 16 KiB total');watchBytes=next;watchValues[id]=result;return value;}catch(error){watchFailure=watchFailure||error;throw error;}}
function log(level,args){if(logs.length>=32)throw Error('Console exceeds 32 messages');const parts=[];for(let i=0;i<args.length;i++){const value=args[i];parts[i]=typeof value==='string'?value:typeof value==='undefined'?'undefined':stringify(value);}const line=level+': '+join(parts,' ');logBytes+=encode(line).byteLength;if(logBytes>4096)throw Error('Console exceeds 4 KiB');logs[logs.length]=line;}
function finish(error,value){if(finished)return;finished=true;error=error||watchFailure;const handles=keys(timers);for(let i=0;i<handles.length;i++)nativeClearTimeout(Number(handles[i]));try{if(error){send({token,error:String(error.message||error).slice(0,1024),stack:typeof error.stack==='string'?error.stack.slice(0,4096):''});return;}const output=typeof value==='undefined'?'undefined':typeof value==='function'?'[Function]':stringify(value);if(typeof output!=='string'||output.length>16384)throw Error('Output exceeds 16 KiB or cannot be serialized');const watches=[];for(const id of keys(watchValues))watches[watches.length]={id,result:watchValues[id]};send({token,output,logs,watches});}catch(e){send({token,error:String(e.message||e).slice(0,1024)});}}
function boundedTimeout(callback,delay=0,...args){if(finished)throw Error('Context already completed');if(typeof callback!=='function')throw Error('Timer callback must be a function');if(typeof delay!=='number'||!finite(delay)||delay<0||delay>500)throw Error('Timer delay must be between 0 and 500 ms');if(liveTimers>=32||++totalTimers>128)throw Error('Timer budget exceeded');let handle=nativeSetTimeout(()=>{delete timers[handle];liveTimers--;if(finished)return;try{then(resolve(callback(...args)),()=>{},error=>finish(error));}catch(error){finish(error);}},delay);timers[handle]=true;liveTimers++;return handle;}
function clearBoundedTimeout(handle){if(timers[handle]){delete timers[handle];liveTimers--;nativeClearTimeout(handle);}}
function lock(name,value){for(let target=self;target;target=Object.getPrototypeOf(target)){if(target===self||Object.prototype.hasOwnProperty.call(target,name))try{Object.defineProperty(target,name,{value,writable:false,configurable:false});}catch(_){}}}
for(const name of ['fetch','XMLHttpRequest','WebSocket','importScripts','Worker','SharedWorker','setInterval','indexedDB','caches','navigator'])lock(name,undefined);
lock('setTimeout',boundedTimeout);lock('clearTimeout',clearBoundedTimeout);
lock('console',Object.freeze({log:(...args)=>log('log',args),info:(...args)=>log('info',args),warn:(...args)=>log('warn',args),error:(...args)=>log('error',args),debug:(...args)=>log('debug',args)}));
self.addEventListener('unhandledrejection',e=>{e.preventDefault();finish(e.reason||Error('Unhandled rejection'));});
self.onmessage=async e=>{if(e.data?.warmup===token&&e.data.code===undefined){send({token,ready:true});return;}self.onmessage=null;let url;try{if(e.data.watch){watchIds=new Set(e.data.watch.ids);lock(e.data.watch.key,watch);}let result;if(e.data.module){url=createURL(new NativeBlob([e.data.code],{type:'text/javascript'}));const namespace=await import(url);result=e.data.resultExport==='namespace'?namespace:namespace.default;}else result=evaluate(e.data.code);finish(null,await result);}catch(error){finish(error);}finally{if(url)revokeURL(url);}};
})();
