'use strict';
process.env.LT_REVIVAL_TEST='1';process.env.LT_REVIVAL_AUTO_LIVE='0';
const {app,Menu}=require('electron'),fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{spawn}=require('child_process');
const core=path.resolve(__dirname,'../../deploy/core'),policy=require(core+'/proof-policy.cjs'),projects=require(core+'/revival-projects.cjs');
const {captureNativePage}=require('./native-page-capture.cjs'),base=path.join(policy.root,'assistant-fixtures'),root=path.join(base,crypto.randomUUID()),file=path.join(root,'program.js'),html=path.join(root,'index.html');
fs.mkdirSync(root,{recursive:true});fs.writeFileSync(file,'const first = 1;\nconst watched = 2;\nconst last = 3;\n');fs.writeFileSync(html,'<h1>Before assistant</h1><script>console.log("preview ready")</script>');
const before=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null;
// Exercise the actual renderer/preload/controller path without borrowing a user's model.
const uiRequests=[];let modelAbort,modelMode='stream';
require(core+'/revival-assistant-ollama.cjs').create=()=>({models:async()=>[{name:'ui-fixture'},{name:'decision-fixture',digest:'fixture',size:1}],show:async name=>({capabilities:name==='decision-fixture'?['decision']:['tools']}),chat:async(body,{signal,onChunk=()=>{}})=>{
 uiRequests.push(body);
 if(modelMode==='command'){modelMode='stream';return {message:{role:'assistant',content:'Starting a foreground command',tool_calls:[{function:{name:'run_command',arguments:{command:'node -e "console.log(\'UI WAITING\');setInterval(()=>{},1000)"'}}}]}};}
 modelAbort=signal;onChunk({content:'Streaming from the native UI fixture…'});return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));
}});
function tree(directory){const files=new Map();function visit(dir){if(!fs.existsSync(dir))return;assert(fs.lstatSync(dir).isDirectory()&&!fs.lstatSync(dir).isSymbolicLink());for(const name of fs.readdirSync(dir)){const full=path.join(dir,name),stat=fs.lstatSync(full);assert(!stat.isSymbolicLink());if(stat.isDirectory())visit(full);else files.set(full,fs.readFileSync(full));}}visit(directory);return files;}
const cacheRoot=path.join(policy.user,'ltcache'),assistantRoot=path.join(policy.user,'assistant'),savedCaches=[cacheRoot,assistantRoot].map(dir=>({dir,files:tree(dir)}));
projects.activate(root);const result={passed:false,checks:[]};let seen=false,manual,window,backend,ending=false;
const deadline=setTimeout(()=>finish(Error('Assistant native proof timed out')),200000);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function finish(error){if(ending)return;ending=true;clearTimeout(deadline);if(error){result.error=error.stack;console.error(error);result.previewDiagnostics=require(core+'/revival-preview.cjs').diagnostics();result.commandDiagnostics=backend.assistant.commands.diagnostics();try{result.uiDiagnostics=await window.webContents.executeJavaScript('({header:document.querySelector("#assistant-preview-pane header")?.textContent,chat:document.getElementById("assistant-history")?.innerText})');}catch(_){}}try{
 await backend.assistant.shutdown();for(const name of ['revival-languages.cjs','revival-preview.cjs','revival-npm.cjs','revival-node.cjs','proof-js.cjs'])await require(core+'/'+name).shutdown();await require(core+'/proof-memory.cjs').stop();if(manual&&manual.exitCode===null)manual.kill();
 if(before)fs.writeFileSync(projects.statePath,before);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);
 for(const {dir,files}of savedCaches){for(const name of tree(dir).keys())if(!files.has(name))fs.unlinkSync(name);for(const [name,data]of files){fs.mkdirSync(path.dirname(name),{recursive:true});fs.writeFileSync(name,data);}}
 assert(path.relative(base,root)&&!path.relative(base,root).startsWith('..')&&fs.realpathSync(root)===root);fs.rmSync(root,{recursive:true});
 result.cleanup={...backend.assistant.diagnostics(),...require(core+'/proof-memory.cjs').status(),projectRestored:before?fs.readFileSync(projects.statePath).equals(before):!fs.existsSync(projects.statePath),fixtureRemoved:!fs.existsSync(root)};
 assert.equal(result.cleanup.commands,0);assert.equal(result.cleanup.active,0);assert.equal(result.cleanup.views,0);assert.equal(result.cleanup.jobs,0);assert(!result.cleanup.helperPid);result.passed=!error;
 }catch(e){result.cleanupError=e.stack;result.passed=false;}fs.writeFileSync(path.join(policy.root,'assistant-native-result.json'),JSON.stringify(result,null,2));app.exit(result.passed?0:1);}
app.on('browser-window-created',(_event,host)=>{if(seen)return;seen=true;window=host;host.setOpacity(0.01);host.setSkipTaskbar(true);host.showInactive();host.setSize(1440,900);host.webContents.once('did-finish-load',()=>setTimeout(async()=>{const ui=code=>host.webContents.executeJavaScript(code),check=async(name,fn)=>{await fn();result.checks.push(name);console.error(name);},until=async(predicate,timeout=7000)=>{const end=Date.now()+timeout;while(!await predicate()){if(Date.now()>end)throw Error('Native editor condition timed out');await sleep(25);}};try{
 host.unmaximize();host.setBounds({x:40,y:40,width:1440,height:900});host.setOpacity(1);host.show();host.moveTop();host.focus();result.hostBounds=host.getBounds();
 await until(()=>ui('!!window.ltAssistantUI&&!!document.getElementById("assistant-dock")'));
 await check('Chat and Activity share a resizable dock and all panel actions live in the menu',async()=>{assert(await ui('document.querySelector("#assistant-activity #proof-calculation")!==null&&document.querySelectorAll("#proof-calculation button,#proof-calculation select").length===0'));host.emit('focus');const menu=Menu.getApplicationMenu().items.find(m=>m.label.replace(/&/g,'')==='Assistant');assert(menu.submenu.items.some(m=>m.label==='Stop'));await ui('ltAssistantUI.width(420);ltAssistantUI.show("chat",false);void 0;');assert.equal(await ui('document.getElementById("assistant-dock").offsetWidth'),420);assert(await ui('!document.getElementById("assistant-chat").hidden'));});
 await ui('ltProjects.openedFolder('+JSON.stringify(projects.info().current)+');lt.objs.command.exec_BANG_(cljs.core.keyword("open-path"),'+JSON.stringify(file)+');void 0;');await until(()=>ui('ltAssistantEditor.snapshot('+JSON.stringify(file)+')!==null'));const files=backend.assistant.runtime.files(host.webContents.id),session=backend.assistant.store.conversation(root);
 const source=await files.read(file);assert.equal(source.source,fs.readFileSync(file,'utf8'));
 await check('The chat displays 64K context and its visible Stop button aborts generation while preserving the draft',async()=>{
  await ui('ltAssistantUI.action("models");');await ui('ltAssistantUI.action("new");');await ui('document.getElementById("assistant-model").value="ui-fixture";document.getElementById("assistant-input").value="Build the fixture";ltAssistantUI.send();');
  await until(()=>ui('!document.getElementById("assistant-stop").hidden&&document.getElementById("assistant-history").textContent.includes("Streaming from")'));
  assert.equal(uiRequests.at(-1).options.num_ctx,65536);assert(await ui('document.getElementById("assistant-context-label").textContent.includes("65,536")'));
  result.stopScreenshot=path.join(policy.root,'assistant-controls-native.png');fs.writeFileSync(result.stopScreenshot,(await captureNativePage(host.webContents)).toPNG());
  const immediate=await ui('(()=>{document.getElementById("assistant-input").value="Keep my next draft";document.getElementById("assistant-stop").click();return {disabled:document.getElementById("assistant-stop").disabled,label:document.getElementById("assistant-stop").textContent,sendDisabled:document.getElementById("assistant-send").disabled};})()');
  assert.deepEqual(immediate,{disabled:true,label:'Stopping…',sendDisabled:true});await until(()=>backend.assistant.runtime.activeCount()===0);await until(()=>ui('ltAssistantUI.state().state.status==="stopped"&&document.getElementById("assistant-stop").hidden'));
  assert(modelAbort.aborted);assert.equal(await ui('document.getElementById("assistant-input").value'),'Keep my next draft');
 });
 await check('Context settings offer presets and custom tokens, validate the range, persist and support Cancel',async()=>{
  await ui('document.getElementById("assistant-context-label").click();void 0;');
  assert(await ui('document.getElementById("assistant-settings").open'));assert.equal(await ui('document.getElementById("assistant-context-preset").value'),'65536');
  result.contextSettingsScreenshot=path.join(policy.root,'assistant-context-settings.png');fs.writeFileSync(result.contextSettingsScreenshot,(await captureNativePage(host.webContents)).toPNG());
  await ui('document.getElementById("assistant-context-preset").value="32768";document.getElementById("assistant-context-preset").dispatchEvent(new Event("change"));void 0;');assert.equal(await ui('document.getElementById("assistant-context").value'),'32768');
  assert(await ui('(()=>{const input=document.getElementById("assistant-context");input.value="2047";return !input.checkValidity();})()'));assert.equal(backend.assistant.store.settings().contextTokens,65536);
  await ui('document.getElementById("assistant-context").value="24576";document.getElementById("assistant-context").dispatchEvent(new Event("input"));void 0;');assert.equal(await ui('document.getElementById("assistant-context-preset").value'),'custom');
  await ui('document.querySelector("#assistant-settings form").requestSubmit();void 0;');await until(()=>ui('!document.getElementById("assistant-settings")'));
  assert.equal(require(core+'/revival-assistant-store.cjs').create(assistantRoot).settings().contextTokens,24576);assert(await ui('document.getElementById("assistant-context-label").textContent.includes("24,576")'));
  await ui('ltAssistantUI.action("settings");void 0;');assert.equal(await ui('document.getElementById("assistant-context").value'),'24576');await ui('document.getElementById("assistant-context-preset").value="32768";document.getElementById("assistant-context-preset").dispatchEvent(new Event("change"));document.querySelector("#assistant-settings button[type=button]").click();void 0;');assert.equal(backend.assistant.store.settings().contextTokens,24576);
 });
 await check('A context value saved through Chat reaches the next model request',async()=>{
  const previous=uiRequests.length;await ui('document.getElementById("assistant-input").value="Use my custom context";ltAssistantUI.send();');await until(()=>uiRequests.length>previous);assert.equal(uiRequests.at(-1).options.num_ctx,24576);
  await ui('document.getElementById("assistant-stop").click();void 0;');await until(()=>ui('ltAssistantUI.state().state.status==="stopped"&&document.getElementById("assistant-stop").hidden'));
  await ui('document.getElementById("assistant-context-label").click();document.getElementById("assistant-context-preset").value="65536";document.getElementById("assistant-context-preset").dispatchEvent(new Event("change"));document.querySelector("#assistant-settings form").requestSubmit();void 0;');await until(()=>ui('!document.getElementById("assistant-settings")'));assert.equal(backend.assistant.store.settings().contextTokens,65536);
 });
 await check('The visible chat Stop button terminates an actual foreground process family',async()=>{
  modelMode='command';await ui('document.getElementById("assistant-input").value="Start command";ltAssistantUI.send();');await until(()=>backend.assistant.commands.diagnostics().active.some(c=>c.stdout.includes('UI WAITING')),30000);assert(await ui('document.getElementById("assistant-history").textContent.includes("Streaming from the native UI fixture")'));
  await ui('document.getElementById("assistant-stop").click();void 0;');await until(()=>backend.assistant.runtime.activeCount()===0&&backend.assistant.commands.activeCount()===0);
  const receipt=backend.assistant.commands.diagnostics().recent.find(c=>c.stdout.includes('UI WAITING'));assert.equal(receipt.status,'stopped');assert(receipt.memory.processExited);result.uiStopCommandReceipt=receipt;
 });
 await check('File tools read actual dirty original CodeMirror buffers',async()=>{await ui('ltProofUI.connect().replaceRange("// user edit\\n",{line:0,ch:0});void 0;');const value=await files.read(file);assert(value.source.startsWith('// user edit'));assert(!fs.readFileSync(file,'utf8').startsWith('// user edit'));});
 await check('A concurrent user edit rejects a stale replacement',async()=>{await ui('ltProofUI.connect().replaceRange("// concurrent\\n",{line:0,ch:0});void 0;');await assert.rejects(files.change(session,file,'discard user source',{runId:'stale'}),/File changed/);assert((await files.read(file)).source.includes('// concurrent'));});
 await ui('window.assistantRootEditor=lt.objs.editor.pool.last_active();window.assistantOldLinked=cljs.core.get(cljs.core.deref(lt.objs.opener.opener),cljs.core.keyword("open-linked-doc"));lt.object.merge_BANG_(lt.objs.opener.opener,cljs.core.hash_map(cljs.core.keyword("open-linked-doc"),true));lt.objs.command.exec_BANG_(cljs.core.keyword("open-path"),'+JSON.stringify(file)+');void 0;');await until(()=>ui('cljs.core.count(lt.objs.editor.pool.by_path('+JSON.stringify(file)+'))===2'));
 await ui('window.assistantMark=ltProofUI.connect().markText({line:3,ch:6},{line:3,ch:13},{className:"assistant-retained-watch"});ltProofUI.connect().setSelections([{anchor:{line:2,ch:6},head:{line:2,ch:11}},{anchor:{line:3,ch:6},head:{line:3,ch:13}}]);void 0;');const dirty=await files.read(file),selection=await ui('ltProofUI.connect().listSelections()');
 await check('Canonical assistant edits update linked views, retain marks and selections, and save the entire document',async()=>{const next=dirty.source.replace('last = 3','last = 9');await files.change(session,file,next,{runId:'linked'});assert.equal(fs.readFileSync(file,'utf8'),next);assert(await ui('(()=>{const views=cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(file)+'));return views.every(v=>lt.objs.editor.__GT_cm_ed(v).getValue()==='+JSON.stringify(next)+'&&!cljs.core.get(cljs.core.deref(v),cljs.core.keyword("dirty"))&&!lt.objs.editor.__GT_cm_ed(v).getOption("readOnly"));})()'));assert(await ui('!!window.assistantMark.find()'));assert.deepEqual(await ui('ltProofUI.connect().listSelections()'),selection);});
 await check('Undo assistant edits restores unsaved linked content and the prior disk independently',async()=>{const value=await files.undo(session);assert.equal(value.conflicts.length,0);assert.equal((await files.read(file)).source,dirty.source);assert.equal(fs.readFileSync(file,'utf8'),source.source);assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(file)+')).every(v=>!!cljs.core.get(cljs.core.deref(v),cljs.core.keyword("dirty")))'));});
 await check('Undo cannot overwrite later user input in a linked editor',async()=>{await files.read(file);await files.change(session,file,dirty.source.replace('last = 3','last = 8'),{runId:'conflict'});await ui('ltProofUI.connect().replaceRange("// later user\\n",{line:0,ch:0});void 0;');const value=await files.undo(session);assert.equal(value.restored.length,0);assert.equal(value.conflicts.length,1);});
 await check('Partial linked views still expose and save the entire canonical document',async()=>{await ui('window.assistantOldOptions=lt.objs.document.default_linked_doc_options;lt.objs.document.default_linked_doc_options=cljs.core.hash_map(cljs.core.keyword("from"),1,cljs.core.keyword("to"),3);lt.objs.command.exec_BANG_(cljs.core.keyword("open-path"),'+JSON.stringify(file)+');void 0;');await until(()=>ui('cljs.core.count(lt.objs.editor.pool.by_path('+JSON.stringify(file)+'))===3'));const before=await files.read(file);assert.equal(await ui('ltProofUI.connect().getDoc().firstLine()'),1);assert.equal(await ui('ltProofUI.connect().getDoc().lastLine()'),2);await files.change(session,file,before.source.replace('last = 8','last = 11'),{runId:'partial'});assert.equal(fs.readFileSync(file,'utf8'),before.source.replace('last = 8','last = 11'));assert.equal((await files.undo(session)).conflicts.length,0);await ui('lt.objs.document.default_linked_doc_options=window.assistantOldOptions;void 0;');});
 await check('Rename and delete preserve canonical identities and have conflict-safe undo',async()=>{await files.read(file);const renamed=path.join(root,'renamed.ts');await files.rename(session,file,renamed,'rename');assert.equal(await ui('cljs.core.count(lt.objs.editor.pool.by_path('+JSON.stringify(renamed)+'))'),3);assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(renamed)+')).every(v=>ltProofUI.sourceLoader(v)==="ts")'));assert.equal((await files.undo(session)).conflicts.length,0);assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(file)+')).every(v=>ltProofUI.sourceLoader(v)==="js")'));await files.read(file);await files.remove(session,file,'delete');assert(!fs.existsSync(file));assert.equal((await files.undo(session)).conflicts.length,0);assert(fs.existsSync(file));});
 await check('A real save failure preserves dirty source, selections and released linked views',async()=>{const before=await files.read(file),rename=fs.renameSync;fs.renameSync=(from,to)=>{if(to===file){const error=Error('Fixture save access denied');error.code='EACCES';throw error;}return rename(from,to);};try{await assert.rejects(files.change(session,file,before.source+'// retained after save failure\n',{runId:'save-failure'}),/access denied/);}finally{fs.renameSync=rename;}assert((await files.read(file)).source.includes('retained after save failure'));assert.equal(fs.readFileSync(file,'utf8'),before.disk.source);assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(file)+')).every(e=>!lt.objs.editor.__GT_cm_ed(e).getOption("readOnly")&&!!cljs.core.get(cljs.core.deref(e),cljs.core.keyword("dirty")))'));assert.equal((await files.undo(session)).conflicts.length,0);});
 await check('Actual foreground commands report Unicode output and native exit codes',async()=>{const value=await backend.assistant.commands.start(host.webContents.id,{cwd:root,command:'node -e "console.log(\'🌱 receipt\');console.error(\'test failed\');process.exit(7)"',purpose:'test'});assert.equal(value.exitCode,7);assert(value.stdout.includes('🌱 receipt'));assert(value.stderr.includes('test failed'));assert(value.memory.hardPrivateCommit&&value.memory.limitBytes===1024*1024*1024);result.commandReceipt=value;});
 const node=require(core+'/revival-node.cjs').discover().executable;manual=spawn(node,['-e','setInterval(()=>{},1000)'],{windowsHide:true,stdio:'ignore'});
 fs.writeFileSync(path.join(root,'server.cjs'),'const http=require("http"),fs=require("fs");http.createServer((req,res)=>{res.setHeader("content-type","text/html");res.end(fs.readFileSync("index.html"))}).listen(0,"127.0.0.1",function(){console.log("READY http://127.0.0.1:"+this.address().port)});');
 const background=await backend.assistant.commands.start(host.webContents.id,{cwd:root,command:'node server.cjs',background:true,purpose:'server'});await until(()=>/READY http:\/\//.test(backend.assistant.commands.status(background.id)?.stdout));const url=backend.assistant.commands.status(background.id).stdout.match(/http:\/\/127\.0\.0\.1:\d+/)[0],run={owner:host.webContents.id,session};result.initialBounds=await ui('({bounds:ltAssistantUI.previewSlot(),popups:Array.from(document.querySelectorAll(".popup,dialog[open]")).map(n=>n.textContent),pane:document.getElementById("assistant-preview-pane").outerHTML})');console.error('Assistant view geometry '+JSON.stringify(result.initialBounds));
 await check('Preview startup failures display their error instead of leaving Preparing program',async()=>{const broken=path.join(root,'broken.html');fs.writeFileSync(broken,'<script>const = ;</script>');await assert.rejects(backend.assistant.preview.start(run,{path:broken}));await until(()=>ui('document.querySelector("#assistant-preview-pane header").textContent.includes("failed")'));assert(await ui('document.querySelector("#assistant-preview-pane header").textContent.length>40'));await backend.assistant.preview.stop(run);});
 await check('The assistant preview Run button survives failures and retries the same preview after a fix',async()=>{const broken=path.join(root,'broken.html');await assert.rejects(backend.assistant.preview.start(run,{path:broken}));await ui('document.getElementById("assistant-preview-run").click();void 0;');await until(()=>ui('!document.getElementById("assistant-preview-run").disabled'));assert(await ui('document.getElementById("assistant-preview-status").textContent.includes("failed")'));fs.writeFileSync(broken,'<h1>Fixed with quick Run</h1>');await ui('document.getElementById("assistant-preview-run").click();void 0;');await until(async()=>!await ui('document.getElementById("assistant-preview-run").disabled')&&require(core+'/revival-preview.cjs').status('assistant:'+host.webContents.id)?.status==='running',12000);await require(core+'/revival-preview.cjs').view('assistant:'+host.webContents.id).webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>resolve(document.body.innerText)))');assert((await backend.assistant.preview.inspect(run)).dom.text.includes('Fixed with quick Run'));await backend.assistant.preview.stop(run);});
 await check('An actual assistant-owned server is shown beside code with DOM, console and real screenshots',async()=>{const value=await backend.assistant.preview.start(run,{job_id:background.id,url});assert.equal(value.status,'running');const inspect=await backend.assistant.preview.inspect(run);assert(inspect.dom?.text?.includes('Before assistant')||String(inspect.dom).includes('Before assistant'));const image=await backend.assistant.preview.capture(run);assert(image.width>50&&image.height>50);assert(Buffer.from(image.images[0],'base64').subarray(1,4).toString()==='PNG');assert.equal(await require(core+'/revival-preview.cjs').view('assistant:'+host.webContents.id).webContents.executeJavaScript('typeof window.ltAssistant'),'undefined');});
 await check('Quick Run reloads an assistant server preview without starting another server or model request',async()=>{const preview=require(core+'/revival-preview.cjs'),previous=preview.status('assistant:'+host.webContents.id).id,requests=uiRequests.length,pid=backend.assistant.commands.status(background.id).pid;await ui('document.getElementById("assistant-preview-run").click();void 0;');assert(await ui('document.getElementById("assistant-preview-run").disabled'));await until(()=>ui('!document.getElementById("assistant-preview-run").disabled'),12000);assert.notEqual(preview.status('assistant:'+host.webContents.id).id,previous);assert((await backend.assistant.preview.inspect(run)).dom.text.includes('Before assistant'));assert.equal(backend.assistant.commands.status(background.id).pid,pid);assert.equal(backend.assistant.commands.activeCount(),1);assert.equal(uiRequests.length,requests);assert.equal(manual.exitCode,null);});
 await backend.assistant.preview.stop(run);await backend.assistant.commands.stop(host.webContents.id,background.id);
 await check('Captured preview automatically reflects unsaved editor changes without Run or Preview',async()=>{await ui('lt.objs.command.exec_BANG_(cljs.core.keyword("open-path"),'+JSON.stringify(html)+');void 0;');await until(()=>ui('!!ltAssistantEditor.snapshot('+JSON.stringify(html)+')'));await backend.assistant.preview.start(run,{path:html});await ui('ltProofUI.connect().replaceRange("Live from unsaved code",{line:0,ch:4},{line:0,ch:20});void 0;');await until(async()=>String((await backend.assistant.preview.inspect(run)).dom?.text||'').includes('Live from unsaved code'));assert(fs.readFileSync(html,'utf8').includes('Before assistant'));const pixels=await backend.assistant.preview.capture(run);result.previewScreenshot=path.join(policy.root,'assistant-native-preview.png');fs.writeFileSync(result.previewScreenshot,Buffer.from(pixels.images[0],'base64'));result.screenshot=path.join(policy.root,'assistant-native.png');fs.writeFileSync(result.screenshot,(await captureNativePage(host.webContents)).toPNG());});
 await check('Quick Run restarts captured program state with dirty canonical source and retains automatic updates',async()=>{const preview=require(core+'/revival-preview.cjs'),owner='assistant:'+host.webContents.id,previous=preview.status(owner).id,before=await files.read(html),disk=fs.readFileSync(html),requests=uiRequests.length;await preview.view(owner).webContents.executeJavaScript('window.quickRunMarker=42');await ui('document.getElementById("assistant-preview-run").click();void 0;');await until(()=>ui('!document.getElementById("assistant-preview-run").disabled'),12000);assert.notEqual(preview.status(owner).id,previous);assert.equal(await preview.view(owner).webContents.executeJavaScript('typeof window.quickRunMarker'),'undefined');assert((await backend.assistant.preview.inspect(run)).dom.text.includes('Live from unsaved code'));assert.equal((await files.read(html)).source,before.source);assert(fs.readFileSync(html).equals(disk));await ui('ltProofUI.connect().replaceRange("Quick Run still live",{line:0,ch:4},{line:0,ch:25});void 0;');await until(async()=>(await backend.assistant.preview.inspect(run)).dom.text.includes('Quick Run still live'));assert.equal(uiRequests.length,requests);assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(html)+')).some(v=>!!cljs.core.get(cljs.core.deref(v),cljs.core.keyword("dirty")))'));});
 await check('Stop during Quick Run prevents a delayed source read from reopening the preview',async()=>{await ui('window.quickRunOperation=ltAssistantEditor.operation;window.quickRunWaiting=false;ltAssistantEditor.operation=async(op,args)=>{if(op==="context"){window.quickRunWaiting=true;await new Promise(resolve=>setTimeout(resolve,500));}return window.quickRunOperation(op,args);};document.getElementById("assistant-preview-run").click();void 0;');await until(()=>ui('window.quickRunWaiting'));await backend.assistant.preview.stop(run);await sleep(700);assert(!require(core+'/revival-preview.cjs').view('assistant:'+host.webContents.id));assert.equal(backend.assistant.diagnostics().views,0);assert(await ui('!document.getElementById("assistant-preview-pane")'));await ui('ltAssistantEditor.operation=window.quickRunOperation;void 0;');assert.equal(manual.exitCode,null);});
 await check('Stop closes assistant previews and command families while preserving a manual program',async()=>{await backend.assistant.preview.stop(run);await backend.assistant.commands.stop(host.webContents.id);assert.equal(manual.exitCode,null);assert.equal(backend.assistant.commands.activeCount(),0);assert.equal(require(core+'/revival-preview.cjs').activeCount(),0);assert(await ui('!document.getElementById("assistant-preview-pane")'));});
 await check('Assistant Stop preserves a preview started through the original live-view controls',async()=>{await ui('ltPreview.openLive('+JSON.stringify(html)+',900000)');const preview=require(core+'/revival-preview.cjs'),manualView=preview.view(host.webContents.id);assert(manualView);const borrowed=await backend.assistant.preview.start(run,{path:html});assert(borrowed.reused);await backend.assistant.preview.stop(run);assert.equal(preview.view(host.webContents.id),manualView);assert.equal(preview.status(host.webContents.id).status,'running');assert.equal(manual.exitCode,null);await ui('ltPreview.stop(false)');});
 await check('An automatic preview starting after file open is reused without launching a duplicate program',async()=>{await ui('ltLive.resume();void 0;');const preview=require(core+'/revival-preview.cjs'),value=await backend.assistant.preview.start(run,{path:html});assert(value.reused);assert.equal(preview.activeCount(),1);assert(!preview.view('assistant:'+host.webContents.id));await backend.assistant.preview.stop(run);assert.equal(preview.status(host.webContents.id).status,'running');await ui('ltPreview.stop()');});
 await check('The original live preview Run button resumes a paused view and restarts the actual unsaved program',async()=>{const preview=require(core+'/revival-preview.cjs'),disk=fs.readFileSync(html);assert(await ui('ltLive.paused()'));await ui('document.getElementById("live-preview-run").click();void 0;');assert(await ui('document.getElementById("live-preview-run").disabled'));await until(()=>ui('!ltLive.state().busy&&!ltLive.paused()'),12000);assert.equal(preview.status(host.webContents.id).status,'running');assert((await preview.view(host.webContents.id).webContents.executeJavaScript('document.body.innerText')).includes('Quick Run still live'));const previous=preview.status(host.webContents.id).id;await ui('document.getElementById("live-preview-run").click();void 0;');await until(()=>ui('!ltLive.state().busy'),12000);assert.notEqual(preview.status(host.webContents.id).id,previous);assert(fs.readFileSync(html).equals(disk));assert(await ui('cljs.core.to_array(lt.objs.editor.pool.by_path('+JSON.stringify(html)+')).some(v=>!!cljs.core.get(cljs.core.deref(v),cljs.core.keyword("dirty")))'));await ui('ltLive.pause()');});
 await check('Abort ends a foreground command family without touching a manual process',async()=>{const abort=new AbortController(),pending=backend.assistant.commands.start(host.webContents.id,{cwd:root,command:'node -e "console.log(\'WAITING\');setInterval(()=>{},1000)"'},abort.signal);await until(()=>backend.assistant.commands.diagnostics().active.some(c=>c.stdout.includes('WAITING')));abort.abort(Error('Stop'));const receipt=await pending;assert.equal(receipt.status,'stopped');assert(receipt.memory.processExited);assert.equal(manual.exitCode,null);});
 await check('Switching projects isolates visible conversation state from the previous project',async()=>{const other=path.join(root,'other');fs.mkdirSync(other);const otherProject=projects.activate(other);await ui('ltProjects.openedFolder('+JSON.stringify(otherProject)+');void 0;');await until(()=>ui('ltAssistantUI.state().root==='+JSON.stringify(other)+'&&ltAssistantUI.state().session===null'));});
 await ui('lt.object.merge_BANG_(lt.objs.opener.opener,cljs.core.hash_map(cljs.core.keyword("open-linked-doc"),window.assistantOldLinked));void 0;');
 await finish();
 }catch(error){await finish(error);}},800));});
backend=require(core+'/main.js');backend.assistant.runtime.settings({contextTokens:65536});
