'use strict';
process.env.LT_REVIVAL_TEST='1';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const core=path.resolve(__dirname,'../../deploy/core'),policy=require(path.join(core,'proof-policy.cjs')),projects=require(path.join(core,'revival-projects.cjs')),modules=require(path.join(core,'proof-modules.cjs')),fixture=require('./package-fixtures.cjs');
const root=path.join(policy.root,'buffer-module-tests',crypto.randomUUID()),receipt=path.resolve(__dirname,'../../.revival/buffer-modules-result.json'),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null,checks=[],hash=source=>crypto.createHash('sha256').update(source).digest('hex');
const write=(folder,name,source)=>fixture.write(folder,name,source);
function buffer(folder,name,source,loader){const file=path.join(folder,name);assert(!fs.existsSync(file));return {path:file,source,...(loader?{loader}:{})};}
async function check(name,fn){const folder=path.join(root,String(checks.length+1));fs.mkdirSync(folder,{recursive:true});projects.activate(folder);try{await fn(folder);checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
async function prepare(folder,source,options={}){return modules.prepare(source,{path:write(folder,'main.ts',source),...options});}
async function evaluate(prepared){return (await import('data:text/javascript;base64,'+Buffer.from(prepared.code).toString('base64'))).default;}
function watch(source,text,id='virtual-total'){const from=source.indexOf(text);assert(from>=0);return {id,from,to:from+text.length,text};}
function virtualRecord(prepared,item){const record=prepared.project.modules.find(value=>value.path===item.path);assert(record,'Missing executed buffer '+item.path);assert.equal(record.origin,'editor');assert.equal(record.source,item.source);assert.equal(record.sha256,hash(item.source));if(item.loader)assert.equal(record.loader,item.loader);assert(!fs.existsSync(item.path));assert(prepared.project.metadata.some(value=>value.path===item.path&&value.exists===false&&value.sha256===null&&value.source===null));return record;}
let result;
(async()=>{try{
 await check('A virtual TypeScript extension outranks an existing JavaScript decoy under a browser map',async folder=>{write(folder,'package.json',{browser:{unrelated:'./unused.js'}});const target=buffer(folder,'answer.tsx','const answer:number=42;export default answer;');write(folder,'answer.js','throw Error("disk extension decoy");');const compiled=await prepare(folder,'import answer from "./answer";answer;',{buffers:[target]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,target);assert(!compiled.project.modules.some(item=>item.name==='answer.js'));});
 await check('Virtual module and main fields retain native import and require priorities',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{module:'./module.js',main:'./main.cjs'});write(folder,'report/index.js','throw Error("index decoy");');const esm=buffer(folder,'report/module.js','export default 42;'),cjs=buffer(folder,'report/main.cjs','module.exports=63;');const imported=await prepare(folder,'import answer from "./report";answer;',{buffers:[esm,cjs]});assert.equal(await evaluate(imported),42);virtualRecord(imported,esm);assert(!imported.project.modules.some(item=>item.path===cjs.path));const required=await prepare(folder,'require("./report");',{buffers:[esm,cjs]});assert.equal(await evaluate(required),63);virtualRecord(required,cjs);assert(!required.project.modules.some(item=>item.path===esm.path));});
 await check('A virtual browser-string entry outranks saved module main and index entries',async folder=>{write(folder,'package.json',{browser:{}});const manifest=write(folder,'report/package.json',{browser:'./web.js',module:'./module.js',main:'./main.js'}),target=buffer(folder,'report/web.js','const answer:number=42;export default answer;','ts');for(const name of ['module.js','main.js','index.js'])write(folder,'report/'+name,'throw Error("saved field decoy");');for(const expression of ['import answer from "./report";answer;','require("./report").default;']){const compiled=await prepare(folder,expression,{buffers:[target]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,target);assert(compiled.project.metadata.some(item=>item.path===manifest&&item.sha256===hash(fs.readFileSync(manifest))));}});
 await check('A main-directory virtual index does not recurse through its saved package main',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{main:'./dist'});write(folder,'report/dist/package.json',{main:'./wrong.js'});write(folder,'report/dist/wrong.js','throw Error("recursive package decoy");');const target=buffer(folder,'report/dist/index.ts','export default 42 as number;'),compiled=await prepare(folder,'import answer from "./report";answer;',{buffers:[target]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,target);assert(!compiled.project.modules.some(item=>item.name.endsWith('wrong.js')));});
 await check('One-hop browser remapping executes only the selected virtual target',async folder=>{write(folder,'package.json',{browser:{'./a.js':'./b.js','./b.js':'./c.js'}});const a=buffer(folder,'a.js','throw Error("original virtual decoy");'),b=buffer(folder,'b.js','export default 42;'),c=buffer(folder,'c.js','throw Error("second-hop virtual decoy");'),compiled=await prepare(folder,'import answer from "./a.js";answer;',{buffers:[a,b,c]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,b);assert(!compiled.project.modules.some(item=>item.path===a.path||item.path===c.path));});
 await check('A browser-map cycle still performs one hop without recursing',async folder=>{write(folder,'package.json',{browser:{'./a.js':'./b.js','./b.js':'./a.js'}});const a=buffer(folder,'a.js','throw Error("cycle source decoy");'),b=buffer(folder,'b.js','export default 42;'),compiled=await prepare(folder,'import answer from "./a.js";answer;',{buffers:[a,b]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,b);});
 await check('A nested empty browser object owns scope and blocks an ancestor mapping',async folder=>{write(folder,'package.json',{browser:{'./leaf/value.js':'./web.js'}});write(folder,'leaf/package.json',{browser:{}});const original=buffer(folder,'leaf/value.js','export default 42;'),web=buffer(folder,'web.js','throw Error("ancestor mapping decoy");'),compiled=await prepare(folder,'import answer from "./leaf/value.js";answer;',{buffers:[original,web]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,original);assert(!compiled.project.modules.some(item=>item.path===web.path));});
 await check('A nested manifest without a browser object retains the ancestor mapping',async folder=>{write(folder,'package.json',{browser:{'./leaf/value.js':'./web.js'}});write(folder,'leaf/package.json',{name:'leaf'});const original=buffer(folder,'leaf/value.js','throw Error("unmapped nested decoy");'),web=buffer(folder,'web.js','export default 42;'),compiled=await prepare(folder,'import answer from "./leaf/value.js";answer;',{buffers:[original,web]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,web);assert(!compiled.project.modules.some(item=>item.path===original.path));});
 await check('Browser false suppresses throwing virtual code while bare replacements use installed exports',async folder=>{write(folder,'package.json',{browser:{'./disabled.js':false,'./server.js':'leaf'}});fixture.install(folder,'leaf',{exports:{browser:'./browser.cjs',default:'./decoy.cjs'}},{'browser.cjs':'module.exports=42;','decoy.cjs':'throw Error("default package decoy");'});const disabled=buffer(folder,'disabled.js','throw Error("disabled virtual decoy");'),server=buffer(folder,'server.js','throw Error("bare alias source decoy");'),compiled=await prepare(folder,'import empty from "./disabled.js";import answer from "./server.js";({answer,empty:Object.keys(empty).length});',{buffers:[disabled,server]});assert.deepEqual(await evaluate(compiled),{answer:42,empty:0});assert(!compiled.project.modules.some(item=>item.path===disabled.path||item.path===server.path));assert(compiled.project.packages.some(item=>item.name==='leaf'));});
 await check('Watched virtual typed main shares initialization and original values through static and lazy imports',async folder=>{write(folder,'package.json',{browser:{unrelated:'./unused.js'}});write(folder,'orders.calc/package.json',{main:'./report.js'});const source='// 😀\r\nglobalThis.virtualInitializations=(globalThis.virtualInitializations||0)+1;export function total(value:number){return (value * 2) as number;}',target=buffer(folder,'orders.calc/report.js',source,'ts'),compiled=await prepare(folder,'import {total} from "./orders.calc";const first=total(21);import("./orders.calc").then(second=>({first,second:second.total(21),count:globalThis.virtualInitializations,same:second.total===total}));',{buffers:[target],watchFiles:[{...target,watches:[watch(source,'(value * 2) as number')]}]}),values=[];globalThis[compiled.watch.key]=(id,value)=>{values.push(value);return value;};delete globalThis.virtualInitializations;try{assert.deepEqual(await evaluate(compiled),{first:42,second:42,count:1,same:true});assert.deepEqual(values,[42,42]);virtualRecord(compiled,target);assert.equal(compiled.project.modules.filter(item=>item.path===target.path).length,1);}finally{delete globalThis[compiled.watch.key];delete globalThis.virtualInitializations;}});
 await check('Virtual typed runtime errors map to original CRLF and UTF-16 source through watches',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{main:'./entry.js'});const source='// 😀\r\nexport function fail(n:number){const value=(n * 2) as number;throw new Error("virtual source failed");}',target=buffer(folder,'report/entry.js',source,'ts'),compiled=await prepare(folder,'import {fail} from "./report";fail(21);',{buffers:[target],watchFiles:[{...target,watches:[watch(source,'(n * 2) as number')]}]});globalThis[compiled.watch.key]=(id,value)=>value;try{await assert.rejects(()=>evaluate(compiled),error=>{const failure=modules.runtimeError(compiled,{error:error.message,stack:error.stack});assert.equal(failure.location.path,target.path);assert.equal(failure.location.line,2);assert.equal(failure.location.column,source.split('\r\n')[1].indexOf('new Error')+1);assert.equal(failure.location.source,source);assert.equal(failure.location.sha256,hash(source));return true;});virtualRecord(compiled,target);}finally{delete globalThis[compiled.watch.key];}});
 await check('Creating changing and deleting a virtual selected path changes disk identity without replacing its dirty source',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{main:'./entry.js'});const target=buffer(folder,'report/entry.js','export default 42;'),source='import answer from "./report";answer;',first=await prepare(folder,source,{buffers:[target]});assert.equal(await evaluate(first),42);virtualRecord(first,target);write(folder,'report/entry.js','export default 99;');const created=await prepare(folder,source,{buffers:[target]});assert.equal(await evaluate(created),42);assert.notEqual(created.project.sha256,first.project.sha256);write(folder,'report/entry.js','export default 105;');const changed=await prepare(folder,source,{buffers:[target]});assert.equal(await evaluate(changed),42);assert.notEqual(changed.project.sha256,created.project.sha256);fs.unlinkSync(target.path);const deleted=await prepare(folder,source,{buffers:[target]});assert.equal(await evaluate(deleted),42);assert.equal(deleted.project.sha256,first.project.sha256);assert.equal(await evaluate(first),42);virtualRecord(deleted,target);});
 await check('Closer virtual extension creation changes selection while prior compiled code stays pinned',async folder=>{write(folder,'package.json',{browser:{}});const js=buffer(folder,'answer.js','export default 42;'),source='import answer from "./answer";answer;',first=await prepare(folder,source,{buffers:[js]});assert.equal(await evaluate(first),42);const ts=buffer(folder,'answer.ts','export default 63 as number;'),next=await prepare(folder,source,{buffers:[js,ts]});assert.equal(await evaluate(next),63);assert.notEqual(next.project.sha256,first.project.sha256);assert.equal(await evaluate(first),42);virtualRecord(next,ts);assert(!next.project.modules.some(item=>item.path===js.path));});
 await check('Dirty saved or virtual package metadata cannot redefine buffer-only resolution',async folder=>{write(folder,'package.json',{browser:{}});const manifest=write(folder,'report/package.json',{main:'./entry.js'}),target=buffer(folder,'report/entry.js','export default 42;');await assert.rejects(()=>prepare(folder,'import answer from "./report";answer;',{buffers:[target,{path:manifest,source:'{"main":"./other.js"}'}]}),/Save package.json/);fs.unlinkSync(manifest);await assert.rejects(()=>prepare(folder,'import answer from "./report";answer;',{buffers:[target,{path:manifest,source:'{"main":"./entry.js"}'}]}),/Save package.json/);});
 await check('Virtual preferred entries still enforce project confinement before decoys can execute',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{browser:'../../outside.js',main:'./entry.js'});const target=buffer(folder,'report/entry.js','export default 42;');await assert.rejects(()=>prepare(folder,'import answer from "./report";answer;',{buffers:[target]}),/leaves the project/);});
 await check('Child browser fields participate even when the importing project has no browser map',async folder=>{write(folder,'package.json',{name:'plain-root'});for(const [index,browser] of ['./web.js',{'./entry.js':'./web.js'}].entries()){const directory='report'+index;write(folder,directory+'/package.json',{browser,main:'./entry.js'});write(folder,directory+'/entry.js','throw Error("child browser main decoy");');const target=buffer(folder,directory+'/web.js','export default 42 as number;','ts'),compiled=await prepare(folder,'import answer from '+JSON.stringify('./'+directory)+';answer;',{buffers:[target]});assert.equal(await evaluate(compiled),42);virtualRecord(compiled,target);assert(!compiled.project.modules.some(item=>item.name.endsWith('entry.js')));}});
 await check('Projects without browser participation retain established local extension order with virtual alternatives',async folder=>{write(folder,'package.json',{name:'plain-root'});const disk=write(folder,'answer.js','export default 42;'),unused=buffer(folder,'answer.tsx','throw Error("inactive native-priority decoy");'),compiled=await prepare(folder,'import answer from "./answer";answer;',{buffers:[unused]});assert.equal(await evaluate(compiled),42);assert(compiled.project.modules.some(item=>item.path===disk));assert(!compiled.project.modules.some(item=>item.path===unused.path));assert(!compiled.project.metadata.some(item=>item.path===unused.path));});
 await check('Virtual sources keep isolated file size and total source limits',async folder=>{write(folder,'package.json',{browser:{}});const oversized=buffer(folder,'answer.js','export default 42;'+' '.repeat(16384));await assert.rejects(()=>prepare(folder,'import answer from "./answer.js";answer;',{buffers:[oversized]}),/source budget/);const inputs=Array.from({length:5},(_,index)=>buffer(folder,'part'+index+'.js','export const value=1;'+' '.repeat(15000))),source=inputs.map((item,index)=>'import {value as value'+index+'} from "./part'+index+'.js";').join('')+'value0;';await assert.rejects(()=>prepare(folder,source,{buffers:inputs}),/source budget/);});
 await check('Virtual resolution observes cancellation before executing authored code',async folder=>{write(folder,'package.json',{browser:{}});const target=buffer(folder,'answer.js','throw Error("cancelled buffer must not execute");'),controller=new AbortController();controller.abort();await assert.rejects(()=>modules.prepare('import answer from "./answer.js";answer;',{path:write(folder,'main.ts',''),buffers:[target]},controller.signal),/cancelled/);});
 result={passed:true,checks,root};
 }catch(error){result={passed:false,checks,root,error:error.stack};process.exitCode=1;}finally{modules.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);fs.mkdirSync(path.dirname(receipt),{recursive:true});fs.writeFileSync(receipt,JSON.stringify(result,null,2));if(!result.passed){const first=receipt.replace(/\.json$/,'.first-failure.json');if(!fs.existsSync(first))fs.writeFileSync(first,JSON.stringify(result,null,2));}process.stdout.write(JSON.stringify(result,null,2)+'\n');}
})();
