'use strict';
process.env.LT_REVIVAL_TEST='1';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm'),{EventEmitter}=require('events'),{createRequire}=require('module');
const core=path.resolve(__dirname,'../../deploy/core'),policy=require(path.join(core,'proof-policy.cjs')),projects=require(path.join(core,'revival-projects.cjs')),modules=require(path.join(core,'proof-modules.cjs')),files=require(path.join(core,'revival-preview-files.cjs')),configurations=require(path.join(core,'revival-compiler-config.cjs')),previewPackages=require(path.join(core,'revival-preview-packages.cjs')),fixture=require('./package-fixtures.cjs');
const root=path.join(policy.root,'config-error-tests',crypto.randomUUID()),receipt=path.resolve(__dirname,'../../.revival/config-errors-result.json'),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null,checks=[],hash=source=>crypto.createHash('sha256').update(source).digest('hex');
const write=(folder,name,source)=>fixture.write(folder,name,source),broken='\uFEFF{\r\n // 😀 comment and a permitted trailing comma\r\n "compilerOptions": {"jsxFactory":"😀", "paths": ?},\r\n}\r\n';
function physical(source,offset){let line=1,start=0;for(let index=0;index<offset;index++){if(source[index]==='\r'){if(source[index+1]==='\n'&&index+1<offset)index++;line++;start=index+1;}else if(source[index]==='\n'){line++;start=index+1;}}let end=start;while(end<source.length&&!/[\r\n]/.test(source[end]))end++;return {line,column:offset-start+1,sourceLine:source.slice(start,end)};}
function expectLocation(error,file,source,offset=source.indexOf('?')){const item=error.location,point=physical(source,offset);assert(item,error.stack);assert.equal(item.kind,'compiler-configuration');assert.equal(item.path,file);assert.equal(item.name,path.relative(projects.info().recents[0].path,file));assert.equal(item.offset,offset);assert.equal(item.line,point.line);assert.equal(item.column,point.column);assert.equal(item.sourceLine,point.sourceLine);assert.equal(item.source,source);assert.equal(item.sha256,hash(source));assert.equal(item.loader,undefined);return true;}
async function rejected(work,file,source,offset){let failure;await assert.rejects(work,error=>{failure=error;return expectLocation(error,file,source,offset);});return failure;}
async function check(name,fn){const folder=path.join(root,String(checks.length+1));fs.mkdirSync(folder,{recursive:true});projects.activate(folder);try{await fn(folder);checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
function watch(source,text){const from=source.indexOf(text);assert(from>=0);return {id:'config-value',from,to:from+text.length,text};}
async function isolated(folder,source='const value:number=42;value;',options={}){const file=options.path||write(folder,'main.ts',source);return modules.prepare(source,{path:file,...options});}
async function captured(file,options,fn){const page=files.prepare({path:file,...options},'lt-preview://config-errors');try{await page.compile();return await fn(page);}finally{await page.close();}}
async function failedCapture(file,options,config,source){const page=files.prepare({path:file,...options},'lt-preview://config-errors');try{return await rejected(()=>page.compile(),config,source);}finally{await page.close();}}
async function evaluate(prepared){return (await import('data:text/javascript;base64,'+Buffer.from(prepared.code).toString('base64'))).default;}
async function execute(page){const context=vm.createContext({}),loaded=new Map();async function module(address){if(loaded.has(address))return loaded.get(address);const item=new vm.SourceTextModule(page.response(page.fromURL(address)).toString('utf8'),{context,identifier:address});loaded.set(address,item);return item;}const link=(specifier,owner)=>module(new URL(specifier,owner.identifier).href);for(const script of page.html.matchAll(/<script\b[^>]*\bsrc="([^"]+)"/g)){const item=await module(new URL(script[1],page.url).href);if(item.status==='unlinked')await item.link(link);if(item.status==='linked')await item.evaluate();}return context;}
function trustedModule(name,overrides={},date=Date){const file=path.join(core,name),nativeRequire=createRequire(file),output={exports:{}};vm.runInThisContext('(function(require,module,exports,__filename,__dirname,Date){'+fs.readFileSync(file,'utf8')+'\n})',{filename:file})(id=>Object.hasOwn(overrides,id)?overrides[id]:nativeRequire(id),output,output.exports,file,core,date);return output.exports;}
function browserRoute(){
 // Exercise the actual browser-selection planner/catch without starting an
 // Electron renderer, a Windows Job, or evaluating authored page code.
 let jobs=0,selectionExecutions=0;const commands=[],plans=[];
 class Contents extends EventEmitter{constructor(){super();this.destroyed=false;this.session={setPermissionRequestHandler(){},setPermissionCheckHandler(){},webRequest:{onBeforeRequest(){}},protocol:{handle(){}}};this.debugger=new EventEmitter();this.debugger.attach=()=>{};this.debugger.sendCommand=async(method,value={})=>{commands.push({method,...value});if(value.expression?.startsWith('document.open();'))queueMicrotask(()=>this.debugger.emit('message',{},'Page.loadEventFired',{}));if(value.expression?.startsWith('Promise.resolve((0,eval)'))selectionExecutions++;return {result:{value:'42'}};};}setBackgroundThrottling(){}invalidate(){}async capturePage(){return {isEmpty:()=>false};}setWindowOpenHandler(){}async loadURL(){}getOSProcessId(){return 98765;}isDestroyed(){return this.destroyed;}close(){this.destroyed=true;}}
 class View{constructor(){this.webContents=new Contents();}setBounds(){}setVisible(){}}
 const memory={async start(){},async attach(){jobs++;return {metadata:{limitMiB:192,hardQuota:true},async release(){jobs--;return {processExited:true};}};},status(){return {jobs};}},host={isDestroyed:()=>false,contentView:{addChildView(){},removeChildView(){}}};
 const api=trustedModule('revival-preview.cjs',{'electron':{protocol:{registerSchemesAsPrivileged(){}},BrowserWindow:{getAllWindows:()=>[]},WebContentsView:View},'./proof-memory.cjs':memory,'./proof-modules.cjs':{...modules,async prepare(...args){const plan=await modules.prepare(...args);plans.push(plan);return plan;}}});return {api,host,jobs:()=>jobs,selectionExecutions:()=>selectionExecutions,commands,plans};
}
let result;
(async()=>{try{
 await check('Isolated typed onLoad errors retain BOM, CRLF and UTF-16 configuration coordinates',async folder=>{const config=write(folder,'tsconfig.json',broken);await rejected(()=>isolated(folder),config,broken);});
 await check('Isolated JS resolver failures choose the configuration instead of the importer',async folder=>{const config=write(folder,'tsconfig.json',broken),source='// 😀\r\nimport answer from "@report/value";answer;',file=write(folder,'main.mjs',source);await rejected(()=>modules.prepare(source,{path:file}),config,broken);});
 await check('A preferred config error keeps its own message alongside an unrelated missing import',async folder=>{const config=write(folder,'tsconfig.json',broken),source='import absent from "./missing.mjs";\r\nimport answer from "@report/value";\r\n[absent,answer];',file=write(folder,'main.mjs',source),error=await rejected(()=>modules.prepare(source,{path:file}),config,broken),details=error.cause?.errors;assert(details?.length>=2,'Real compilation must retain both independent failures');assert.match(details[0].text,/missing\.mjs/,'The fixture must put the unrelated missing-module diagnostic first');assert.match(error.message,/Invalid compiler configuration/);assert.doesNotMatch(error.message,/Module not found|Could not resolve/);});
 await check('Inserted original watches cannot shift configuration source locations',async folder=>{const config=write(folder,'tsconfig.json',broken),source='const value:number=21;value * 2;';await rejected(()=>isolated(folder,source,{watches:[watch(source,'value * 2')]}),config,broken);});
 await check('Relative inherited configuration errors identify the parent JSONC source',async folder=>{write(folder,'tsconfig.json',{extends:'./config/base.json'});const source='{\r// 😀 lone-CR comment\r"compilerOptions":{"paths":?}\r}',config=write(folder,'config/base.json',source);await rejected(()=>isolated(folder),config,source);});
 await check('Installed configuration package errors identify its inherited source',async folder=>{fixture.install(folder,'paint-config',{tsconfig:'base.json'},{'base.json':broken});write(folder,'tsconfig.json',{extends:'paint-config'});await rejected(()=>isolated(folder),path.join(folder,'node_modules/paint-config/base.json'),broken);});
 await check('Malformed configuration package manifests preserve their own UTF-16 source',async folder=>{fixture.install(folder,'paint-config',{tsconfig:'base.json'},{'base.json':'{}'});const source='\uFEFF{\r\n"name":"😀", "tsconfig":?\r\n}',config=write(folder,'node_modules/paint-config/package.json',source);write(folder,'tsconfig.json',{extends:'paint-config'});await rejected(()=>isolated(folder),config,source);});
 await check('Typed selection compilation keeps config identity separate from its short selection',async folder=>{const file=write(folder,'main.ts','// 😀 whole editor\r\nconst original:number=0;'),config=write(folder,'tsconfig.json',broken);await rejected(()=>modules.prepare('(21 as number) * 2',{path:file,loader:'ts',inline:true}),config,broken);assert.equal(fs.readFileSync(file,'utf8'),'// 😀 whole editor\r\nconst original:number=0;');});
 await check('Browser selection planning preserves exact config errors without executing or stopping the page',async folder=>{const file=write(folder,'main.ts','globalThis.answer=42;'),config=write(folder,'tsconfig.json','{}'),route=browserRoute();try{await route.api.start('config-selection',{path:file},route.host);assert.equal(route.jobs(),1);write(folder,'tsconfig.json',broken);await rejected(()=>route.api.evaluate('config-selection','(21 as number) * 2',{path:file,loader:'ts',lineOffset:70,columnOffset:13,bufferSource:'// unsaved 😀\r\n(21 as number) * 2'}),config,broken);assert.equal(route.selectionExecutions(),0);assert.equal(route.api.status('config-selection').status,'running');assert.equal(route.jobs(),1);}finally{await route.api.shutdown();assert.equal(route.jobs(),0);assert.equal(route.api.activeCount(),0);}});
 await check('Live selections parse newly saved inherited metadata rather than the old page snapshot',async folder=>{const file=write(folder,'main.ts','globalThis.answer=42;'),config=write(folder,'base.json','{}'),route=browserRoute();write(folder,'tsconfig.json',{extends:'./base.json'});try{await route.api.start('config-selection',{path:file},route.host);const record=route.api.status('config-selection').project.files.find(item=>item.path===config);assert.equal(record.snapshotRole,'metadata');write(folder,'base.json',broken);const error=await rejected(()=>route.api.evaluate('config-selection','(21 as number) * 2',{path:file,loader:'ts'}),config,broken);assert.match(error.message,/Invalid compiler configuration/);assert.doesNotMatch(error.message,/Save compiler configuration/);assert.equal(route.selectionExecutions(),0);assert.equal(route.jobs(),1);assert.equal(route.api.status('config-selection').status,'running');}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 await check('Valid saved metadata drift refuses live selection before execution and preserves the old page',async folder=>{const file=write(folder,'main.ts','globalThis.answer=42;'),config=write(folder,'tsconfig.json','{}'),route=browserRoute();try{const initial=await route.api.start('config-selection',{path:file},route.host);write(folder,'tsconfig.json',{compilerOptions:{useDefineForClassFields:false}});await assert.rejects(()=>route.api.evaluate('config-selection','(21 as number) * 2',{path:file,loader:'ts'}),/metadata changed.*Refresh the preview/);assert.equal(route.selectionExecutions(),0);assert.equal(route.api.status('config-selection').id,initial.id);assert.equal(route.api.status('config-selection').status,'running');assert.equal(route.jobs(),1);fs.writeFileSync(config,'{}');await route.api.evaluate('config-selection','(21 as number) * 2',{path:file,loader:'ts'});assert.equal(route.selectionExecutions(),1);assert.equal(route.api.status('config-selection').id,initial.id);}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 await check('Current unsaved config metadata still rejects with the saved source while the page stays alive',async folder=>{const file=write(folder,'main.ts','globalThis.answer=42;'),savedSource='{\r\n"compilerOptions":{}\r\n}',config=write(folder,'tsconfig.json',savedSource),route=browserRoute();try{await route.api.start('config-selection',{path:file},route.host);const error=await rejected(()=>route.api.evaluate('config-selection','(21 as number) * 2',{path:file,loader:'ts',buffers:[{path:config,source:'{"compilerOptions":{"useDefineForClassFields":false}}'}]}),config,savedSource,0);assert.match(error.message,/Save compiler configuration/);assert.equal(fs.readFileSync(config,'utf8'),savedSource);assert.equal(route.selectionExecutions(),0);assert.equal(route.jobs(),1);await assert.rejects(()=>route.api.evaluate('config-selection','42 as number',{path:file,loader:'ts',buffers:[{path:file,source:'globalThis.answer=63;'}]}),/must contain captured compiler or package metadata/);assert.equal(route.selectionExecutions(),0);}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 await check('Executable JSON dependencies retain captured code buffers during live selection planning',async folder=>{const data=write(folder,'data.json',{answer:42}),file=write(folder,'main.ts','import data from "./data.json";globalThis.answer=data.answer;'),route=browserRoute();write(folder,'tsconfig.json','{}');try{await route.api.start('config-selection',{path:file},route.host);const record=route.api.status('config-selection').project.files.find(item=>item.path===data);assert.equal(record.snapshotRole,undefined);write(folder,'data.json',{answer:63});await route.api.evaluate('config-selection','import data from "./data.json";data.answer as number;',{path:file,loader:'ts'});assert.equal(route.plans.length,1);assert.equal(await evaluate(route.plans[0]),42);assert.equal(route.plans[0].project.modules.find(item=>item.path===data).sha256,hash(record.source));assert.equal(fs.readFileSync(data,'utf8'),'{"answer":63}');assert.equal(route.selectionExecutions(),1);}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 await check('Captured typed module onLoad errors retain exact configuration coordinates',async folder=>{const config=write(folder,'tsconfig.json',broken),file=write(folder,'main.ts','globalThis.answer=42;');await failedCapture(file,{},config,broken);});
 await check('Captured JS alias resolver failures prioritize config source over importer mappings',async folder=>{const config=write(folder,'tsconfig.json',broken),file=write(folder,'main.mjs','// 😀\r\nimport answer from "@report/value";globalThis.answer=answer;');await failedCapture(file,{},config,broken);});
 await check('Captured external typed classics report config errors before split compilation',async folder=>{const config=write(folder,'tsconfig.json',broken),source='var answer:number=42;',classic=write(folder,'classic.js',source),file=write(folder,'index.html','<script src="classic.js"></script>');await failedCapture(file,{buffers:[{path:classic,source,loader:'ts'}]},config,broken);assert.equal(fs.readFileSync(classic,'utf8'),source);});
 await check('Captured watch instrumentation cannot reinterpret a configuration failure',async folder=>{const config=write(folder,'tsconfig.json',broken),source='const n:number=21;globalThis.answer=n * 2;',file=write(folder,'main.ts',source);await failedCapture(file,{watches:[watch(source,'n * 2')]},config,broken);});
 await check('Captured relative extends errors retain the malformed parent and its physical lines',async folder=>{write(folder,'tsconfig.json',{extends:['./first.json','./base.json']});write(folder,'first.json',{compilerOptions:{jsxFactory:'h'}});const config=write(folder,'base.json',broken),file=write(folder,'main.tsx','const h=(...args:any[])=>args;globalThis.view=<output/>;');await failedCapture(file,{},config,broken);});
 await check('Captured installed extends errors retain the package configuration source',async folder=>{fixture.install(folder,'paint-config',{tsconfig:'base.json'},{'base.json':broken});write(folder,'tsconfig.json',{extends:'paint-config'});const file=write(folder,'main.ts','globalThis.answer=42;');await failedCapture(file,{},path.join(folder,'node_modules/paint-config/base.json'),broken);});
 await check('Captured package manifest errors preserve their cause through esbuild detail',async folder=>{fixture.install(folder,'paint-config',{tsconfig:'base.json'},{'base.json':'{}'});const source='{\r\n"name":"😀", "tsconfig":?\r\n}',config=write(folder,'node_modules/paint-config/package.json',source);write(folder,'tsconfig.json',{extends:'paint-config'});const file=write(folder,'main.mjs','import value from "bare-package";globalThis.answer=value;');await failedCapture(file,{},config,source);});
 await check('Saving a repaired config restores isolated execution and changes captured config identity',async folder=>{const config=write(folder,'tsconfig.json',broken),source='class Base{set value(n:number){globalThis.__configAnswer=n;}}class Child extends Base{value=42;}new Child();globalThis.__configAnswer;',file=write(folder,'main.ts',source);await rejected(()=>modules.prepare(source,{path:file}),config,broken);try{write(folder,'tsconfig.json',{compilerOptions:{useDefineForClassFields:false}});const first=await modules.prepare(source,{path:file});assert.equal(await evaluate(first),42);const capturedConfig=first.project.metadata.find(item=>item.path===config);assert.equal(capturedConfig.source,fs.readFileSync(config,'utf8'));assert.equal(capturedConfig.sha256,hash(capturedConfig.source));delete globalThis.__configAnswer;write(folder,'tsconfig.json',{compilerOptions:{useDefineForClassFields:true}});const second=await modules.prepare(source,{path:file});assert.notEqual(second.project.sha256,first.project.sha256);assert.equal(await evaluate(second),undefined);assert.equal(fs.readFileSync(file,'utf8'),source);}finally{delete globalThis.__configAnswer;}});
 await check('Repaired preview configuration reloads while prior compiled styles of class fields stay pinned',async folder=>{const config=write(folder,'tsconfig.json',broken),source='class Base{set value(n:number){globalThis.answer=n;}}class Child extends Base{value=42;}new Child();',file=write(folder,'main.ts',source);await failedCapture(file,{},config,broken);write(folder,'tsconfig.json',{compilerOptions:{useDefineForClassFields:false}});await captured(file,{},async first=>{const identity=first.snapshot().sha256;assert.equal((await execute(first)).answer,42);write(folder,'tsconfig.json',{compilerOptions:{useDefineForClassFields:true}});assert.equal((await execute(first)).answer,42);await captured(file,{},async second=>{assert.notEqual(second.snapshot().sha256,identity);assert.equal((await execute(second)).answer,undefined);const metadata=second.snapshot().files.find(item=>item.path===config);assert.equal(metadata.source,fs.readFileSync(config,'utf8'));assert.equal(metadata.sha256,hash(metadata.source));});});assert.equal(fs.readFileSync(file,'utf8'),source);});
 await check('Oversized configs remain rejected under the same 64 KiB, 128 path, 1 MiB and depth limits',async folder=>{assert.deepEqual(configurations.limits,{files:128,fileBytes:65536,totalBytes:1024*1024,depth:32});write(folder,'tsconfig.json',' '.repeat(65537));const source='const answer:number=42;answer;',file=write(folder,'main.ts',source);await assert.rejects(()=>modules.prepare(source,{path:file}),/64 KiB/);const page=files.prepare({path:file},'lt-preview://config-limits');try{await assert.rejects(()=>page.compile(),/64 KiB/);}finally{await page.close();}assert.equal(previewPackages.limits.compileMs,5000);assert.equal(files.limits.fileBytes,2*1024*1024);});
 await check('Deep config inheritance still respects the bounded 32-level compilation contract',async folder=>{write(folder,'tsconfig.json',{extends:'./level-0.json'});for(let index=0;index<34;index++)write(folder,'level-'+index+'.json',index===33?{}:{extends:'./level-'+(index+1)+'.json'});const source='const answer:number=42;answer;',file=write(folder,'main.ts',source);await assert.rejects(()=>modules.prepare(source,{path:file}),/32 levels/);const page=files.prepare({path:file},'lt-preview://config-depth');try{await assert.rejects(()=>page.compile(),/32 levels/);}finally{await page.close();}});
 await check('Compiler configuration traversal retains the isolated five-second deadline',async folder=>{let clock=1000,disposed=0;const nativeCompiler=require(path.join(core,'node_modules/esbuild')),compiler={...nativeCompiler,async context(options){const context=await nativeCompiler.context(options),dispose=context.dispose.bind(context);context.dispose=async()=>{disposed++;await dispose();};return context;}},config={...configurations,create(options){return configurations.create({...options,aborted(){clock=6000;options.aborted();}});}},api=trustedModule('proof-modules.cjs',{'esbuild':compiler,'./revival-compiler-config.cjs':config},{now:()=>clock}),source='const answer:number=42;answer;',file=write(folder,'main.ts',source);write(folder,'tsconfig.json','{}');await assert.rejects(()=>api.prepare(source,{path:file}),/compilation exceeded 5 seconds/);assert.equal(disposed,1);});
 await check('Typed live selections import a captured virtual source using its separate absent disk identity',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{main:'./entry.js'});const target=path.join(folder,'report/entry.js'),current='export default 42 as number;',file=write(folder,'main.ts','import answer from "./report";globalThis.answer=answer;'),route=browserRoute();try{const initial=await route.api.start('virtual-selection',{path:file,buffers:[{path:target,source:current,loader:'ts'}]},route.host),record=initial.project.files.find(item=>item.path===target);assert.equal(record.exists,true);assert.equal(record.resolutionSha256,null);assert.equal(record.origin,'editor');await route.api.evaluate('virtual-selection','import answer from "./report";answer as number;',{path:file,loader:'ts'});assert.equal(route.selectionExecutions(),1);assert.equal(await evaluate(route.plans[0]),42);assert.equal(route.plans[0].project.modules.find(item=>item.path===target).source,current);assert.equal(route.api.status('virtual-selection').id,initial.id);assert.equal(route.jobs(),1);assert(!fs.existsSync(target));}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 await check('Typed virtual imports refuse new disk resolution identity until Refresh while preserving dirty captured code',async folder=>{write(folder,'package.json',{browser:{}});write(folder,'report/package.json',{main:'./entry.js'});const target=path.join(folder,'report/entry.js'),current='export default 42 as number;',file=write(folder,'main.ts','import answer from "./report";globalThis.answer=answer;'),route=browserRoute(),options={path:file,buffers:[{path:target,source:current,loader:'ts'}]};try{const initial=await route.api.start('virtual-selection',options,route.host);write(folder,'report/entry.js','export default 99;');await assert.rejects(()=>route.api.evaluate('virtual-selection','import answer from "./report";answer as number;',{path:file,loader:'ts'}),/metadata changed.*Refresh the preview/);assert.equal(route.selectionExecutions(),0);assert.equal(route.api.status('virtual-selection').id,initial.id);assert.equal(route.jobs(),1);const refreshed=await route.api.start('virtual-selection',options,route.host),record=refreshed.project.files.find(item=>item.path===target);assert.equal(record.resolutionSha256,hash('export default 99;'));assert.equal(record.source,current);await route.api.evaluate('virtual-selection','import answer from "./report";answer as number;',{path:file,loader:'ts'});assert.equal(route.selectionExecutions(),1);assert.equal(await evaluate(route.plans.at(-1)),42);fs.unlinkSync(target);await assert.rejects(()=>route.api.evaluate('virtual-selection','import answer from "./report";answer as number;',{path:file,loader:'ts'}),/metadata changed.*Refresh the preview/);assert.equal(route.selectionExecutions(),1);assert.equal(route.api.status('virtual-selection').status,'running');}finally{await route.api.shutdown();assert.equal(route.jobs(),0);}});
 result={passed:true,checks,root};
 }catch(error){result={passed:false,checks,root,error:error.stack};process.exitCode=1;}finally{modules.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);fs.mkdirSync(path.dirname(receipt),{recursive:true});fs.writeFileSync(receipt,JSON.stringify(result,null,2));if(!result.passed){const first=receipt.replace(/\.json$/,'.first-failure.json');if(!fs.existsSync(first))fs.writeFileSync(first,JSON.stringify(result,null,2));}process.stdout.write(JSON.stringify(result,null,2)+'\n');}
})();
