'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const compiler=require('../../deploy/core/revival-compiler-config.cjs'),runtime=path.resolve(__dirname,'../../.revival'),root=path.join(runtime,'config-parser',crypto.randomUUID()),checks=[];
fs.mkdirSync(root,{recursive:true});
const hash=source=>crypto.createHash('sha256').update(source).digest('hex');
const write=(folder,name,source)=>{const file=path.join(folder,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,source);return file;};
function check(name,fn){const folder=path.join(root,String(checks.length));fs.mkdirSync(folder,{recursive:true});fn(folder);checks.push(name);}
function failure(folder,source,wanted){const file=write(folder,'tsconfig.json',source);let error;try{compiler.create({root:folder}).forFile(path.join(folder,'main.ts'));}catch(caught){error=caught;}assert(error,'Expected invalid configuration');const location=compiler.fromError(error);assert(location,'Missing explicit config location');assert.equal(location.kind,'compiler-configuration');assert.equal(location.path,file);assert.equal(location.name,'tsconfig.json');assert.equal(location.source,source);assert.equal(location.sha256,hash(source));assert.equal(location.offset,wanted);return location;}
let result;try{
 check('Native JSON value, duplicate-key and prototype semantics survive JSONC cleaning',()=>{const source='\uFEFF{ // 😀\r\n "__proto__":{"answer":42},"duplicate":1,"duplicate":2,"wide":1e400,"negative":-0,"text":"/*not a comment*/,]\\n","items":[null,true,false,],}';const actual=compiler.jsonc(source),expected=JSON.parse('{"__proto__":{"answer":42},"duplicate":1,"duplicate":2,"wide":1e400,"negative":-0,"text":"/*not a comment*/,]\\n","items":[null,true,false]}');assert.deepEqual(actual,expected);assert.equal(Object.getPrototypeOf(actual),Object.prototype);assert(Object.hasOwn(actual,'__proto__'));assert(Object.is(actual.negative,-0));});
 check('BOM, comments, trailing commas and astral UTF-16 bytes keep the exact invalid value offset',folder=>{const source='\uFEFF{\r\n // 😀 source\r\n "compilerOptions": {"jsxFactory":"h",},\r\n "bad": @\r\n}';const location=failure(folder,source,source.indexOf('@'));assert.equal(location.line,4);assert.equal(location.column,9);assert.equal(location.sourceLine,' "bad": @');});
 check('Lone CR configuration lines use physical line/column coordinates',folder=>{const source='{\r "note":"😀",\r "bad": @\r}';const location=failure(folder,source,source.indexOf('@'));assert.equal(location.line,3);assert.equal(location.column,9);assert.equal(location.sourceLine,' "bad": @');});
 check('Astral and U+2028/U+2029 string data remain UTF-16 characters on their physical line',folder=>{const source='{"note":"😀\u2028\u2029", "bad": @}';const location=failure(folder,source,source.indexOf('@'));assert.equal(location.line,1);assert.equal(location.column,source.indexOf('@')+1);});
 check('Unterminated block comments link to the original opening slash',folder=>{const source='\uFEFF{\r\n /* 😀 never closed';const location=failure(folder,source,source.indexOf('/*'));assert.equal(location.line,2);assert.equal(location.column,2);});
 check('Unterminated strings and containers report the captured EOF',folder=>{for(const source of ['{"value":"unfinished','{"value":[1,2','{"compilerOptions":{']){const location=failure(folder,source,source.length);assert.equal(location.column,source.length+1);}});
 check('Invalid string escapes and control characters report the offending original unit',folder=>{for(const [source,offset] of [['{"v":"\\q"}',7],['{"v":"\\u00x0"}',10],['{"v":"a\tb"}',7],['{"v":"a\nb"}',7]])failure(folder,source,offset);});
 check('Invalid numbers and literals retain the first unexpected original token',folder=>{for(const [source,token] of [['{"v":01}','1'],['{"v":1.}','}'],['{"v":1e+}','}'],['{"v":truX}','X'],['{"v":nulp}','p'],['{"v":-}','}']])failure(folder,source,source.indexOf(token,5));});
 check('Missing colons, values, commas and trailing top-level tokens retain exact positions',folder=>{for(const [source,token] of [['{"v" 1}','1'],['{"v":}','}'],['[1 2]','2'],['{} false','f'],['{"a":1,,}',' ,']]){const offset=token===' ,'?source.indexOf(',,')+1:source.indexOf(token);failure(folder,source,offset);}});
 check('Trailing-comma cleaning cannot turn empty array slots or missing values into valid JSON',folder=>{for(const source of ['{"compilerOptions":{"paths":{"@x":[,]}}}','{"compilerOptions":,}','{"v":[1,,]}'])failure(folder,source,source.includes(',,')?source.indexOf(',,')+1:source.indexOf(','));});
 check('Non-JSON whitespace is rejected instead of silently changing JSON value semantics',folder=>{const source='{"v":\u00a042}';failure(folder,source,source.indexOf('\u00a0'));});
 check('Deep malformed input stays iterative and within the 64 KiB source budget',folder=>{const source='['.repeat(20000)+'@'+']'.repeat(20000);const location=failure(folder,source,20000);assert.equal(location.column,20001);});
 check('Invalid compilerOptions links to its actual value rather than file start',folder=>{const source='{\n "note":"😀",\n "compilerOptions": false\n}';const location=failure(folder,source,source.indexOf('false'));assert.equal(location.line,3);});
 check('Duplicate semantic keys follow native JSON last-value semantics',folder=>{const source='{"compilerOptions":{"baseUrl":"."}, "compilerOptions":{"baseUrl":42}}';failure(folder,source,source.indexOf('42'));});
 check('Invalid paths and alias-array values identify the declaring config value',folder=>{for(const [source,token] of [['{"compilerOptions":{"paths":false}}','false'],['{"compilerOptions":{"paths":{"@bad":["good",42]}}}','42']])failure(folder,source,source.indexOf(token));});
 check('Invalid extends array entries identify the exact failing element',folder=>{const source='{"extends":[42]}';failure(folder,source,source.indexOf('42'));});
 check('Missing and escaping extends link to the current declaring config',folder=>{for(const source of ['{"extends":"./missing.json"}','{"extends":"../outside.json"}'])failure(folder,source,source.indexOf('"./')>=0?source.indexOf('"./'):source.indexOf('"../'));});
 check('Malformed inherited config links to the inherited captured source',folder=>{write(folder,'tsconfig.json','{"extends":"./base.json"}');const source='\uFEFF{\r\n "compilerOptions": @\r\n}',file=write(folder,'base.json',source);assert.throws(()=>compiler.create({root:folder}).forFile(path.join(folder,'main.ts')),error=>error.location?.path===file&&error.location.offset===source.indexOf('@')&&error.location.source===source&&error.location.line===2);});
 check('Package compiler manifests retain strict JSON syntax and original BOM offsets',folder=>{write(folder,'tsconfig.json','{"extends":"fixture-config"}');const source='\uFEFF{"name":"fixture-config",/* forbidden */"tsconfig":"base.json"}',file=write(folder,'node_modules/fixture-config/package.json',source);write(folder,'node_modules/fixture-config/base.json','{}');assert.throws(()=>compiler.create({root:folder}).forFile(path.join(folder,'main.ts')),error=>error.location?.path===file&&error.location.offset===source.indexOf('/*')&&error.location.source===source);});
 check('Circular extends identifies the reference that closes the cycle',folder=>{write(folder,'tsconfig.json','{"extends":"./base.json"}');const source='{\n "extends": "./tsconfig.json"\n}',file=write(folder,'base.json',source);assert.throws(()=>compiler.create({root:folder}).forFile(path.join(folder,'main.ts')),error=>/Circular/.test(error.message)&&error.location?.path===file&&error.location.offset===source.indexOf('"./'));});
 check('Unsaved config rejection retains only the saved captured source',folder=>{const source='\uFEFF{\r\n "compilerOptions":{}\r\n}',file=write(folder,'tsconfig.json',source);assert.throws(()=>compiler.create({root:folder,buffers:new Map([[file.toLowerCase(),'{}']])}).forFile(path.join(folder,'main.ts')),error=>/Save compiler configuration/.test(error.message)&&error.location?.source===source&&error.location.sha256===hash(source)&&error.location.offset===0&&error.location.line===1&&error.location.column===1);});
 check('Opening a lone-CR config with normalized editor lines does not invent unsaved changes',folder=>{const source='{\r "compilerOptions":{}\r}',file=write(folder,'tsconfig.json',source),config=compiler.create({root:folder,buffers:new Map([[file.toLowerCase(),source.replace(/\r/g,'\n')]])});assert.deepEqual(config.forFile(path.join(folder,'main.ts')).raw.compilerOptions,{});assert.equal(config.finish().metadata.find(item=>item.path===file).source,source);});
 check('Parent validation reconstructs coordinates and name without trusting child fields',folder=>{const source='\uFEFF{\r\n "bad": @\r\n}',file=path.join(folder,'tsconfig.json'),raw={kind:'compiler-configuration',path:file,source,sha256:hash(source),offset:source.indexOf('@'),line:900,column:800,name:'forged',sourceLine:'wrong'},location=compiler.validateLocation(raw,{root:folder});assert.equal(location.line,2);assert.equal(location.column,9);assert.equal(location.name,'tsconfig.json');assert.equal(location.sourceLine,' "bad": @');});
 check('Outside paths, invalid hashes, oversized sources and invalid offsets cannot create links',folder=>{const source='{}',raw={kind:'compiler-configuration',path:path.join(folder,'tsconfig.json'),source,sha256:hash(source),offset:0};for(const changes of [{path:path.join(folder,'../outside.json')},{sha256:'f'.repeat(64)},{offset:-1},{offset:3},{offset:0.5},{source:'x'.repeat(65537),sha256:hash('x'.repeat(65537))},{kind:'source'},{path:'tsconfig.json'}])assert.equal(compiler.validateLocation({...raw,...changes},{root:folder}),null);assert.equal(compiler.validateLocation(raw,{root:folder,checked:()=>{throw Error('junction escape');}}),null);});
 check('Captured locations survive saved file changes for accurate changed-source notices',folder=>{const source='{"bad":@}',file=write(folder,'tsconfig.json',source),raw=compiler.diagnosticLocation({path:file,source},source.indexOf('@'));fs.writeFileSync(file,'{}');assert.equal(compiler.validateLocation(raw,{root:folder}).source,source);});
 check('Changed-during-compilation failure links to the original positive config snapshot',folder=>{const source='\uFEFF{\r\n "compilerOptions":{}\r\n}',file=write(folder,'tsconfig.json',source),config=compiler.create({root:folder});config.forFile(path.join(folder,'main.ts'));fs.writeFileSync(file,'{}');assert.throws(()=>config.finish(),error=>/changed during compilation/.test(error.message)&&error.location?.path===file&&error.location.source===source&&error.location.sha256===hash(source));});
 check('Nested esbuild details and causes retain config locations without cycles or unbounded traversal',folder=>{const location=compiler.diagnosticLocation({path:path.join(folder,'tsconfig.json'),source:'{}'},0),cause=Error('config');cause.location=location;const wrapped={errors:[{location:{file:'main.ts',line:1},detail:{cause}}]};wrapped.cause=wrapped;assert.equal(compiler.fromError(wrapped),location);assert.equal(compiler.fromError({errors:[{location:{kind:'source'}}]}),null);let chain={location};for(let i=0;i<40;i++)chain={cause:chain};assert.equal(compiler.fromError(chain),null);});
 check('Saved UTF-8 file-byte limits remain enforced before producing oversized source diagnostics',folder=>{write(folder,'tsconfig.json','{"note":"'+'😀'.repeat(17000)+'"}');assert.throws(()=>compiler.create({root:folder}).forFile(path.join(folder,'main.ts')),/64 KiB/);assert.equal(compiler.limits.fileBytes,65536);assert.equal(compiler.limits.files,128);assert.equal(compiler.limits.totalBytes,1048576);assert.equal(compiler.limits.depth,32);});
 check('Valid inherited JSONC still resolves aliases and retains unchanged captured metadata',folder=>{const base=write(folder,'config/base.json','\uFEFF{ // 😀\r\n "compilerOptions":{"baseUrl":"../src","paths":{"@value":["value.ts",],},},}');write(folder,'tsconfig.json','{"extends":"./config/base.json"}');const config=compiler.create({root:folder}),loaded=config.forFile(path.join(folder,'main.ts'));assert.equal(loaded.raw.compilerOptions.baseUrl,path.join(folder,'src'));assert.deepEqual(loaded.raw.compilerOptions.paths['@value'],[path.join(folder,'src/value.ts')]);const metadata=config.finish().metadata;assert.equal(metadata.find(item=>item.path===base).sha256,hash(fs.readFileSync(base,'utf8')));});
 result={passed:true,checks,root};
}catch(error){result={passed:false,checks,root,error:error.stack};console.error(error);}
fs.writeFileSync(path.join(runtime,'config-parser-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));process.exitCode=result.passed?0:1;
