'use strict';
process.env.LT_REVIVAL_TEST='1';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const policy=require('../../deploy/core/proof-policy.cjs'),projects=require('../../deploy/core/revival-projects.cjs'),node=require('../../deploy/core/revival-node.cjs'),context=require('../../deploy/core/revival-node-context.cjs'),memory=require('../../deploy/core/proof-memory.cjs'),compilerConfig=require('../../deploy/core/revival-compiler-config.cjs'),modules=require('../../deploy/core/proof-modules.cjs');
const root=path.join(policy.root,'config-node-tests',crypto.randomUUID()),receipt=path.join(policy.root,'config-node-result.json'),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null,checks=[];
const hash=source=>crypto.createHash('sha256').update(source).digest('hex');
function write(folder,name,source){const file=path.join(folder,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,source);return file;}
async function check(name,fn){const folder=path.join(root,String(checks.length+1));write(folder,'package.json','{"name":"config-node-fixture","private":true}');projects.activate(folder);try{await fn(folder);checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
function point(source,offset){let line=1,start=0;for(let index=0;index<offset;index++){if(source[index]==='\r'){line++;if(source[index+1]==='\n')index++;start=index+1;}else if(source[index]==='\n'){line++;start=index+1;}}let end=start;while(end<source.length&&!/[\r\n]/.test(source[end]))end++;return {line,column:offset-start+1,sourceLine:source.slice(start,end)};}
function exact(error,file,source,offset){const location=error.location;assert(location,error.stack);assert.equal(location.kind,'compiler-configuration');assert.equal(location.path,file);assert.equal(location.source,source);assert.equal(location.sha256,hash(source));assert.equal(location.offset,offset);assert.deepEqual({line:location.line,column:location.column,sourceLine:location.sourceLine},point(source,offset));assert(error.message.includes(location.name+':'+location.line+':'+location.column+' - '));return true;}
const run=(file,source,options={})=>node.run(119,{path:file,source,...options});
function clean(){const recent=node.diagnostics().recent.at(-1);assert.equal(recent.memory.limitBytes,1024*1024*1024);assert.equal(recent.memory.hardPrivateCommit,true);assert.equal(recent.memory.processExited,true);assert.equal(recent.memory.contextFilesRemoved,true);assert.equal(node.activeCount(),0);assert.equal(memory.status().jobs,0);}
async function rejects(file,source,configuration,offset,options={}){await assert.rejects(()=>run(file,source,options),error=>exact(error,configuration.path,configuration.source,offset));clean();}
function broken(folder,name='tsconfig.json',source='{\r\n  "compilerOptions": {"baseUrl": false}\r\n}') {return {path:write(folder,name,source),source};}
const workerRun=(name,handled=false,wrapped=false,explicit=false)=>'const {Worker}=require("node:worker_threads");new Promise((resolve,reject)=>{const worker=new Worker('+JSON.stringify(name)+(explicit?',{execArgv:[]}':'')+');const before=worker.listenerCount("error");worker.once("error",error=>'+(handled?'resolve({answer:42,before,message:error.message})':wrapped?'reject(new Error("forwarded worker configuration",{cause:error}))':'reject(error)')+');worker.once("message",resolve);});';
let result;
(async()=>{try{
 await check('Primary typed JSON syntax failures link exact saved CRLF configuration bytes before code runs',async folder=>{const source='// 😀 config\r\n{\r\n  "compilerOptions": {"target": ?}\r\n}',config=broken(folder,'tsconfig.json',source),code='require("node:fs").writeFileSync("should-not-run.txt","bad");const value:number=42;value;',file=write(folder,'main.cts',code);await rejects(file,code,config,source.indexOf('?'));assert.equal(fs.existsSync(path.join(folder,'should-not-run.txt')),false);});
 await check('Semantic configuration errors retain raw UTF16 columns after an emoji on the same line',async folder=>{const source='{"note":"😀", "compilerOptions":{"baseUrl": 42}}',config=broken(folder,'tsconfig.json',source),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,source.indexOf('42'));});
 await check('Inherited configuration errors retain the inherited path and physical lone-CR lines',async folder=>{write(folder,'tsconfig.json','{"extends":"./base.json"}');const config=broken(folder,'base.json','// 😀 inherited\r{\r "compilerOptions": []\r}'),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,config.source.indexOf('[]'));});
 await check('Missing extends links the authored extends value rather than a nonexistent target',async folder=>{const config=broken(folder,'tsconfig.json','{\r\n "extends": "./missing-config",\r\n "compilerOptions": {}\r\n}'),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,config.source.indexOf('"./missing-config"'));});
 await check('Invalid inherited paths link the actual alias element in its declaring file',async folder=>{write(folder,'tsconfig.json','{"extends":"./base.json"}');const config=broken(folder,'base.json','{"compilerOptions":{"paths":{"@answer":["./first", false]}}}'),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,config.source.indexOf('false'));});
 await check('Package configuration extends preserves strict package-manifest syntax coordinates',async folder=>{write(folder,'tsconfig.json','{"extends":"config-kit"}');const config=broken(folder,'node_modules/config-kit/package.json','{\r\n "note":"😀",\r\n "tsconfig": ?\r\n}'),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,config.source.indexOf('?'));});
 await check('Normalized editor buffers for a lone-CR config package preserve native execution and raw metadata',async folder=>{write(folder,'tsconfig.json','{"extends":"config-kit"}');const manifestSource='{\r "name":"config-kit",\r "main":"index.cjs",\r "tsconfig":"base.json"\r}',manifest=write(folder,'node_modules/config-kit/package.json',manifestSource),normalized=manifestSource.replace(/\r/g,'\n'),options={buffers:[{path:manifest,source:normalized}]};write(folder,'node_modules/config-kit/base.json','{"compilerOptions":{"jsx":"preserve","jsxFactory":"h"}}');write(folder,'node_modules/config-kit/index.cjs','module.exports=42;');const code='const h=(tag:string,props:any)=>props;module.exports=<output answer={require("config-kit")}/>;',file=write(folder,'main.tsx',code),output=await run(file,code,options);assert.equal(output.result,'{"answer":42}');const captured=output.project.metadata.find(item=>item.path===manifest);assert.equal(captured.source,manifestSource);assert.equal(captured.sha256,hash(manifestSource));assert.equal(fs.readFileSync(manifest,'utf8'),manifestSource);assert.equal(output.memory.limitBytes,1024*1024*1024);assert.equal(output.memory.contextFilesRemoved,true);const isolated=await modules.prepare(code,{path:file,...options});assert.equal(isolated.project.metadata.find(item=>item.path===manifest).source,manifestSource);assert(isolated.project.modules.some(item=>item.path.endsWith(path.join('config-kit','index.cjs'))));modules.stop();});
 await check('Unsaved configuration rejection links saved source rather than the unsaved buffer',async folder=>{const config=broken(folder,'tsconfig.json','{"compilerOptions":{}}'),code='const answer:number=42;answer;';await rejects(write(folder,'main.cts',code),code,config,0,{buffers:[{path:config.path,source:'{"compilerOptions":{"target":"es2020"}}'}]});assert.equal(fs.readFileSync(config.path,'utf8'),config.source);});
 await check('Imported typed modules select their nearest configuration for diagnostics',async folder=>{write(folder,'tsconfig.json','{"compilerOptions":{}}');const config=broken(folder,'nested/tsconfig.json'),dependency=write(folder,'nested/value.cts','module.exports=42 as number;'),code='require("./nested/value.cts");';await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));assert(fs.existsSync(dependency));});
 await check('Captured config diagnostic survives a later saved-file change before the parent receives it',async folder=>{const config=broken(folder,'nested/tsconfig.json'),code='try{require("./nested/value.cts")}catch(error){require("node:fs").writeFileSync('+JSON.stringify(config.path)+',"{}");throw error;}';write(folder,'nested/value.cts','module.exports=42 as number;');await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));assert.equal(fs.readFileSync(config.path,'utf8'),'{}');});
 await check('Native Worker rejection carries exact config source even with explicit empty native flags',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code=workerRun('./nested/worker.cts',false,false,true);await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));});
 await check('A near-64 KiB control-character worker config retains its original error and exact source link',async folder=>{const source='{"padding":"'+'\0'.repeat(64*1024-64)+'","compilerOptions":{}}',config=broken(folder,'nested/tsconfig.json',source);assert(Buffer.byteLength(source)>65000&&Buffer.byteLength(source)<=65536);write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code=workerRun('./nested/worker.cts');await assert.rejects(()=>run(write(folder,'main.cjs',code),code),error=>{assert.match(error.message,/Invalid compiler configuration/);assert.doesNotMatch(error.message,/diagnostic exceeds|report budget/);return exact(error,config.path,source,source.indexOf('\0'));});clean();});
 await check('Handled worker config errors preserve native events and successful parent results',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code=workerRun('./nested/worker.cts',true),output=await run(write(folder,'main.cjs',code),code),value=JSON.parse(output.result);assert.equal(value.answer,42);assert.equal(value.before,0);assert.match(value.message,/baseUrl/);assert.equal(output.memory.limitBytes,1024*1024*1024);assert.equal(output.memory.contextFilesRemoved,true);assert.equal(output.memory.processExited,true);assert.equal(fs.readFileSync(config.path,'utf8'),config.source);});
 await check('Unhandled native Worker error remains fatal and links its config without an added error handler',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code='new (require("node:worker_threads").Worker)("./nested/worker.cts");new Promise(()=>{});';await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));});
 await check('A parent rethrow with native cause retains the original worker configuration location',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code=workerRun('./nested/worker.cts',false,true);await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));});
 await check('A nested worker rethrow preserves configuration location across both real thread boundaries',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/bad.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');write(folder,'parent-worker.cjs','const {Worker,parentPort}=require("node:worker_threads");const worker=new Worker("./nested/bad.cts",{execArgv:[]});worker.once("error",error=>{throw new Error("nested worker configuration",{cause:error})});worker.once("message",value=>parentPort.postMessage(value));');const code=workerRun('./parent-worker.cjs');await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));});
 await check('Nested worker native uncaught handlers and capture callbacks retain handled success',async folder=>{broken(folder,'nested/tsconfig.json');write(folder,'nested/bad.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');for(const mode of ['handler','capture']){const callback='error=>parentPort.postMessage({answer:42,message:error.message,flags:process.execArgv})',setup=mode==='handler'?'process.on("uncaughtException",'+callback+')':'process.setUncaughtExceptionCaptureCallback('+callback+')';write(folder,'parent-worker.cjs','const {Worker,parentPort}=require("node:worker_threads");'+setup+';const worker=new Worker("./nested/bad.cts");worker.once("error",error=>{throw new Error("handled nested configuration",{cause:error})});');const code=workerRun('./parent-worker.cjs'),output=await run(write(folder,'main.cjs',code),code),value=JSON.parse(output.result);assert.equal(value.answer,42);assert.equal(value.message,'handled nested configuration');assert.deepEqual(value.flags,[]);assert.equal(output.memory.contextFilesRemoved,true);assert.equal(output.memory.processExited,true);assert.equal(output.memory.limitBytes,1024*1024*1024);}});
 await check('Fork failure forwarded through native stderr links the child configuration',async folder=>{const config=broken(folder,'nested/tsconfig.json');write(folder,'nested/child.cts','module.exports=42 as number;');const code='new Promise((resolve,reject)=>{const child=require("node:child_process").fork("./nested/child.cts",[],{silent:true});let stderr="";child.stderr.on("data",chunk=>stderr+=chunk);child.once("error",reject);child.once("close",code=>code?reject(new Error("fork failed\\n"+stderr)):resolve(42));});';await rejects(write(folder,'main.cjs',code),code,config,config.source.indexOf('false'));});
 await check('A handled fork configuration failure does not replace a successful parent result',async folder=>{broken(folder,'nested/tsconfig.json');write(folder,'nested/child.cts','module.exports=42 as number;');const code='new Promise((resolve,reject)=>{const child=require("node:child_process").fork("./nested/child.cts");child.once("error",reject);child.once("close",code=>resolve(code===1?42:0));});',output=await run(write(folder,'main.cjs',code),code);assert.equal(output.result,'42');assert.equal(output.memory.contextFilesRemoved,true);assert.equal(output.memory.processExited,true);});
 await check('An earlier handled worker diagnostic cannot relabel an unrelated later parent error',async folder=>{broken(folder,'nested/tsconfig.json');write(folder,'nested/worker.cts','require("node:worker_threads").parentPort.postMessage(42 as number);');const code=workerRun('./nested/worker.cts',true).replace('});','}).then(()=>{throw new Error("unrelated parent failure")});'),file=write(folder,'main.cjs',code);await assert.rejects(()=>run(file,code),error=>{assert.match(error.message,/unrelated parent failure/);assert.equal(error.location.path,file);assert.notEqual(error.location.kind,'compiler-configuration');return true;});clean();});
 await check('Handled fork stderr cannot relabel an unrelated later parent failure',async folder=>{broken(folder,'nested/tsconfig.json');write(folder,'nested/child.cts','module.exports=42 as number;');const code='new Promise((resolve,reject)=>{const child=require("node:child_process").fork("./nested/child.cts");child.once("error",reject);child.once("close",()=>resolve(42));}).then(()=>{throw new Error("unrelated after handled fork")});',file=write(folder,'main.cjs',code);await assert.rejects(()=>run(file,code),error=>{assert.match(error.message,/unrelated after handled fork/);assert.equal(error.location.path,file);assert.notEqual(error.location.kind,'compiler-configuration');return true;});clean();});
 await check('Stop after a handled fork config failure retains cancellation without an old config link',async folder=>{broken(folder,'nested/tsconfig.json');write(folder,'nested/child.cts','module.exports=42 as number;');const code='new Promise((resolve,reject)=>{const child=require("node:child_process").fork("./nested/child.cts");child.once("error",reject);child.once("close",()=>setTimeout(()=>console.log("handled-fork-ready"),50));});',file=write(folder,'main.cjs',code);let ready,timer;const started=new Promise(resolve=>ready=resolve),task=node.run(119,{path:file,source:code},event=>{if(event.stream==='stdout'&&event.text.includes('handled-fork-ready'))ready();}).then(result=>({result}),error=>({error}));try{await Promise.race([started,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Handled fork fixture did not become ready')),10000);})]);await node.cancel(119);const output=await task;assert(output.error);assert.equal(output.error.message,'Execution cancelled');assert.equal(output.error.location,undefined);assert.match(output.error.logs.join('\n'),/Invalid compiler baseUrl/);clean();}finally{clearTimeout(timer);await node.cancel(119);await task;}});
 await check('Parent diagnostic validation reconstructs coordinates and rejects forged envelopes without links',async folder=>{const source='{"note":"😀"}\r\n{"bad":true}',file=write(folder,'tsconfig.json',source),raw=compilerConfig.diagnosticLocation({path:file,source},source.indexOf('true')),prepared={root:folder},valid=node.failure(prepared,'config failed','',[],true,{...raw,name:'invented',line:999,column:999,sourceLine:'invented'});assert.deepEqual({line:valid.location.line,column:valid.location.column,sourceLine:valid.location.sourceLine},point(source,raw.offset));assert.equal(valid.location.name,'tsconfig.json');for(const invalid of [{...raw,kind:'ordinary'},{...raw,sha256:'0'.repeat(64)},{...raw,offset:-1},{...raw,offset:0.5},{...raw,offset:source.length+1},{...raw,path:path.join(root,'outside.json')},{...raw,source:'x'.repeat(65537),sha256:hash('x'.repeat(65537))}])assert.equal(node.failure(prepared,'config failed','',[],true,invalid).location,undefined);});
 await check('Quota rejection still prevents config evaluation and authored code before the private gate opens',async folder=>{const config=broken(folder,'tsconfig.json'),code='require("node:fs").writeFileSync("blocked.txt","bad");42 as number;',file=write(folder,'main.cts',code),attach=memory.attach;memory.attach=async()=>{throw Error('focused quota refusal');};try{await assert.rejects(()=>run(file,code),error=>{assert.match(error.message,/focused quota refusal/);assert.equal(error.location,undefined);return true;});assert.equal(fs.existsSync(path.join(folder,'blocked.txt')),false);assert.equal(fs.readFileSync(config.path,'utf8'),config.source);}finally{memory.attach=attach;}assert.equal(node.activeCount(),0);assert.equal(memory.status().jobs,0);});
 result={passed:true,checks,cleanup:{active:node.activeCount(),jobs:memory.status().jobs}};
 }catch(error){result={passed:false,checks,error:error.stack};process.exitCode=1;}finally{modules.stop();await node.shutdown();await memory.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);fs.mkdirSync(path.dirname(receipt),{recursive:true});fs.writeFileSync(receipt,JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,checks:checks.length,cleanup:result.cleanup,error:result.error}));}})();
