(async()=>{
 const checks=[],check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};
 const kw=cljs.core.keyword,clients=lt.objs.clients,runtime=clients.javascript;
 const command=(name,...args)=>lt.objs.command.exec_BANG_(kw(name),...args);
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 const get=(object,key)=>cljs.core.get(cljs.core.deref(object),kw(key));
 const client=()=>clients.by_name('JavaScript');
 const association=()=>cljs.core.get(get(lt.objs.editor.pool.last_active(),'client'),kw('javascript'));
 command('open-path',ltProof.info.docs+'\\order-report-test.js');const cm=ltProofUI.connect(),baseline=cm.getValue();
 check('Normal Run is registered as an actual JavaScript client',runtime.connected_QMARK_()&&get(client(),'connected')&&cljs.core.contains_QMARK_(get(client(),'commands'),kw('javascript.eval')));
 check('Original client discovery finds JavaScript execution',cljs.core.first(clients.discover(kw('javascript.eval'),cljs.core.PersistentArrayMap.EMPTY)).toString()===':found');
 const first=client();runtime.connect_BANG_();runtime.connect_BANG_();check('Repeated connect reuses one provider',client()===first);
 command('show-connect');await wait(150);
 const sidebar=document.querySelector('#right-bar .clients.active');
 check('Original Connections panel displays the real provider',sidebar?.textContent.includes('JavaScript')&&sidebar.textContent.includes('fresh context per run')&&sidebar.getBoundingClientRect().width>0);
 check('Connections replace Activity without obscuring the editor',getComputedStyle(document.getElementById('proof-calculation')).visibility==='hidden'&&document.getElementById('right-bar').getBoundingClientRect().width===340);
 command('close-sidebar');await wait(150);
 check('Closing Connections restores Activity',getComputedStyle(document.getElementById('proof-calculation')).visibility==='visible');
 const callbackCount=()=>cljs.core.count(cljs.core.deref(clients.callbacks));
 const before=callbackCount();
 const request=(code,data)=>new Promise(resolve=>clients.send(client(),kw(code),cljs.core.js__GT_clj(data,kw('keywordize-keys'),true),true,(reply,value)=>resolve({reply:reply.toString(),value:cljs.core.clj__GT_js(value)})));
 let response=await request('javascript.eval',{source:'Promise.resolve(42)',options:{}});
 check('Client protocol executes promises in the isolated runtime',response.reply===':javascript.result'&&response.value.result==='42'&&response.value.memory.hardPrivateCommit&&response.value.sandbox&&response.value.source==='Promise.resolve(42)');
 response=await request('javascript.eval',{source:'throw new Error("client error")',options:{}});
 check('Client protocol returns an actionable execution error',response.reply===':javascript.error'&&response.value.message.includes('client error'));
 response=await request('unsupported.command',{});
 check('Unsupported commands fail without leaving callbacks',response.reply===':javascript.error'&&response.value.message.includes('Unsupported')&&callbackCount()===before);
 response=await request('javascript.eval',{source:'40+3',options:{}});
 check('Client recovers after an error with no callback leak',response.value.result==='43'&&callbackCount()===before);
 cm.setValue('new Promise(()=>{})');testMenuClick('Run file');const cancelled=ltProofUI.pending();await wait(150);
 testMenuClick('Disconnect JavaScript');await cancelled;await wait(100);
 check('Disconnect cancels active execution and removes the client',!runtime.connected_QMARK_()&&!client()&&document.getElementById('proof-output').dataset.status==='cancelled');
 check('Disconnect clears active-editor associations and callbacks',!association()&&callbackCount()===before);
 check('Native menu permits reconnect after disconnect',testMenuItem('Connect JavaScript').enabled&&!testMenuItem('Disconnect JavaScript').enabled);
 testMenuClick('Connect JavaScript');await wait(50);check('Explicit reconnect creates a fresh usable client',runtime.connected_QMARK_()&&client()!==first&&!testMenuItem('Connect JavaScript').enabled&&testMenuItem('Disconnect JavaScript').enabled);
 testMenuClick('Disconnect JavaScript');await wait(50);cm.setValue('42');testMenuClick('Run file');let run=await ltProofUI.pending();
 check('Normal Run automatically reconnects and restores evaluation',runtime.connected_QMARK_()&&run.accepted&&run.result.result==='42');
 check('Normal Run associates the editor with its runtime',association()===client());
 // The original LightTable-UI connection must use the same execution boundary.
 lt.objs.clients.local.init();const local=clients.by_name('LightTable-UI');
 const localRequest=code=>new Promise(resolve=>clients.send(local,kw('editor.eval.js'),cljs.core.js__GT_clj({code,meta:{line:3}},kw('keywordize-keys'),true),true,(reply,value)=>resolve({reply:reply.toString(),value:cljs.core.clj__GT_js(value)})));
 const localResult=await localRequest('[typeof window,typeof document,typeof require,42]');
 check('Legacy UI JavaScript messages use isolated execution and preserve metadata',localResult.reply===':editor.eval.js.result'&&JSON.stringify(localResult.value.result)==='["undefined","undefined","undefined",42]'&&localResult.value.meta.line===3&&localResult.value.snapshot.memory.hardPrivateCommit);
 const localError=await localRequest('window.document.body.textContent="changed"');
 check('Legacy UI JavaScript cannot modify the editor document',localError.reply===':editor.eval.js.exception'&&localError.value.ex.message.includes('window is not defined')&&localError.value.meta.line===3&&document.getElementById('proof-calculation'));
 const localPromise=await localRequest('Promise.resolve(43)');
 check('Legacy JavaScript protocol awaits promises and recovers',localPromise.reply===':editor.eval.js.result'&&localPromise.value.result===43);
 check('Legacy JavaScript releases its terminal reply callback',callbackCount()===before);
 clients.close_BANG_(local);
 cm.setValue(baseline);cm.focus();command('save');run=await ltProofUI.runJavaScript();check('Full order report still runs after connection cycles',run.accepted&&JSON.parse(run.result.result).revenue===129);
 return {passed:true,checks,clientName:get(client(),'name'),result:run.result};
})()
