'use strict';
const {captureNativePage}=require('./native-page-capture.cjs');
const {app}=require('electron'),fs=require('fs'),path=require('path');
process.env.LT_REVIVAL_TEST='1';
const root=path.resolve(__dirname,'../..','.revival'),phase=process.env.LT_PROOF_PHASE||'evaluation';
const projectParent=path.join(root,'project-ui-tests',require('crypto').randomUUID());
fs.mkdirSync(path.join(projectParent,'existing-project'),{recursive:true});
fs.writeFileSync(path.join(projectParent,'existing-project','index.js'),'17');
// Drive the real native-picker bridge with a deterministic OS selection in this test.
const nativeDialog=require('electron').dialog,originalPicker=nativeDialog.showOpenDialogSync,originalTrustDialog=nativeDialog.showMessageBox;
nativeDialog.showOpenDialogSync=(_window,options)=>options.title==='Choose where to create your project'?[projectParent]:options.title==='Open project folder'?[path.join(projectParent,'existing-project')]:originalPicker(_window,options);
nativeDialog.showMessageBox=async(window,options)=>{
 if(options.title!=='Run local Node project')return originalTrustDialog(window,options);
 const requested=options.detail.split('\n')[0];step('native project trust: '+requested);
 if(!requested.toLowerCase().startsWith((projectParent+path.sep).toLowerCase()))throw Error('Unexpected project trust request in editor fixture: '+requested);
 return {response:1};
};
fs.mkdirSync(path.join(root,'test-proof-files'),{recursive:true});
fs.writeFileSync(path.join(root,'test-proof-files/calculation.js'),'(12 + 30)');
fs.copyFileSync(path.join(__dirname,'../../deploy/core/fixtures/order-report.js'),path.join(root,'test-proof-files/order-report-test.js'));
fs.writeFileSync(path.join(root,'test-proof-files/input-test.css'),'* { color: red; }');
fs.writeFileSync(path.join(root,phase+'-console.log'),'');
let editorWindowSeen=false;
const step=stage=>fs.writeFileSync(path.join(root,phase+'-progress.json'),JSON.stringify({pid:process.pid,stage,time:new Date().toISOString()}));step('waiting for editor window');
app.on('browser-window-created',(_e,win)=>{
if(editorWindowSeen)return;editorWindowSeen=true;win.setOpacity(0);win.setSkipTaskbar(true);win.showInactive();step('waiting for editor load');
win.webContents.on('console-message',(_e,level,message,line,source)=>fs.appendFileSync(path.join(root,phase+'-console.log'),JSON.stringify({level,message,line,source})+'\n'));
win.webContents.on('did-finish-load',()=>setTimeout(async()=>{
const capture=async name=>{await win.webContents.executeJavaScript('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');await new Promise(resolve=>setTimeout(resolve,80));fs.writeFileSync(path.join(root,name),(await captureNativePage(win.webContents)).toPNG());};step('starting original editor checks');
const focusInput=async()=>{win.focus();win.webContents.focus();const end=Date.now()+2000;while(!win.isFocused()||!win.webContents.isFocused()){if(Date.now()>=end)throw Error('Native editor input focus unavailable: '+JSON.stringify({window:win.isFocused(),contents:win.webContents.isFocused(),visible:win.isVisible()}));await new Promise(resolve=>setTimeout(resolve,20));}};
const nativeItem=label=>{const find=menu=>{for(const item of menu.items){if(item.label.replace('&','')===label)return item;if(item.submenu){const match=find(item.submenu);if(match)return match;}}};const item=find(require('electron').Menu.getApplicationMenu());if(!item)throw Error('Missing native menu item: '+label);return item;};
const nativeClick=async label=>{await focusInput();const started=Date.now(),deadline=started+2000;let item;while(!(item=nativeItem(label)).enabled){if(Date.now()>=deadline)throw Error('Disabled native menu item after readiness deadline: '+label);await new Promise(resolve=>setTimeout(resolve,20));}item.click();await new Promise(resolve=>setTimeout(resolve,80));};
let result={};try{
await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'menu-ui.js'),'utf8'));
result.welcome=await win.webContents.executeJavaScript(`({loaded:!!document.getElementById('intro'),visible:getComputedStyle(document.getElementById('wrapper')).opacity,text:document.getElementById('intro')?.innerText})`);
result.panel=await win.webContents.executeJavaScript(`({buttons:document.querySelectorAll('#proof-calculation button').length,selectors:document.querySelectorAll('#proof-calculation select').length})`);
step('opening calculation');await nativeClick('Calculation');
step('evaluating arithmetic');await nativeClick('Evaluate arithmetic');
await win.webContents.executeJavaScript('ltProofUI.pending()');
result.first=await win.webContents.executeJavaScript(`({last:ltProofUI.getLast(),status:document.getElementById('proof-output').dataset.status,editor:ltProofUI.connect().getValue()})`);
fs.writeFileSync(path.join(root,'evaluation-42.png'),(await captureNativePage(win.webContents)).toPNG());
await focusInput();await win.webContents.executeJavaScript(`ltProofUI.connect().focus();ltProofUI.connect().execCommand('selectAll');`);
await win.webContents.insertText('(12 + 31)');
await new Promise(resolve=>setTimeout(resolve,200));
result.afterEdit=await win.webContents.executeJavaScript(`({status:document.getElementById('proof-output').dataset.status,editor:ltProofUI.connect().getValue()})`);
await nativeClick('Save file');await nativeClick('Evaluate arithmetic');
await win.webContents.executeJavaScript('ltProofUI.pending()');
result.second=await win.webContents.executeJavaScript(`({last:ltProofUI.getLast(),status:document.getElementById('proof-output').dataset.status,editor:ltProofUI.connect().getValue(),requireType:typeof require,actualNodeProcess:typeof process?.versions,hasLegacyRemote:typeof ltRequire('electron').remote.require})`);
result.disk=fs.readFileSync(path.join(require('../../deploy/core/proof-policy.cjs').docs,'calculation.js'),'utf8');
result.runtime={electron:process.versions.electron,chrome:process.versions.chrome};result.settings=win.webContents.getLastWebPreferences(); result.settings.preload='deploy/core/proof-preload.cjs';
result.passed=result.runtime.electron==='44.5.1'&&result.first.last.result===42&&result.second.last.result===43&&result.first.last.sha256!==result.second.last.sha256&&result.afterEdit.status==='stale'&&result.disk.replace(/\r\n/g,'\n')===result.second.editor&&result.settings.contextIsolation===true&&result.settings.nodeIntegration===false&&result.settings.sandbox===true&&result.settings.enableRemoteModule!==true;
if(!result.passed)throw Error('Original arithmetic/editor/source-hash verification failed');
step('capturing arithmetic');await capture('evaluation-43.png');
result.edgecases=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'ui-edgecases.js'),'utf8'));result.passed=result.passed&&result.edgecases.passed;
await win.webContents.executeJavaScript('window.testEditorPID='+win.webContents.getOSProcessId());
step('JavaScript checks');result.javascript=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'javascript-ui.js'),'utf8'));result.passed=result.passed&&result.javascript.passed;
await capture('javascript-43.png');
step('async checks');result.async=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'async-ui.js'),'utf8'));result.passed=result.passed&&result.async.passed;
await capture('async-43.png');
step('workflow checks');result.workflow=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'workflow-ui.js'),'utf8'));result.passed=result.passed&&result.workflow.passed;
await capture('order-report.png');
const nativeMenu=require('electron').Menu.getApplicationMenu();
result.menus={labels:nativeMenu?.items.map(item=>item.label),fileItems:nativeMenu?.items.find(item=>item.label.replace('&','')==='File')?.submenu.items.map(item=>item.label)};
result.passed=result.passed&&result.welcome.loaded&&result.welcome.visible==='1'&&result.menus.labels.includes('&File')&&result.menus.labels.includes('&Run')&&result.menus.fileItems.includes('Save file')&&result.menus.fileItems.includes('Recent projects')&&result.panel.buttons===0&&result.panel.selectors===0;
await focusInput();await win.webContents.executeJavaScript(`ltProofUI.connect().setValue('40+4');ltProofUI.connect().focus();`);
win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return',modifiers:['control','shift']});
win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return',modifiers:['control','shift']});
await new Promise(resolve=>setTimeout(resolve,100));
result.keyboard=await win.webContents.executeJavaScript(`ltProofUI.pending().then(run=>({accepted:run.accepted,source:run.result?.source,result:run.result?.result}))`);
result.passed=result.passed&&result.keyboard.accepted&&result.keyboard.source==='40+4'&&result.keyboard.result==='44';
nativeItem('Save file').click();
await new Promise(resolve=>setTimeout(resolve,100));
result.menuSave=fs.readFileSync(path.join(root,'test-proof-files/order-report-test.js'),'utf8').trim()==='40+4';result.passed=result.passed&&result.menuSave;
const menuChecks=[];const menuCheck=(name,ok)=>{if(!ok)throw Error(name);menuChecks.push(name);};
// Native menu updates follow the renderer's debounced menu bridge. Observe
// completion instead of assuming the last 100 ms sleep delivered that update.
const idleMenuStarted=Date.now(),idleMenuDeadline=idleMenuStarted+2000;
result.idleMenu={initialNativeEnabled:nativeItem('Stop').enabled,initialRenderer:await win.webContents.executeJavaScript('({running:ltProofUI.isRunning(),stopEnabled:testMenuItem("Stop").enabled})')};
do{result.idleMenu.rendererRunning=await win.webContents.executeJavaScript('ltProofUI.isRunning()');result.idleMenu.nativeEnabled=nativeItem('Stop').enabled;if(!result.idleMenu.rendererRunning&&!result.idleMenu.nativeEnabled||Date.now()>=idleMenuDeadline)break;await new Promise(resolve=>setTimeout(resolve,20));}while(true);
result.idleMenu.waitMs=Date.now()-idleMenuStarted;
menuCheck('Stop is disabled while idle',!result.idleMenu.rendererRunning&&!result.idleMenu.nativeEnabled);
menuCheck('Run menu displays the existing keyboard shortcuts',/^(Control|CommandOrControl)\+Shift\+[Ee]nter$/.test(nativeItem('Run file').accelerator)&&/^(Control|CommandOrControl)\+[Ee]nter$/.test(nativeItem('Run selection / line').accelerator));
await win.webContents.executeJavaScript(`ltProofUI.connect().setValue('20+22');`);
await nativeClick('Run file');
const menuRun=await win.webContents.executeJavaScript('ltProofUI.pending()');
menuCheck('Native Run dispatches to the original editor',menuRun.accepted&&menuRun.result.source==='20+22'&&menuRun.result.result==='42');
await nativeClick('Clear results');
menuCheck('Native Clear removes both inspector and inline output',await win.webContents.executeJavaScript(`document.getElementById('proof-output').dataset.status==='idle'&&!ltProofUI.connect().getWrapperElement().querySelector('.revival-inline-result')`));
await win.webContents.executeJavaScript(`const cm=ltProofUI.connect();cm.setValue('const ignored=9;\\n21*2');cm.setSelection({line:1,ch:0},{line:1,ch:4});`);
await nativeClick('Run selection / line');
const menuSelection=await win.webContents.executeJavaScript('ltProofUI.pending()');
menuCheck('Native selection command runs only selected code',menuSelection.accepted&&menuSelection.result.source==='21*2'&&menuSelection.result.scope==='selection'&&menuSelection.result.result==='42');
await win.webContents.executeJavaScript(`ltProofUI.connect().setValue('new Promise(()=>{})');`);
await nativeClick('Run file');
menuCheck('Native Stop becomes enabled during execution',nativeItem('Stop').enabled);
await nativeClick('Stop');
await win.webContents.executeJavaScript('ltProofUI.pending()');
menuCheck('Native Stop cancels execution and becomes disabled',!nativeItem('Stop').enabled&&await win.webContents.executeJavaScript(`document.getElementById('proof-output').dataset.status==='cancelled'`));
result.menuActions={passed:true,checks:menuChecks};
await win.webContents.executeJavaScript(`ltProofUI.connect().setValue(${JSON.stringify(fs.readFileSync(path.join(__dirname,'../../deploy/core/fixtures/order-report.js'),'utf8'))});testMenuClick('Save file');ltProofUI.runJavaScript();`);
await win.webContents.executeJavaScript('ltProofUI.pending()');
result.connections=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'connection-ui.js'),'utf8'));result.passed=result.passed&&result.connections.passed;
result.cleanup={active:require('../../deploy/core/proof-js.cjs').activeCount(),windows:require('electron').BrowserWindow.getAllWindows().length};result.passed=result.passed&&result.cleanup.active===0&&result.cleanup.windows===1;
result.quota=require('../../deploy/core/proof-js.cjs').diagnostics();result.passed=result.passed&&result.quota.jobs===0&&result.quota.pending===0;
// Reproduce historical input sequences through actual Chromium key input.
const key=async code=>{await focusInput();win.webContents.sendInputEvent({type:'keyDown',keyCode:code});win.webContents.sendInputEvent({type:'keyUp',keyCode:code});await new Promise(resolve=>setTimeout(resolve,80));};
await win.webContents.executeJavaScript(`window.inputCM=ltProofUI.connect();inputCM.setValue('function sum() {');inputCM.setCursor({line:0,ch:16});inputCM.focus();`);
await key('Return');
result.input={jsIndent:await win.webContents.executeJavaScript('inputCM.getLine(1)')};
await key('Tab');result.input.jsTab=await win.webContents.executeJavaScript('inputCM.getLine(1)');
await win.webContents.executeJavaScript(`inputCM.setValue('function sum() {\\n  return 42;\\n}');inputCM.setCursor({line:2,ch:1});inputCM.focus();`);
await key('Return');result.input.jsAfterBrace=await win.webContents.executeJavaScript('inputCM.getLine(3)');
await win.webContents.executeJavaScript(`lt.objs.command.exec_BANG_(cljs.core.keyword('open-path'),ltProof.info.docs+'\\\\input-test.css');window.cssCM=ltProofUI.connect();cssCM.setValue('* {\\n  color: red;\\n}');cssCM.setCursor({line:2,ch:1});cssCM.focus();`);
await key('Return');result.input.cssAfterBrace=await win.webContents.executeJavaScript('cssCM.getLine(3)');
await win.webContents.executeJavaScript(`lt.objs.command.exec_BANG_(cljs.core.keyword('version'));lt.objs.command.exec_BANG_(cljs.core.keyword('open-path'),ltProof.info.docs+'\\\\order-report-test.js');inputCM=ltProofUI.connect();inputCM.setValue('a\\nb');inputCM.setCursor({line:0,ch:1});inputCM.focus();`);
await new Promise(resolve=>setTimeout(resolve,100));
result.input.visibleCursors=await win.webContents.executeJavaScript(`[...document.querySelectorAll('.CodeMirror-cursor')].filter(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.height>0&&r.width>0&&s.visibility==='visible'&&s.display!=='none'}).length`);
await focusInput();await win.webContents.executeJavaScript(`inputCM.setSelections([{anchor:{line:0,ch:0},head:{line:0,ch:0}},{anchor:{line:1,ch:0},head:{line:1,ch:0}}]);inputCM.focus();`);
result.input.beforeMultiCursor=await win.webContents.executeJavaScript(`({focused:inputCM.hasFocus(),selections:inputCM.listSelections().length,activeElement:document.activeElement.tagName})`);
result.input.nativeFocus={window:win.isFocused(),contents:win.webContents.isFocused(),visible:win.isVisible()};
await win.webContents.insertText('x');
// Native insertion reaches CodeMirror through its asynchronous textarea poll.
// Observe that real edit; do not resend input or replace the editor buffer.
const multiCursorStarted=Date.now(),multiCursorDeadline=multiCursorStarted+3000;
do{result.input.multiCursor=await win.webContents.executeJavaScript('inputCM.getValue()');if(result.input.multiCursor==='xa\nxb'||Date.now()>=multiCursorDeadline)break;await new Promise(resolve=>setTimeout(resolve,25));}while(true);
result.input.multiCursorWaitMs=Date.now()-multiCursorStarted;
result.input.passed=result.input.jsIndent==='  '&&result.input.jsTab==='    '&&result.input.jsAfterBrace===''&&result.input.cssAfterBrace===''&&result.input.visibleCursors<=1&&result.input.multiCursor==='xa\nxb';result.passed=result.passed&&result.input.passed;
if(!result.input.passed)throw Error('Native editor input did not match: '+JSON.stringify(result.input));
fs.writeFileSync(path.join(root,'input-check.png'),(await captureNativePage(win.webContents)).toPNG());
await win.webContents.executeJavaScript('window.testProjectParent='+JSON.stringify(projectParent));
step('project checks');result.projects=await win.webContents.executeJavaScript(fs.readFileSync(path.join(__dirname,'project-ui.js'),'utf8'));result.passed=result.passed&&result.projects.passed;
result.passed=result.passed&&result.menus.fileItems.includes('New project...')&&result.menus.fileItems.includes('Open project...')&&result.menus.fileItems.includes('New file in project...');
await capture('project-43.png');
}catch(e){result.passed=false;result.error=e.message;result.stack=e.stack;result.failureDiagnostics=require('../../deploy/core/proof-js.cjs').diagnostics();try{result.projectDiagnostics=await win.webContents.executeJavaScript(`({info:ltProjects.info(),status:document.getElementById('project-status')?.textContent,form:document.querySelector('.project-form-error')?.textContent})`);await capture('project-failure.png');}catch(_){} }
nativeDialog.showOpenDialogSync=originalPicker;
nativeDialog.showMessageBox=originalTrustDialog;
await require('../../deploy/core/revival-node.cjs').shutdown();
await require('../../deploy/core/revival-npm.cjs').shutdown();
await require('../../deploy/core/proof-js.cjs').shutdown();
result.helperCleanup=require('../../deploy/core/proof-js.cjs').diagnostics();delete result.helperCleanup.recent;
result.passed=result.passed&&result.helperCleanup.jobs===0&&result.helperCleanup.pending===0&&!result.helperCleanup.helperPid;
fs.writeFileSync(path.join(root,phase+'-result.json'),JSON.stringify(result,null,2));step(result.passed?'passed':'failed: '+result.error);app.exit(result.passed?0:1);},3000));});
setTimeout(()=>app.exit(2),90000);
require('../../deploy/core/main.js');
