'use strict';
process.env.LT_REVIVAL_TEST='1';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const core=path.resolve(__dirname,'../../deploy/core'),policy=require(core+'/proof-policy.cjs'),projects=require(core+'/revival-projects.cjs'),network=require(core+'/revival-preview-network.cjs');
const base=path.join(policy.root,'html-viewer-unit'),root=path.join(base,crypto.randomUUID()),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null,checks=[];
fs.mkdirSync(root,{recursive:true});
const check=async(name,fn)=>{await fn();checks.push(name);};
(async()=>{try{
 await check('A unique nested HTML entry is discovered without an open editor or package.json',()=>{fs.mkdirSync(path.join(root,'golf-course-website'));const file=path.join(root,'golf-course-website/index.html');fs.writeFileSync(file,'<h1>Golf</h1>');projects.activate(root);assert.deepEqual(projects.preview(),{root,entry:file});});
 await check('Root HTML takes precedence over nested pages',()=>{const file=path.join(root,'index.html');fs.writeFileSync(file,'Root');assert.equal(projects.preview().entry,file);fs.unlinkSync(file);});
 await check('Multiple nested sites require a file selection rather than starting an arbitrary site',()=>{fs.mkdirSync(path.join(root,'another-site'));fs.writeFileSync(path.join(root,'another-site/index.html'),'Other');assert.equal(projects.preview(),null);fs.unlinkSync(path.join(root,'another-site/index.html'));});
 await check('Dependency, build, hidden and linked folders cannot become automatic HTML entries',()=>{for(const name of ['node_modules','dist','build','coverage','.hidden']){fs.mkdirSync(path.join(root,name));fs.writeFileSync(path.join(root,name,'index.html'),'Ignored');}fs.symlinkSync(path.join(root,'.hidden'),path.join(root,'linked'),'junction');assert.equal(projects.preview().entry,path.join(root,'golf-course-website/index.html'));});
 await check('Vite projects still select the development server rather than raw HTML',()=>{fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({devDependencies:{vite:'8'},scripts:{dev:'vite'}}));fs.writeFileSync(path.join(root,'index.html'),'<div id=root></div>');assert.equal(projects.preview().mode,'server');fs.unlinkSync(path.join(root,'package.json'));fs.unlinkSync(path.join(root,'index.html'));});
 await check('HTTPS CDN scripts remain browser resources while local scripts still compile',async()=>{const file=path.join(root,'golf-course-website/index.html');fs.writeFileSync(file,'<script src="https://cdn.tailwindcss.com"></script><script src="./app.js"></script><h1>Page</h1>');fs.writeFileSync(path.join(path.dirname(file),'app.js'),'document.title="Local script ran";');const page=require(core+'/revival-preview-files.cjs').prepare({path:file},'lt-preview://html-viewer-unit');try{await page.compile();assert.match(page.html,/https:\/\/cdn.tailwindcss.com/);assert(page.snapshot().files.some(f=>f.path.endsWith('app.js')));}finally{await page.close();}});
 await check('Only HTTPS GET/HEAD script, style, image and font assets can use external hosts',()=>{for(const type of ['script','stylesheet','image','font'])assert(network.allowed({url:'https://cdn.example.test/asset',resourceType:type,method:'GET'},'lt-preview://page'));for(const type of ['xhr','webSocket','ping','subFrame','mainFrame','object','media','other'])assert(!network.allowed({url:'https://cdn.example.test/asset',resourceType:type,method:'GET'},'lt-preview://page'));for(const url of ['http://cdn.example.test/a','file:///C:/secret','https://user:pass@cdn.example.test/a','javascript:alert(1)'])assert(!network.allowed({url,resourceType:'script',method:'GET'},'lt-preview://page'));assert(!network.allowed({url:'https://cdn.example.test/a',resourceType:'script',method:'POST'},'lt-preview://page'));});
 await check('Project resource origin checks and Vite loopback websockets remain intact',()=>{assert(network.allowed({url:'lt-preview://page/app.js',resourceType:'script',method:'GET'},'lt-preview://page'));assert(!network.allowed({url:'lt-preview://other/app.js',resourceType:'script',method:'GET'},'lt-preview://page'));assert(network.allowed({url:'ws://127.0.0.1:5173/',resourceType:'webSocket'},'http://127.0.0.1:5173',true));assert(!network.allowed({url:'ws://127.0.0.1:5174/',resourceType:'webSocket'},'http://127.0.0.1:5173',true));assert.match(network.csp,/connect-src 'self'; frame-src 'none'/);});
 await check('Remote asset loading is detected from actual elements rather than ordinary external hyperlinks',()=>{assert(network.hasAssets('<script src=https://cdn.example.test/script.js></script>'));assert(network.hasAssets('<link rel=stylesheet href="https://fonts.example.test/font.css">'));assert(network.hasAssets('<img src="https://images.example.test/image.jpg">'));assert(network.hasAssets('<style>body{background:url("https://images.example.test/image.jpg")}</style>'));assert(!network.hasAssets('<a href="https://example.test/">Link</a>'));assert(!network.hasAssets('<script src="./local.js"></script>'));});
 console.log(JSON.stringify({passed:true,checks},null,2));
 }finally{if(saved)fs.writeFileSync(projects.statePath,saved);else fs.rmSync(projects.statePath,{force:true});assert.equal(path.dirname(fs.realpathSync(root)),fs.realpathSync(base));fs.rmSync(root,{recursive:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
