'use strict';
const assert=require('assert/strict'),{Readable}=require('stream'),path=require('path'),fs=require('fs');
const {parse,install}=require('../../deploy/core/revival-json-stream.cjs'),node=require('../../deploy/core/revival-node.cjs');
const valid=['null','true','false','42','-0','1e999','9007199254740993','1.23456789e-300','"hello 🌐 café"','"\\ud800\\udfff"','[1,2,{},[],null,true,false,"tail"]','{"__proto__":{"polluted":true},"constructor":42,"prototype":"text"}','{"a":1,"a":2,"z":"quote \\" and slash \\\\"}',' \r\n {"value":"tab\\tline\\nreturn\\r", "1":true, "nested":{"a":[1,-42e-3]}} \n','"'+('a\\u0062🌐'.repeat(10000))+'"'];
const invalid=['',' ','[','{','"','true false','[1,]','{"a":1,}','{"a":}','{a:42}','[01]','[-]','[1.]','[NaN]','{"__proto__":true,,"a":1}','"\\q"','"newline\n"','"\\u123x"','[truefalse]','{"a" 42}'];
(async()=>{const checks=[];
 for(const text of valid){const expected=JSON.parse(text),bytes=Buffer.from(text);for(const size of [1,2,3,7,65536]){const chunks=[];for(let offset=0;offset<bytes.length;offset+=size)chunks.push(bytes.subarray(offset,offset+size));assert.deepStrictEqual(await parse(Readable.from(chunks)),expected);}checks.push('JSON value matches JSON.parse across UTF-8 chunk boundaries');}
 for(const text of invalid){assert.throws(()=>JSON.parse(text));await assert.rejects(parse(Readable.from([...Buffer.from(text)].map(byte=>Buffer.from([byte])))));}checks.push('Malformed JSON and multiple roots are rejected');
 assert.equal(Object.prototype.polluted,undefined);checks.push('Prototype keys remain ordinary own JSON properties');
 await assert.rejects(parse(Readable.from([Buffer.from('"abc"')]),2),/size limit/);checks.push('Configured response size remains bounded');
 const cli=node.discover().npm.cli,localRequire=require('module').createRequire(cli),{Response}=localRequire('minipass-fetch');install(cli);const response=new Response(Readable.from([Buffer.from('{"answer":'),Buffer.from('42}')]));assert.deepStrictEqual(await response.json(),{answer:42});assert.equal(response.bodyUsed,true);await assert.rejects(response.json(),/body used already/);checks.push('Installed npm Response preserves consumed-body semantics');
 await assert.rejects(new Response(Readable.from([Buffer.from('not JSON')])).json(),error=>error.type==='invalid-json');checks.push('npm JSON errors preserve the native fetch error type');
 const Blob=localRequire('minipass-fetch/lib/blob.js');assert.deepStrictEqual(await new Response(new Blob([Buffer.from('{"answer":42}')])).json(),{answer:42});checks.push('npm Blob response bodies retain JSON values');
 const {Minipass}=localRequire('minipass'),body=new Minipass(),pending=parse(body);for(let index=0;index<128;index++)body.write(index===0?'[42':',42');body.end(']');assert.equal((await pending).length,128);assert.equal(body.listenerCount('data'),0);assert.equal(body.listenerCount('end'),0);assert.equal(body.listenerCount('error'),0);checks.push('Many Minipass chunks complete without accumulating parser listeners');
 const closed=new Minipass(),closedResult=assert.rejects(parse(closed),/closed before completing/);closed.destroy();await closedResult;checks.push('Destroyed registry streams reject instead of leaving a pending parser');
 const broken=new Minipass(),brokenResponse=new Response(broken),failed=assert.rejects(brokenResponse.json(),error=>error.type==='system'&&error.message.includes('fixture socket failure'));broken.emit('error',Error('fixture socket failure'));await failed;checks.push('Registry stream failures retain the npm fetch system error');
 const license='Repeated immutable license.\n'.repeat(16000),metadata={versions:Object.fromEntries(Array.from({length:64},(_,index)=>['1.0.'+index,{version:'1.0.'+index,licenseText:license}]))},encoded=Buffer.from(JSON.stringify(metadata));assert.deepStrictEqual(await parse(Readable.from((function*(){for(let offset=0;offset<encoded.length;offset+=16384)yield encoded.subarray(offset,offset+16384);})())),metadata);checks.push('Large repeated metadata retains every version and complete license value');
 const file=path.resolve(__dirname,'../../.revival/vite-packument.json');if(fs.existsSync(file)){const streamed=await parse(fs.createReadStream(file));assert.deepStrictEqual(streamed,JSON.parse(fs.readFileSync(file,'utf8')));checks.push('Complete real Vite registry metadata remains identical to JSON.parse');}
 console.log(JSON.stringify({passed:true,checks:checks.length}));
})().catch(error=>{console.error(error);process.exitCode=1;});
