(async()=>{
 const checks=[],root=ltProjects.info().current.path,entry=root+'\\module-entry.js',dependency=root+'\\sum.js';
 const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};
 const command=(name,...args)=>lt.objs.command.exec_BANG_(cljs.core.keyword(name),...args);
 const open=path=>{command('open-path',path);return ltProofUI.connect();};
 const source='import {sum} from "./sum.js";\nimport data from "./data.json";\nconsole.log("module report", data.price);\nsum(20, data.price);';
 const cm=open(entry);cm.setValue(source);command('save');command('eval-editor');let run=await ltProofUI.pending();
 check('Original file Eval runs ESM and JSON project imports',run.accepted&&run.result.result==='42'&&run.result.mode==='project-javascript');
 check('Module runs retain verified hard quota and process cleanup',run.result.memory.hardPrivateCommit&&run.result.memory.processExited&&run.result.memory.limitBytes===1073741824);
 check('Module console messages appear with the result',run.result.logs[0]==='log: module report 22');
 check('Exact graph sources and identities are displayed',run.result.project.modules.length===3&&document.getElementById('proof-project-snapshot').textContent.includes('sum.js'));
 const firstHash=run.result.project.sha256,firstSourceHash=run.result.sha256;
 cm.setValue('import {answer} from "./awaited.mjs";\nconst value=await Promise.resolve(answer);\nvalue;');run=await ltProofUI.runJavaScript();
 check('Native top-level await works in entry and dependency',run.accepted&&run.result.result==='43'&&run.result.memory.hardPrivateCommit&&run.result.memory.processExited);
 cm.setValue('let total=0;for await(const n of [20,22])total+=n;total;');run=await ltProofUI.runJavaScript();check('Top-level async iteration works through normal Run',run.accepted&&run.result.result==='42');
 open(root+'\\awaited.mjs');command('eval-editor');run=await ltProofUI.pending();check('mjs file evaluates awaited exports',run.accepted&&JSON.parse(run.result.result).answer===43);open(entry);cm.setValue(source);command('save');run=await ltProofUI.runJavaScript();
 const sum=open(dependency);sum.setValue('export const sum = (a,b)=>a+b+1;');open(entry);
 check('Editing a dependency makes the entry result stale',document.getElementById('proof-output').dataset.status==='stale');
 run=await ltProofUI.runJavaScript();check('Unsaved dependency code participates in execution',run.accepted&&run.result.result==='43'&&run.result.project.modules.find(m=>m.name==='sum.js').origin==='editor');
 check('Dependency edit changes graph identity while entry hash stays stable',run.result.project.sha256!==firstHash&&run.result.sha256===firstSourceHash);
 check('Unsaved evaluation never writes a dependency implicitly',ltProof.read(dependency)==='export const sum = (a,b)=>a+b;');
 cm.setValue('import {sum} from "./sum.js";\nnew Promise(resolve=>setTimeout(()=>resolve(sum(20,22)),300));');
 const pending=ltProofUI.runJavaScript();await new Promise(resolve=>setTimeout(resolve,180));sum.setValue('export const sum = (a,b)=>a+b+2;');run=await pending;
 check('Dependency edit during execution rejects the result as stale',!run.accepted&&run.reason==='source changed'&&document.getElementById('proof-output').dataset.status==='stale');
 run=await ltProofUI.runJavaScript();check('Later run recovers with the changed dependency',run.accepted&&run.result.result==='44');
 cm.setValue('const item=require("./common.cjs");item.answer;');run=await ltProofUI.runJavaScript();check('CommonJS require runs in original editor',run.accepted&&run.result.result==='43');
 cm.setValue('module.exports={answer:42};');run=await ltProofUI.runJavaScript();check('CommonJS exports display their value',run.accepted&&JSON.parse(run.result.result).answer===42);
 open(root+'\\common.cjs');command('eval-editor');run=await ltProofUI.pending();check('A cjs file opens and evaluates through its normal command',run.accepted&&JSON.parse(run.result.result).answer===43);open(entry);
 cm.setValue('export const answer=42;');run=await ltProofUI.runJavaScript();check('Named ESM exports display their values',run.accepted&&JSON.parse(run.result.result).answer===42);
 cm.setValue('const answer=42;export {answer as default};');run=await ltProofUI.runJavaScript();check('ESM default aliases display their value',run.accepted&&run.result.result==='42');
 cm.setValue('export const answer=require("./common.cjs").answer;');run=await ltProofUI.runJavaScript();check('Named ESM exports can consume a CommonJS dependency',run.accepted&&JSON.parse(run.result.result).answer===43);
 cm.setValue('import {answer} from "./barrel.js";answer;');run=await ltProofUI.runJavaScript();check('Re-exports resolve through the graph',run.accepted&&run.result.result==='43');
 cm.setValue('import("./common.cjs").then(item=>item.default.answer);');run=await ltProofUI.runJavaScript();check('Literal dynamic imports resolve as Promises',run.accepted&&run.result.result==='43');
 cm.setValue('const a=require("./cycle-a.cjs");[a.name,a.other];');run=await ltProofUI.runJavaScript();check('CommonJS circular dependencies resolve once',run.accepted&&run.result.result==='["a","b"]');
 cm.setValue('import fs from "node:fs";fs;');run=await ltProofUI.runJavaScript();check('Node imports fail without granting capabilities',run.reason==='error'&&run.error.includes('Node import is unavailable'));
 cm.setValue('import x from "../outside.js";x;');run=await ltProofUI.runJavaScript();check('Module traversal is rejected',run.reason==='error'&&run.error.includes('leaves the project'));
 cm.setValue('import x from "./missing.js";x;');run=await ltProofUI.runJavaScript();check('Missing import errors identify entry location',run.reason==='error'&&run.error.includes('module-entry.js:1:')&&run.error.includes('Module not found'));
 cm.setValue('import {bad} from "./bad.js";bad;');run=await ltProofUI.runJavaScript();check('Syntax errors identify the dependency and line',run.reason==='error'&&run.error.includes('bad.js:1:'));
 cm.setValue('import {broken} from "./throws.js";\nbroken();');run=await ltProofUI.runJavaScript();check('Runtime errors map to original imported source',run.reason==='error'&&run.error.includes('throws.js:2:')&&run.location?.path===root+'\\throws.js'&&run.location.line===2);
 check('Error location is a link without sidebar action buttons',document.getElementById('proof-error-open').tagName==='A'&&document.querySelectorAll('#proof-calculation button').length===0);
 document.getElementById('proof-error-open').click();check('Error link opens the original file and reported line',document.getElementById('proof-versions').textContent.includes('throws.js')&&ltProofUI.connect().getCursor().line===1);
 open(entry);cm.setValue('import {broken} from "./throws.js";broken();');run=await ltProofUI.runJavaScript();const changed=open(root+'\\throws.js');changed.replaceRange('// changed\n',{line:0,ch:0});open(entry);document.getElementById('proof-error-open').click();check('Error navigation identifies changed source honestly',document.getElementById('proof-notice').textContent.includes('changed since the failed run'));changed.setValue('export function broken() {\n  throw new Error("dependency failed");\n}\n');open(entry);
 cm.setValue('import "./sum.js";\n(()=>{\n  throw new Error("entry failed");\n})();');run=await ltProofUI.runJavaScript();check('Runtime error maps through generated entry completion',run.reason==='error'&&run.location?.path===entry&&run.location.line===3);
 cm.setValue('40;\n41;\n42;\nawait Promise.reject(new Error("selection failed"));');cm.setCursor({line:3,ch:10});command('eval-editor-form');run=await ltProofUI.pending();check('Selected-line await error uses the full editor line',run.reason==='error'&&run.error.includes('module-entry.js:4:')&&run.location?.line===4&&document.getElementById('proof-error-open').textContent==='module-entry.js:4:'+run.location.column);
 cm.setValue('0;\nawait Promise.resolve(43);');cm.setCursor({line:1,ch:10});command('eval-editor-form');run=await ltProofUI.pending();check('Native await works in selection or line evaluation',run.accepted&&run.result.result==='43'&&run.result.scope==='selection');
 command('new-file');const untitled=ltProofUI.connect();untitled.setValue('const answer=await Promise.resolve(43);answer;');testMenuClick('Run file');run=await ltProofUI.pending();check('Untitled JavaScript evaluates native await',run.accepted&&run.result.result==='43'&&run.result.source==='const answer=await Promise.resolve(43);answer;');open(entry);
 command('open-file');const standalone=ltProofUI.connect();command('eval-editor');run=await ltProofUI.pending();check('Native file selection can run standalone awaited module',run.accepted&&run.result.result==='43');standalone.setValue('import "./sibling.mjs";42;');command('eval-editor');run=await ltProofUI.pending();check('Standalone file selection does not grant sibling module access',run.reason==='error'&&run.error.includes('Open the containing folder'));open(entry);
 cm.setValue('await new Promise(()=>{});42;');run=await ltProofUI.runJavaScript();check('Unresolved top-level await is bounded',run.reason==='error'&&run.error.includes('1500 ms'));
 cm.setValue('await new Promise(()=>{});42;');const topStop=ltProofUI.runJavaScript();await new Promise(resolve=>setTimeout(resolve,150));testMenuClick('Stop');run=await topStop;check('Stop cancels native module loading',!run.accepted&&document.getElementById('proof-output').dataset.status==='cancelled');
 cm.setValue('import "./loop.js";42;');run=await ltProofUI.runJavaScript();check('Infinite loops inside dependencies are terminated',run.reason==='error'&&run.error.includes('1500 ms'));
 cm.setValue('import item from "./common.cjs";item.answer;');run=await ltProofUI.runJavaScript();check('Module error recovery leaves the editor usable',run.accepted&&run.result.result==='43');
 cm.setValue('import "./common.cjs";new Promise(()=>{});');const stopped=ltProofUI.runJavaScript();await new Promise(resolve=>setTimeout(resolve,150));testMenuClick('Stop');run=await stopped;
 check('Stop cancels a real module run',!run.accepted&&document.getElementById('proof-output').dataset.status==='cancelled');
 cm.setValue('import {sum} from "./sum.js";[typeof process,typeof fetch,typeof Worker,sum(20,22)];');run=await ltProofUI.runJavaScript();check('Bundled modules retain sandbox capabilities',run.accepted&&run.result.result==='["undefined","undefined","undefined",44]');
 open(dependency);sum.setValue('export const sum = (a,b)=>a+b+1;');command('save');open(entry);cm.setValue(source);command('save');run=await ltProofUI.runJavaScript();
 check('Saved module report finishes with current output 43',run.accepted&&run.result.result==='43'&&document.getElementById('proof-output').dataset.status==='current');
 ltProof.write(root+'\\data.json','{"price":23}');await new Promise(resolve=>setTimeout(resolve,1200));
 check('External dependency changes mark output stale',document.getElementById('proof-output').dataset.status==='stale');
 run=await ltProofUI.runJavaScript();check('External dependency changes participate in the next run',run.accepted&&run.result.result==='44');
 ltProof.write(root+'\\data.json','{"price":22}');run=await ltProofUI.runJavaScript();
 return {passed:true,checks,result:run.result};
})()
