'use strict';
process.env.LT_REVIVAL_TEST='1';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const policy=require('../../deploy/core/proof-policy.cjs'),projects=require('../../deploy/core/revival-projects.cjs'),modules=require('../../deploy/core/proof-modules.cjs');
const root=path.join(policy.root,'module-tests',crypto.randomUUID());fs.mkdirSync(root,{recursive:true});
const saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null;
const checks=[];async function check(name,fn){await fn();checks.push(name);}
(async()=>{try{
 projects.activate(root);const entry=path.join(root,'index.js');
 fs.writeFileSync(path.join(root,'sum.js'),'export const sum = (a,b)=>a+b;');
 fs.writeFileSync(path.join(root,'data.json'),'{"price":22}');
 fs.writeFileSync(path.join(root,'common.cjs'),'module.exports={price:23};');
 const options={path:entry},compile=source=>modules.prepare(source,options);
 const evaluatePrepared=async prepared=>(await import('data:text/javascript;base64,'+Buffer.from(prepared.code).toString('base64'))).default; // Trusted compilation smoke test; actual sandbox tests are separate.
 const evaluate=async source=>evaluatePrepared(await compile(source));
 await check('ESM import and final-expression result',async()=>assert.equal(await evaluate('import {sum} from "./sum.js";sum(20,22);'),42));
 await check('ESM default export awaits normally',async()=>assert.equal(await evaluate('export default Promise.resolve(43);'),43));
 await check('Native top-level await returns the last expression',async()=>assert.equal(await evaluate('const value=await Promise.resolve(42);value;'),42));
 await check('Top-level async iteration works',async()=>assert.equal(await evaluate('let total=0;for await(const n of [20,22])total+=n;total;'),42));
 fs.writeFileSync(path.join(root,'awaited.mjs'),'export const answer=await Promise.resolve(43);');
 await check('Top-level await in a dependency resolves first',async()=>assert.equal(await evaluate('import {answer} from "./awaited.mjs";answer;'),43));
 await check('JSON and extensionless resolution',async()=>assert.equal(await evaluate('import {sum} from "./sum";import data from "./data.json";sum(20,data.price);'),42));
 await check('CommonJS require result',async()=>assert.equal(await evaluate('const x=require("./common.cjs");x.price+20;'),43));
 await check('CommonJS exports remain an object',async()=>assert.equal(JSON.stringify(await evaluate('module.exports={price:42};')),'{"price":42}'));
 await check('Named module exports remain an object',async()=>assert.equal(JSON.stringify(await evaluate('export const price=42;')),'{"price":42}'));
 await check('Default export aliases return their value',async()=>assert.equal(await evaluate('const price=42;export {price as default};'),42));
 await check('ESM named exports with a local require keep their namespace',async()=>assert.equal(JSON.stringify(await evaluate('export const price=require("./common.cjs").price;')),'{"price":23}'));
 const first=await compile('import {sum} from "./sum.js";sum(20,22);');
 await check('Graph hashes include sources and exact file names',async()=>{assert.equal(first.project.modules.length,2);assert.equal(first.project.modules.find(m=>m.name==='sum.js').source,'export const sum = (a,b)=>a+b;');});
 await check('Unsaved dependency overrides disk and changes graph identity',async()=>{const second=await modules.prepare('import {sum} from "./sum.js";sum(20,22);',{...options,buffers:[{path:path.join(root,'sum.js'),source:'export const sum = (a,b)=>a+b+1;'}]});assert.equal(await evaluatePrepared(second),43);assert.notEqual(first.project.sha256,second.project.sha256);});
 for(const [name,source] of [['Node import','import fs from "node:fs";fs;'],['Package import','import x from "some-package";x;'],['Traversal','import x from "../outside.js";x;'],['Missing module','import x from "./missing.js";x;']])await check(name+' rejected',async()=>assert.rejects(()=>compile(source)));
 fs.writeFileSync(path.join(root,'bad.js'),'export const x = ;');
 await check('Module syntax errors name the source file and line',async()=>assert.rejects(()=>compile('import {x} from "./bad.js";x;'),/bad\.js:1:/));
 await check('Pre-cancelled compilation does not start',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(()=>modules.prepare('import "./sum.js";',options,controller.signal),/cancelled/);});
 await check('Large imported sources are bounded',async()=>{fs.writeFileSync(path.join(root,'large.js'),' '.repeat(16385));await assert.rejects(()=>compile('import "./large.js";'),/16 KiB/);});
 await check('Graph module count is bounded',async()=>{let source='';for(let i=0;i<33;i++){fs.writeFileSync(path.join(root,'count-'+i+'.js'),'export const x=42;');source+='import "./count-'+i+'.js";\n';}await assert.rejects(()=>compile(source),/32 module/);});
 await check('Aggregate graph source is bounded',async()=>{let source='';for(let i=0;i<5;i++){fs.writeFileSync(path.join(root,'budget-'+i+'.js'),'/*'+'x'.repeat(15000)+'*/');source+='import "./budget-'+i+'.js";\n';}await assert.rejects(()=>compile(source),/64 KiB/);});
 await check('Single-file picker grant does not permit module graph access',async()=>{const leaf=path.join(policy.root,'module-leaf-'+crypto.randomUUID()+'.js');fs.writeFileSync(leaf,'');policy.grantFile(leaf);await assert.rejects(()=>modules.prepare('import "./sum.js";',{path:leaf}),/Open.*project/);});
 await check('Selected standalone module can await without a directory grant',async()=>{const leaf=path.join(policy.root,'module-single-'+crypto.randomUUID()+'.mjs');fs.writeFileSync(leaf,'');policy.grantFile(leaf);assert.equal(await evaluatePrepared(await modules.prepare('export default await Promise.resolve(42);',{path:leaf})),42);});
 fs.writeFileSync(path.join(root,'throws.js'),'export function broken(){\n  throw new Error("dependency failed");\n}\n');
 await check('Runtime stack maps back to an imported source line',async()=>{const prepared=await compile('import {broken} from "./throws.js";broken();');try{await evaluatePrepared(prepared);assert.fail('Expected runtime error');}catch(error){const mapped=modules.runtimeError(prepared,{error:error.message,stack:error.stack});assert.equal(mapped.location.path,path.join(root,'throws.js'));assert.equal(mapped.location.line,2);assert.ok(mapped.location.sourceLine.includes('throw new Error'));}});
 await check('Synthetic completion maps back to the original entry expression',async()=>{const prepared=await compile('import "./sum.js";\n(()=>{\n  throw new Error("entry failed");\n})();');try{await evaluatePrepared(prepared);assert.fail('Expected runtime error');}catch(error){const mapped=modules.runtimeError(prepared,{error:error.message,stack:error.stack});assert.equal(mapped.location.path,entry);assert.equal(mapped.location.line,3);}});
 await check('Unknown stack positions cannot open files outside the graph',async()=>assert.equal(modules.runtimeError(first,{error:'spoofed',stack:'at C:\\Windows\\win.ini:1:1'}).location,undefined));
 await check('Invalid generated positions preserve the original error',async()=>{const failure=modules.runtimeError(first,{error:'custom stack',stack:'at light-table-project.js:0:0'});assert.equal(failure.message,'custom stack');assert.equal(failure.location,undefined);});
 await check('Untitled native await compiles as an isolated module',async()=>assert.equal(await evaluatePrepared(await modules.prepare('const answer=await Promise.resolve(43);answer;')),43));
 await check('Untitled named exports retain their namespace',async()=>{const prepared=await modules.prepare('export const answer=42;');const ns=await import('data:text/javascript;base64,'+Buffer.from(prepared.code).toString('base64'));assert.equal(prepared.resultExport,'namespace');assert.equal(ns.answer,42);});
 await check('Selected code retains source locations in its own snapshot',async()=>{const prepared=await modules.prepare('await Promise.reject(new Error("selection failed"));',{path:entry,inline:true});try{await evaluatePrepared(prepared);assert.fail('Expected rejection');}catch(error){const mapped=modules.runtimeError(prepared,{error:error.message,stack:error.stack});assert.equal(mapped.location.path,entry);assert.equal(mapped.location.line,1);}});
 console.log(JSON.stringify({passed:true,checks:checks.length}));
}finally{modules.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);}})().catch(error=>{console.error(error);process.exitCode=1;});
