(async()=>{
 const root=ltProjects.info().current.path,entry=root+'\\index.js',checks=[];
 const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);console.info('Node editor check: '+name);};
 const command=(name,...args)=>lt.objs.command.exec_BANG_(cljs.core.keyword(name),...args);
 const open=file=>{command('open-path',file);return ltProofUI.connect();};
 const cm=open(entry),run=async source=>{console.info('Node editor run: '+source.slice(0,180));cm.setValue(source);ltProofUI.refreshMenus(true);for(let i=0;i<50&&!testMenuItem('Run file with Node').enabled;i++)await new Promise(resolve=>setTimeout(resolve,10));testMenuClick('Run file with Node');return ltProofUI.pending();};
 let result=await run('42;');
 check('Declining project trust launches no project code',!result.accepted&&result.error.includes('execution was cancelled'));
 result=await run('({answer:42,main:require.main===module,buffer:Buffer.from("native").toString()});');
 check('Native menu executes real Node code and main-module semantics',result.accepted&&JSON.parse(result.result.result).answer===42&&JSON.parse(result.result.result).main&&JSON.parse(result.result.result).buffer==='native');
 check('Native result has verified quota, process exit and exact editor source',result.result.memory.hardPrivateCommit&&result.result.memory.processExited&&result.result.source===cm.getValue()&&result.result.project.modules.find(item=>item.path===entry).source===cm.getValue());
 check('Native execution uses the original JavaScript client association',lt.objs.clients.javascript.connected_QMARK_());
 const workerPath=root+'\\worker.cjs',workerOriginal=ltProof.read(workerPath),threadSource='const {Worker}=require("node:worker_threads");new Promise((resolve,reject)=>{const worker=new Worker("./worker.cjs",{workerData:{value:21}});worker.once("message",resolve);worker.once("error",reject);});';
 result=await run(threadSource);
 check('Actual Node worker result and source appear in the editor',result.accepted&&result.result.result==='42'&&result.result.project.modules.some(item=>item.path===workerPath)&&result.result.contexts.length===2&&document.getElementById('proof-output').dataset.status==='current');
 const workerCM=open(workerPath);workerCM.setValue(workerOriginal.replace('value*2','value*2+1'));open(entry);
 check('An unsaved worker edit makes its parent result stale',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runNode();
 check('Node rerun uses the current worker buffer and refreshes its parent',result.accepted&&result.result.result==='43'&&result.result.project.modules.some(item=>item.path===workerPath&&item.origin==='editor'&&item.source===workerCM.getValue())&&document.getElementById('proof-output').dataset.status==='current');
 check('Worker execution preserves the saved file and removes private contexts',ltProof.read(workerPath)===workerOriginal&&result.result.memory.contextFilesRemoved&&result.result.memory.processExited);
 workerCM.setValue(workerOriginal);open(entry);
 result=await run('const {fork}=require("node:child_process");new Promise((resolve,reject)=>{const child=fork("./child.cjs");child.once("message",resolve);child.once("error",reject);child.once("exit",code=>{if(code)reject(new Error("Child failed"))});child.send({value:21});});');
 check('Native fork messaging completes through the original JavaScript client',result.accepted&&result.result.result==='42'&&result.result.project.modules.some(item=>item.name==='child.cjs'));
 check('Fork results retain the shared hard quota and context cleanup',result.result.contexts.length===2&&result.result.contexts[0].pid!==result.result.contexts[1].pid&&result.result.memory.hardPrivateCommit&&result.result.memory.contextFilesRemoved);
 const inlineWorker='const worker=new (require("node:worker_threads").Worker)("./worker.cjs",{workerData:{value:21}});worker.once("message",value=>console.log(value));worker.once("error",error=>{throw error;});';
 result=await run('Number(require("node:child_process").execFileSync(process.execPath,["--title=LightTableEditorFixture","--eval",'+JSON.stringify(inlineWorker)+']).toString());');
 check('The editor executes inline Node workers with inherited process flags',result.accepted&&result.result.result==='42'&&result.result.contexts.length===3&&result.result.project.modules.some(item=>item.path===workerPath)&&document.getElementById('proof-output').dataset.status==='current');
 const inlineFork='if(process.env.LT_FIXTURE_EVAL_PARENT)throw Error("Repeated inline parent");process.env.LT_FIXTURE_EVAL_PARENT="1";const child=require("node:child_process").fork("./child.cjs");child.once("message",value=>console.log(value));child.once("exit",code=>{if(code)process.exitCode=code;});child.send({value:21});';
 result=await run('Number(require("node:child_process").execFileSync(process.execPath,["--eval",'+JSON.stringify(inlineFork)+']).toString());');
 check('The editor executes the requested fork file from inline Node code',result.accepted&&result.result.result==='42'&&result.result.contexts.length===3&&result.result.project.modules.some(item=>item.name==='child.cjs')&&result.result.memory.contextFilesRemoved);
 result=await run('const pending=require("node:util").promisify(require("node:child_process").execFile)(process.execPath,["child-process-output.cjs"]);if(!pending.child.pid)throw Error("Missing promise child");pending.then(({stdout,stderr})=>{if(stderr!=="")throw Error("Unexpected error output");return Number(stdout);});');
 check('Promisified child-process results and sources render through the original client',result.accepted&&result.result.result==='42'&&result.result.project.modules.some(item=>item.name==='child-process-output.cjs')&&document.getElementById('proof-output').dataset.status==='current');
 result=await run('require("node:util").promisify(require("node:child_process").execFile)(process.execPath,["--eval","process.stdout.write(\\"42\\");process.stderr.write(\\"fixture-error\\");process.exit(7)"]).catch(error=>{if(error.code!==7||error.stderr!=="fixture-error")throw error;console.log("handled exit:",error.code);return Number(error.stdout);});');
 check('Project handling of a promisified child failure completes with current output',result.accepted&&result.result.result==='42'&&result.result.logs.join('\n').includes('handled exit: 7')&&document.getElementById('proof-output').dataset.status==='current');
 result=await run(threadSource.replace('./worker.cjs','./failed-worker.cjs'));
 check('Worker failures retain their original file and line in Activity',!result.accepted&&result.location?.path===root+'\\failed-worker.cjs'&&result.location.line===2&&document.getElementById('proof-output').dataset.status==='rejected');
 document.getElementById('proof-error-open').click();check('Worker error navigation opens the original editor line',ltProofUI.connect().getCursor().line===1);open(entry);
 cm.setValue('const {Worker}=require("node:worker_threads");const worker=new Worker("./loop-worker.cjs");worker.once("message",value=>console.log(value));new Promise(()=>{});');
 const runningWorker=ltProofUI.runNode();for(let i=0;i<120&&!document.getElementById('proof-output').textContent.includes('worker ready');i++)await new Promise(resolve=>setTimeout(resolve,25));
 check('A busy worker leaves Activity responsive with its actual output',document.getElementById('proof-output').dataset.status==='running'&&document.getElementById('proof-output').textContent.includes('worker ready')&&testMenuItem('Stop').enabled);
 testMenuClick('Stop');await runningWorker;check('Native menu Stop terminates the busy worker and restores the editor',document.getElementById('proof-output').dataset.status==='cancelled'&&!ltProofUI.isRunning());
 result=await run('console.log(JSON.stringify({exceptions:process.listenerCount("uncaughtException"),rejections:process.listenerCount("unhandledRejection"),send:typeof process.send}));42;');
 check('Node editor runs retain native project handlers and CLI process identity',result.accepted&&result.result.result==='42'&&result.result.logs.join('\n').includes('{"exceptions":0,"rejections":0,"send":"undefined"}'));
 result=await run('process.once("uncaughtException",error=>console.log("project handled:",error.message));setTimeout(()=>{throw new Error("expected timer error")},5);42;');
 check('A project-handled timer exception completes with current output in Activity',result.accepted&&result.result.result==='42'&&result.result.logs.join('\n').includes('project handled: expected timer error')&&document.getElementById('proof-output').dataset.status==='current');
 result=await run('process.once("unhandledRejection",error=>console.log("project rejection:",error.message));Promise.reject(new Error("expected rejection"));42;');
 check('A project Promise-rejection handler completes through the original client',result.accepted&&result.result.result==='42'&&result.result.logs.join('\n').includes('project rejection: expected rejection'));
 result=await run('module.exports={answer:21};process.once("beforeExit",()=>{module.exports={answer:42};});');
 check('Node editor captures exports after project beforeExit work',result.accepted&&JSON.parse(result.result.result).answer===42&&result.result.memory.processExited);
 result=await run('module.exports={answer:42};process.on("exit",code=>console.log("project cleanup:",code));process.exit(0);');
 check('An explicit successful exit retains source, result and cleanup output',result.accepted&&JSON.parse(result.result.result).answer===42&&result.result.source===cm.getValue()&&result.result.logs.join('\n').includes('project cleanup: 0')&&document.getElementById('proof-output').dataset.status==='current');
 const dataSource='const fs=require("node:fs");const orders=JSON.parse(fs.readFileSync("orders.json","utf8"));orders.reduce((sum,item)=>sum+item.price*item.count,0);';
 result=await run(dataSource);check('Filesystem-backed revenue report executes in Node',result.accepted&&result.result.result==='114'&&result.result.project.modules.some(item=>item.name==='orders.json'));
 ltProof.write(root+'\\orders.json','[{"price":13,"count":2},{"price":30,"count":3}]');await new Promise(resolve=>setTimeout(resolve,1200));
 check('Changing filesystem input marks the Node report stale',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runNode();check('Node rerun uses changed data and updates graph identity',result.accepted&&result.result.result==='116');
 result=await run('require("acorn").parse("42",{ecmaVersion:"latest"}).body[0].expression.value;');check('Installed library executes with real Node package resolution',result.accepted&&result.result.result==='42');
 result=await run('require("node:fs").readFileSync("input.bin").toString("hex");');check('Binary filesystem input retains a current byte snapshot',result.accepted&&result.result.result==='"00fffe2a"'&&result.result.project.modules.find(item=>item.name==='input.bin').kind==='binary'&&document.getElementById('proof-output').dataset.status==='current');
 result=await run('import path from "node:path";const answer=await Promise.resolve(42);({answer,name:path.basename(import.meta.filename)});');check('Unsaved js ESM imports and native await run correctly',result.accepted&&JSON.parse(result.result.result).answer===42&&JSON.parse(result.result.result).name==='index.js');
 result=await run('require("./broken.cjs")();');check('Native dependency errors map to captured source line',!result.accepted&&result.location?.path===root+'\\broken.cjs'&&result.location.line===2);
 document.getElementById('proof-error-open').click();check('Node error link opens its source line',ltProofUI.connect().getCursor().line===1);open(entry);
 result=await run('require("node:fs").writeFileSync("generated.txt","Node output");42;');check('Node writes actual project files and recovers after errors',result.accepted&&result.result.result==='42'&&ltProof.read(root+'\\generated.txt')==='Node output');
 cm.setValue('const server=require("node:http").createServer((req,res)=>res.end("native server"));server.listen(0,"127.0.0.1",()=>console.log("server ready",server.address().port));new Promise(()=>{});');
 const server=ltProofUI.runNode();for(let i=0;i<120&&!document.getElementById('proof-output').textContent.includes('server ready');i++)await new Promise(resolve=>setTimeout(resolve,25));
 check('Running Node server streams output into Activity',document.getElementById('proof-output').dataset.status==='running'&&document.getElementById('proof-output').textContent.includes('server ready'));
 check('Native server enables the existing menu Stop',testMenuItem('Stop').enabled);testMenuClick('Stop');await server;
 check('Menu Stop restores the editor after a Node server run',document.getElementById('proof-output').dataset.status==='cancelled'&&!ltProofUI.isRunning());
 cm.setValue('new Promise(()=>{});');const oldNode=ltProofUI.runNode();await new Promise(resolve=>setTimeout(resolve,100));cm.setValue('43;');command('eval-editor');const isolated=await ltProofUI.pending();await oldNode;
 check('Isolated Run replaces a pending Node execution',isolated.accepted&&isolated.result.result==='43'&&isolated.result.sandbox===true&&document.getElementById('proof-output').dataset.status==='current');
 cm.setValue('new Promise(()=>{});');const oldIsolated=ltProofUI.runJavaScript();await new Promise(resolve=>setTimeout(resolve,100));cm.setValue('44;');result=await ltProofUI.runNode();await oldIsolated;
 check('Node Run replaces a pending isolated execution',result.accepted&&result.result.result==='44'&&document.getElementById('proof-output').dataset.status==='current');
 cm.setValue('42;');command('save');ltProofUI.refreshMenus(true);await new Promise(resolve=>setTimeout(resolve,80));
 check('Project npm scripts are present in the native Run menu',testMenuItem(['Run','npm scripts','test']).enabled!==false);
 testMenuClick(['Run','npm scripts','test']);result=await ltProofUI.pending();
 check('npm menu runs the real Node test runner',result.accepted&&result.result.mode==='npm-script'&&JSON.parse(result.result.result).exitCode===0&&result.result.logs.join('\n').includes('real Node test runner'));
 check('npm completion records saved project inputs and verified quota',result.result.project.snapshotKind==='inputs'&&result.result.memory.hardPrivateCommit&&result.result.memory.processExited&&document.getElementById('proof-project-snapshot').textContent.includes('Saved project inputs'));
 check('npm retains its normal lifecycle behavior',ltProof.read(root+'\\pretest-marker.txt')==='pretest');
 open(entry);cm.setValue('43;');testMenuClick(['Run','npm scripts','test']);result=await ltProofUI.pending();
 check('npm scripts require saving changed project files',!result.accepted&&result.error.includes('Save project files'));open(entry);command('save');
 result=await run('({answer:42,node:process.versions.node,main:require.main===module});');
 check('Node workflow finishes with a current source-linked result',result.accepted&&JSON.parse(result.result.result).answer===42&&document.getElementById('proof-output').dataset.status==='current');
 check('Activity remains free of action buttons',document.querySelectorAll('#proof-calculation button').length===0);
 return {passed:true,checks,result:result.result};
})()
