'use strict';
process.env.LT_REVIVAL_TEST='1';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const policy=require('../../deploy/core/proof-policy.cjs'),projects=require('../../deploy/core/revival-projects.cjs'),node=require('../../deploy/core/revival-node.cjs'),memory=require('../../deploy/core/proof-memory.cjs'),modules=require('../../deploy/core/proof-modules.cjs');
const {fixture,write}=require('./package-fixtures.cjs'),root=path.join(policy.root,'node-tests',crypto.randomUUID()),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null;
const checks=[];async function check(name,fn){try{await fn();checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
(async()=>{try{
 fixture(root);projects.activate(root);const entry=write(root,'index.js','');const run=source=>node.run(101,{path:entry,source});
 let result;
 await check('Actual Node CLI evaluates the current source expression',async()=>{result=await run('12+30;');assert.equal(result.result,'42');assert.equal(result.project.modules.find(item=>item.path===entry).source,'12+30;');});
 await check('Quota is verified before Node code and released after exit',async()=>{assert.equal(result.memory.hardPrivateCommit,true);assert.equal(result.memory.processExited,true);assert.equal(result.memory.limitBytes,1073741824);});
 await check('Native CJS main and path identity are preserved',async()=>{const output=await run('({main:require.main===module,name:__filename,dir:__dirname,node:process.versions.node});');const value=JSON.parse(output.result);assert.equal(value.main,true);assert.equal(value.name,entry);assert.equal(value.dir,root);assert.equal(value.node,node.discover().version.slice(1));});
 await check('Node builtins work with native Buffer and crypto',async()=>{const output=await run('require("node:crypto").createHash("sha256").update(Buffer.from("42")).digest("hex");');assert.equal(output.result,JSON.stringify(crypto.createHash('sha256').update('42').digest('hex')));});
 write(root,'orders.json',[{price:12,count:2},{price:30,count:3}]);
 await check('Filesystem data is read and included in the source identity',async()=>{const output=await run('const fs=require("node:fs");const orders=JSON.parse(fs.readFileSync("orders.json","utf8"));orders.reduce((sum,item)=>sum+item.price*item.count,0);');assert.equal(output.result,'114');assert.ok(output.project.modules.some(item=>item.name==='orders.json'));});
 await check('Filesystem writes work inside the real project',async()=>{await run('require("node:fs").writeFileSync("generated.txt","verified");42;');assert.equal(fs.readFileSync(path.join(root,'generated.txt'),'utf8'),'verified');});
 await check('Asynchronous filesystem data participates in the snapshot',async()=>{const output=await node.run(101,{path:write(root,'async.mjs',''),source:'import {readFile} from "node:fs/promises";const data=await readFile("orders.json","utf8");JSON.parse(data).length;'});assert.equal(output.result,'2');assert.ok(output.project.modules.some(item=>item.name==='orders.json'));});
 await check('Binary filesystem input retains exact byte identity',async()=>{const bytes=Buffer.from([0,255,254,42]);fs.writeFileSync(path.join(root,'input.bin'),bytes);const output=await run('require("node:fs").readFileSync("input.bin").toString("hex");'),input=output.project.modules.find(item=>item.name==='input.bin');assert.equal(output.result,'"00fffe2a"');assert.equal(input.source,null);assert.equal(input.sha256,crypto.createHash('sha256').update(bytes).digest('hex'));});
 await check('Native CommonJS exports return their value',async()=>assert.equal((await run('module.exports={answer:42};')).result,'{"answer":42}'));
 await check('Native bigint and symbols retain their types in results',async()=>{assert.equal((await run('42n;')).result,'42n');assert.equal((await run('Symbol("answer");')).result,'Symbol(answer)');});
 await check('Native collections and cycles produce useful inspected results',async()=>{assert.match((await run('new Map([["answer",42]]);')).result,/Map\(1\).*answer/);assert.match((await run('const value={answer:42};value.self=value;value;')).result,/Circular/);});
 await check('Native nonfinite numbers are not misrepresented as null',async()=>{assert.equal((await run('NaN;')).result,'NaN');assert.equal((await run('Infinity;')).result,'Infinity');});
 await check('Result inspection does not invoke object getters',async()=>assert.match((await run('({get answer(){throw new Error("getter should not run")}});')).result,/Getter/));
 await check('Actual installed CommonJS package executes',async()=>assert.equal((await run('require("acorn").parse("42",{ecmaVersion:"latest"}).body[0].expression.value;')).result,'42'));
 const esm=write(root,'esm.mjs','');
 await check('Native ESM can import Node builtins and await',async()=>{const output=await node.run(101,{path:esm,source:'import path from "node:path";const answer=await Promise.resolve(42);({answer,base:path.basename(import.meta.filename)});'});assert.deepEqual(JSON.parse(output.result),{answer:42,base:'esm.mjs'});});
 await check('Native ESM default exports return their value',async()=>assert.equal((await node.run(101,{path:esm,source:'export default await Promise.resolve(43);'})).result,'43'));
 await check('Native named exports retain their namespace',async()=>assert.equal((await node.run(101,{path:esm,source:'export const answer=42;'})).result,'{"answer":42}'));
 await check('Unsaved js module syntax uses native syntax detection',async()=>assert.equal((await run('import path from "node:path";path.basename(import.meta.filename);')).result,'"index.js"'));
 await check('Node runtime errors map to captured dependency source',async()=>{write(root,'broken.cjs','module.exports=()=>{\n throw new Error("native dependency failed");\n};');await assert.rejects(()=>run('require("./broken.cjs")();'),error=>error.location?.path===path.join(root,'broken.cjs')&&error.location.line===2);});
 write(root,'test.cjs','const test=require("node:test");const assert=require("node:assert/strict");test("real Node test runner",()=>assert.equal(20+22,42));');
 const manifest=path.join(root,'package.json'),json=JSON.parse(fs.readFileSync(manifest,'utf8'));json.scripts={test:'node --test test.cjs'};write(root,'package.json',json);
 await check('Actual npm script runs the native Node test runner',async()=>{const output=await node.run(101,{path:manifest,source:fs.readFileSync(manifest,'utf8'),script:'test'});assert.ok(output.logs.join('\n').includes('real Node test runner'));assert.equal(output.memory.hardPrivateCommit,true);assert.equal(output.memory.processExited,true);});
 await check('Failed npm tests retain stdout and map the failing project source',async()=>{
  const testFile=path.join(root,'test.cjs'),original=fs.readFileSync(testFile,'utf8');write(root,'test.cjs','const test=require("node:test"),assert=require("node:assert/strict");\ntest("intentional failure",()=>assert.equal(42,43));');
  try{await assert.rejects(()=>node.run(101,{path:manifest,source:fs.readFileSync(manifest,'utf8'),script:'test'}),error=>error.logs.join('\n').includes('intentional failure')&&error.location?.path===testFile&&error.location.line===2);}finally{fs.writeFileSync(testFile,original);}
 });
 await check('A newly created project has working native start and test scripts',async()=>{
  const starter=projects.create(projects.chooseParent(root).token,'starter-project'),file=path.join(starter.path,'package.json'),source=fs.readFileSync(file,'utf8');
  try{const test=await node.run(101,{path:file,source,script:'test'});assert.match(test.logs.join('\n'),/adds the project prices/);assert.match(test.logs.join('\n'),/handles discounts/);assert.equal(test.memory.processExited,true);const start=await node.run(101,{path:file,source,script:'start'});assert.match(start.logs.join('\n'),/Project is running/);}finally{projects.activate(root);}
 });
 await check('An actual npm build runs esbuild and its native child under the quota',async()=>{
  for(const name of ['esbuild','@esbuild/win32-x64'])fs.cpSync(path.resolve(__dirname,'../../deploy/core/node_modules',name),path.join(root,'node_modules',name),{recursive:true});
  write(root,'build.cjs','require("esbuild").buildSync({entryPoints:["site.js"],bundle:true,minify:true,outfile:"dist/site.js"});console.log("Build complete");');write(root,'site.js','import {answer} from "./answer.js";console.log(answer);');write(root,'answer.js','export const answer=42;');
  const buildJson=JSON.parse(fs.readFileSync(manifest,'utf8'));buildJson.scripts.build='node build.cjs';write(root,'package.json',buildJson);
  const output=await node.run(101,{path:manifest,source:fs.readFileSync(manifest,'utf8'),script:'build'});assert.match(output.logs.join('\n'),/Build complete/);assert.match(fs.readFileSync(path.join(root,'dist/site.js'),'utf8'),/42/);assert.equal(output.memory.hardPrivateCommit,true);assert.equal(output.memory.processExited,true);
 });
 await check('Quota attachment failure prevents all project code',async()=>{const attach=memory.attach;memory.attach=async()=>{throw Error('quota attachment test failure');};try{await assert.rejects(()=>run('require("node:fs").writeFileSync("should-not-run.txt","bad");'),/quota attachment test failure/);assert.equal(fs.existsSync(path.join(root,'should-not-run.txt')),false);}finally{memory.attach=attach;}});
 await check('Executable identity mismatch prevents project code before quota attachment',async()=>{const attach=memory.attach;memory.attach=(pid,excluded)=>attach(pid,excluded,require('../../deploy/core/revival-runtime-paths.cjs').powershell());try{await assert.rejects(()=>run('require("node:fs").writeFileSync("wrong-image.txt","bad");'),/Target executable mismatch/);assert.equal(fs.existsSync(path.join(root,'wrong-image.txt')),false);}finally{memory.attach=attach;}});
 await check('Stop terminates a listening local server',async()=>{
  let ready;const listening=new Promise(resolve=>ready=resolve),job=node.run(101,{path:entry,source:'const server=require("node:http").createServer((req,res)=>res.end("native Node"));server.listen(0,"127.0.0.1",()=>console.log(JSON.stringify({port:server.address().port})));new Promise(()=>{});'},event=>{try{const data=JSON.parse(event.text.trim());if(data.port)ready(data.port);}catch(_){}}).then(result=>({result}),error=>({error}));
  const port=await Promise.race([listening,new Promise((_,reject)=>setTimeout(()=>reject(Error('Server did not listen')),3000))]);assert.equal(await (await fetch('http://127.0.0.1:'+port)).text(),'native Node');await node.cancel(101);assert.match((await job).error.message,/cancelled/);await assert.rejects(()=>fetch('http://127.0.0.1:'+port));
 });
 await check('Stop terminates detached child processes inherited by the quota job',async()=>{
  let ready;const started=new Promise(resolve=>ready=resolve),job=node.run(101,{path:entry,source:'const child=require("node:child_process").spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{detached:true,stdio:"ignore",windowsHide:true});child.unref();console.log(JSON.stringify({child:child.pid}));new Promise(()=>{});'},event=>{try{const data=JSON.parse(event.text.trim());if(data.child)ready(data.child);}catch(_){}}).then(result=>({result}),error=>({error}));
  const pid=await Promise.race([started,new Promise((_,reject)=>setTimeout(()=>reject(Error('Child did not start')),3000))]);await node.cancel(101);await job;assert.throws(()=>process.kill(pid,0),error=>error.code==='ESRCH');
 });
 await check('Native Buffer growth is terminated within the hard commit quota',async()=>{await assert.rejects(()=>run('const values=[];while(true)values.push(Buffer.alloc(8*1024*1024,1));'));const last=node.diagnostics().recent.at(-1);assert.equal(last.memory.hardPrivateCommit,true);assert.equal(last.memory.processExited,true);assert.ok(last.memory.peakJobBytes<=1073741824);});
 await check('New native run supersedes an unresolved old run',async()=>{const old=run('new Promise(()=>{});').then(result=>({result}),error=>({error}));await new Promise(resolve=>setTimeout(resolve,100));const next=await run('43;');assert.equal(next.result,'43');assert.match((await old).error.message,/cancelled/);assert.equal(node.activeCount(),0);});
 await check('Native CPU loops end at the actual 30 second deadline',async()=>{await assert.rejects(()=>run('while(true){}'),/30000 ms/);assert.equal(node.activeCount(),0);});
 console.log(JSON.stringify({passed:true,checks:checks.length,runtime:node.info(),cleanup:node.diagnostics().active}));
}finally{await node.shutdown();await memory.stop();modules.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);}})().catch(error=>{console.error(error);process.exitCode=1;});
