(async()=>{
 const checks=[],root=ltProjects.info().current.path,entry=root+'\\package-entry.js';
 const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);};
 const command=(name,...args)=>lt.objs.command.exec_BANG_(cljs.core.keyword(name),...args);
 const open=file=>{command('open-path',file);return ltProofUI.connect();};
 const cm=open(entry),run=async source=>{cm.setValue(source);ltProofUI.refreshMenus(true);for(let i=0;i<50&&!testMenuItem('Run file')?.enabled;i++)await new Promise(resolve=>setTimeout(resolve,10));testMenuClick('Run file');return ltProofUI.pending();};
 let result=await run('import value from "dual";value;');
 check('Normal Run resolves installed ESM packages',result.accepted&&result.result.result==='42');
 result=await run('require("dual");');check('Normal Run resolves CommonJS package conditions',result.accepted&&result.result.result==='43');
 const initialHash=result.result.project.sha256,initialSourceHash=result.result.sha256;
 const actual='import {parse} from "acorn";\nimport meta from "acorn/package.json";\nconst parsed=parse("const answer = 42;", {ecmaVersion:"latest"});\n({library:meta.name,version:meta.version,answer:parsed.body[0].declarations[0].init.value});';
 result=await run(actual);const report=JSON.parse(result.result?.result||'null');
 check('Real Acorn package runs through the editor sandbox',result.accepted&&report.answer===42&&report.version==='8.18.0');
 check('Large package retains verified hard memory quota',result.result.memory.hardPrivateCommit&&result.result.memory.limitBytes===1073741824&&result.result.memory.processExited);
 check('Package versions appear in the Activity snapshot',document.getElementById('proof-package-versions').textContent.includes('acorn @ 8.18.0'));
 const graph=document.getElementById('proof-project-snapshot');graph.open=true;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 check('Package metadata fits the Activity panel width',graph.scrollWidth<=graph.clientWidth+1);
 check('Package sources are retained without filling the panel eagerly',result.result.project.modules.some(item=>item.name.endsWith('acorn.mjs')&&item.source.length>16384)&&document.getElementById('proof-project-snapshot').textContent.length<10000);
 const detail=[...document.querySelectorAll('#proof-project-snapshot details')].find(item=>item.firstChild.textContent.includes('acorn.mjs'));detail.open=true;await new Promise(resolve=>setTimeout(resolve,30));
 check('Opening a captured package source reveals exact source and hash',detail.querySelector('pre').textContent.includes(result.result.project.modules.find(item=>item.name.endsWith('acorn.mjs')).sha256));
 open(root+'\\node_modules\\acorn\\dist\\acorn.mjs');open(entry);result=await run('require("acorn").parse("42",{ecmaVersion:"latest"}).body[0].expression.value;');
 check('Opening an unchanged large library does not exhaust editor buffer budget',result.accepted&&result.result.result==='42');
 result=await run('require("@lt/math").answer;');check('Scoped packages run through normal Run',result.accepted&&result.result.result==='45');
 result=await run('import value from "dual/features/answer";value;');check('Exported subpaths run through normal Run',result.accepted&&result.result.result==='44');
 result=await run('require("outer");');check('Nested dependency resolves its own installed version',result.accepted&&result.result.result==='48');
 result=await run('require("browser-map");');check('Browser-compatible package entry is used',result.accepted&&result.result.result==='50');
 result=await run('require("dual");');const file=root+'\\node_modules\\dual\\index.cjs',packageEditor=open(file);packageEditor.setValue('/*'+'x'.repeat(20000)+'*/module.exports=60;');open(entry);
 check('Unsaved installed package edit marks the entry stale',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runJavaScript();check('Large unsaved package source executes without writing disk',result.accepted&&result.result.result==='60'&&ltProof.read(file)==='module.exports=43;');
 packageEditor.setValue('module.exports=43;');const manifest=root+'\\node_modules\\dual\\package.json',manifestEditor=open(manifest),metadata=JSON.parse(manifestEditor.getValue());metadata.version='1.1.0';manifestEditor.setValue(JSON.stringify(metadata));open(entry);
 result=await ltProofUI.runJavaScript();check('Unsaved package metadata asks to save instead of mislabeling the result',result.reason==='error'&&result.error.includes('Save package.json'));
 open(manifest);command('save');open(entry);result=await ltProofUI.runJavaScript();
 check('Saved version edit is visible while entry source stays unchanged',result.accepted&&result.result.project.packages.find(item=>item.name==='dual').version==='1.1.0'&&result.result.sha256===initialSourceHash&&result.result.project.sha256!==initialHash);
 result=await run('require("outer");');const outerManifest=root+'\\node_modules\\outer\\package.json',outerMeta=JSON.parse(ltProof.read(outerManifest));outerMeta.version='1.2.0';ltProof.write(outerManifest,JSON.stringify(outerMeta));await new Promise(resolve=>setTimeout(resolve,1200));
 check('External manifest edit makes the result stale',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runJavaScript();check('Rerun captures the externally changed package version',result.accepted&&result.result.project.packages.find(item=>item.name==='outer').version==='1.2.0');
 const nested=root+'\\node_modules\\outer\\node_modules\\leaf\\index.cjs';ltProof.write(nested,'module.exports=61;');await new Promise(resolve=>setTimeout(resolve,1200));
 check('External installed source edit makes the result stale',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runJavaScript();check('Fresh run uses externally edited package source',result.accepted&&result.result.result==='61');
 result=await run('require("consumer");');check('Package uses the project dependency before a nearer install',result.accepted&&result.result.result==='47');
 const nearer=root+'\\node_modules\\consumer\\node_modules\\leaf';ltProof.mkdir(nearer);ltProof.write(nearer+'\\package.json',JSON.stringify({name:'leaf',version:'3.0.0',main:'index.cjs'}));ltProof.write(nearer+'\\index.cjs','module.exports=54;');await new Promise(resolve=>setTimeout(resolve,1200));
 check('Installing a nearer dependency invalidates the previous result',document.getElementById('proof-output').dataset.status==='stale');
 result=await ltProofUI.runJavaScript();check('Rerun uses the newly installed dependency and version',result.accepted&&result.result.result==='54'&&result.result.project.packages.some(item=>item.name==='leaf'&&item.version==='3.0.0'));
 result=await run('require("throws")();');check('Package runtime errors map to the installed source',result.reason==='error'&&result.location?.path===root+'\\node_modules\\throws\\index.cjs'&&result.location.line===2);
 document.getElementById('proof-error-open').click();check('Package error link opens the captured line',ltProofUI.connect().getCursor().line===1&&document.getElementById('proof-versions').textContent.includes('index.cjs'));open(entry);
 result=await run('require("missing-library");');check('Missing installed package has an actionable error',result.reason==='error'&&result.error.includes('Package not installed in this project'));
 result=await run('require("node:fs");');check('Node builtins stay unavailable through the package loader',result.reason==='error'&&result.error.includes('Node import is unavailable'));
 result=await run('require("hang");');check('Infinite package loop is terminated by the run budget',result.reason==='error'&&result.error.includes('1500 ms'));
 cm.setValue('require("dual");new Promise(()=>{});');const stopped=ltProofUI.runJavaScript();await new Promise(resolve=>setTimeout(resolve,150));testMenuClick('Stop');result=await stopped;
 check('Menu Stop cancels a package run and restores the editor',!result.accepted&&document.getElementById('proof-output').dataset.status==='cancelled');
 result=await run('import {parse} from "acorn";[typeof process,typeof fetch,typeof Worker,parse("42",{ecmaVersion:"latest"}).body.length];');
 check('Installed code retains the restricted execution capabilities',result.accepted&&result.result.result==='["undefined","undefined","undefined",1]');
 cm.setValue(actual);command('save');result=await ltProofUI.runJavaScript();
 check('Package error recovery ends with a current real-library result',result.accepted&&JSON.parse(result.result.result).answer===42&&document.getElementById('proof-output').dataset.status==='current');
 check('Activity remains free of action buttons',document.querySelectorAll('#proof-calculation button').length===0);
 return {passed:true,checks,result:result.result};
})()
