'use strict';
process.env.LT_REVIVAL_TEST='1';
const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const policy=require('../../deploy/core/proof-policy.cjs'),projects=require('../../deploy/core/revival-projects.cjs'),preview=require('../../deploy/core/revival-preview.cjs'),memory=require('../../deploy/core/proof-memory.cjs');
const root=path.join(policy.root,'preview-fixtures',crypto.randomUUID());fs.mkdirSync(root,{recursive:true});projects.activate(root);
const write=(file,source)=>fs.writeFileSync(path.join(root,file),source),entry=path.join(root,'index.html');
const html='<!doctype html>\n<meta charset="utf-8">\n<title>Orders preview</title>\n<link rel="stylesheet" href="./style.css">\n<main><h1>Order report</h1><button id="total">Calculate revenue</button><output id="revenue">Ready</output></main>\n<script src="./app.js"></script>\n<script type="module" src="./module.mjs"></script>';
write('index.html',html);write('app.js','var prices=[12,30];\ndocument.getElementById("total").onclick=()=>document.getElementById("revenue").textContent=prices.reduce((a,b)=>a+b,0);\nconsole.log("DOM app ready");');
write('module.mjs','import {label} from "./label.mjs";globalThis.moduleLabel=label;');write('label.mjs','export const label="saved module";');
write('style.css','body { background: #10271f; color: #d9ede2; font: 18px system-ui; padding: 40px; } button { padding: 14px; } output { margin-left: 24px; }');write('orders.json','{"revenue":129}');write('input.bin',Buffer.from([0,255,42]));
const checks=[],events=[],captures=[];let host;
function check(label,fn){return Promise.resolve().then(fn).then(()=>{checks.push(label);console.log(label);fs.writeFileSync(path.join(policy.root,'preview-progress.json'),JSON.stringify({checks,pid:process.pid}));});}
const start=(file='index.html',buffers=[])=>preview.start(1,{path:path.join(root,file),buffers},host,event=>events.push(event));
const evaluate=(code,opts)=>preview.evaluate(1,code,opts);
const raw=()=>preview.view(1).webContents;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
// Retry only the hidden-view bitmap observation after a compositor resize.
// The same renderer stays live and all DOM/runtime assertions remain intact.
const capture=async()=>{for(let attempt=1;attempt<=3;attempt++){try{const pixels=await raw().capturePage();assert(!pixels.isEmpty(),'Empty actual preview screenshot');fs.writeFileSync(path.join(policy.root,'preview-report.png'),pixels.toPNG());captures.push({name:'preview-report.png',attempt});return;}catch(error){if(!error.message.includes('UnknownVizError')||attempt===3)throw error;await sleep(150);}}};
const deadline=setTimeout(()=>app.exit(2),100000);
app.whenReady().then(async()=>{
 let result;try{
  host=new BrowserWindow({show:false,width:1000,height:700,opacity:0,skipTaskbar:true,webPreferences:{sandbox:true,nodeIntegration:false,contextIsolation:true,backgroundThrottling:false}});host.showInactive();await host.loadURL('data:text/html,<title>Preview test host</title>');
  let initial;
  await check('Real HTML scripts and relative ES modules execute in the preview',async()=>{initial=await start('index.html',[{path:path.join(root,'label.mjs'),source:'export const label="unsaved module";'}]);assert.equal((await evaluate('moduleLabel')).result,'"unsaved module"');assert.equal(initial.status,'running');});
  await check('Project DOM events and CSS render in the actual browser view',async()=>{assert.equal((await evaluate('document.getElementById("total").click();document.getElementById("revenue").textContent')).result,'"42"');assert.equal((await evaluate('getComputedStyle(document.body).backgroundColor')).result,'"rgb(16, 39, 31)"');preview.bounds(1,{x:0,y:0,width:980,height:660,visible:true});await sleep(100);await capture();});
  await check('The preview quota is verified on a renderer separate from its host',()=>{assert.equal(initial.memory.limitBytes,1024*1024*1024);assert.equal(initial.memory.hardPrivateCommit,true);assert.notEqual(initial.rendererPid,host.webContents.getOSProcessId());const prefs=raw().getLastWebPreferences();assert.equal(prefs.sandbox,true);assert.equal(prefs.nodeIntegration,false);assert.equal(prefs.contextIsolation,true);});
  await check('Current source snapshots include HTML, CSS, classic scripts and unsaved ES modules',()=>{const sources=preview.status(1).project.files;for(const name of ['index.html','style.css','app.js','module.mjs','label.mjs'])assert(sources.some(s=>s.name===name));const module=sources.find(s=>s.name==='label.mjs');assert.equal(module.origin,'editor');assert.equal(module.source,'export const label="unsaved module";');assert.equal(fs.readFileSync(path.join(root,'label.mjs'),'utf8'),'export const label="saved module";');});
  await check('Browser selection can use existing page globals and await timers',async()=>{assert.equal((await evaluate('new Promise(resolve=>setTimeout(()=>resolve(prices[0]+30),20))')).result,'42');});
  await check('Readonly project fetches track exact JSON and binary inputs',async()=>{assert.equal((await evaluate('fetch("./orders.json").then(r=>r.json()).then(v=>v.revenue)')).result,'129');assert.equal((await evaluate('fetch("./input.bin").then(r=>r.arrayBuffer()).then(b=>[...new Uint8Array(b)])')).result,'[0,255,42]');const binary=preview.status(1).project.files.find(s=>s.name==='input.bin');assert.equal(binary.source,null);assert.equal(binary.sha256,crypto.createHash('sha256').update(Buffer.from([0,255,42])).digest('hex'));});
  await check('Missing project resources are captured for later stale checks',async()=>{assert.equal((await evaluate('fetch("./missing.json").then(r=>r.status)')).result,'404');assert.equal(preview.status(1).project.files.find(s=>s.name==='missing.json').exists,false);});
  await check('Preview code has no Node, editor preload or application bridge',async()=>{assert.equal((await evaluate('[typeof process,typeof require,typeof ltProof,typeof ltBrowserPreview]')).result,'["undefined","undefined","undefined","undefined"]');});
  await check('External network, host file reads, nested frames and workers are blocked',async()=>{assert.equal((await evaluate('fetch("https://example.com/").then(()=>false,()=>true)')).result,'true');assert.equal((await evaluate('fetch("file:///C:/Windows/win.ini").then(()=>false,()=>true)')).result,'true');assert.equal((await evaluate('new Promise(resolve=>{const worker=new Worker("./app.js");worker.onerror=()=>resolve(true);setTimeout(()=>resolve(false),50);})')).result,'true');assert.equal((await evaluate('new Promise(resolve=>{const iframe=document.createElement("iframe");iframe.src="./index.html";document.body.append(iframe);setTimeout(()=>resolve(!iframe.contentDocument?.getElementById("total")),50);})')).result,'true');});
  await check('Browser runtime errors retain the original project line and column',async()=>{await assert.rejects(evaluate('throw new Error("selection failed")',{path:path.join(root,'app.js'),lineOffset:1,columnOffset:2}),error=>{console.log('selection error location',JSON.stringify(error.location));return error.location?.path===path.join(root,'app.js')&&error.location.line===2&&error.location.column>=3;});});
  await check('Selection errors identify the current unsaved buffer independently of the loaded page',async()=>{const buffer='var old=42;\n  throw new Error("current selection failed");';await assert.rejects(evaluate('throw new Error("current selection failed");',{path:path.join(root,'app.js'),lineOffset:1,columnOffset:2,bufferSource:buffer}),error=>error.location.source===buffer&&error.location.sourceLine==='  throw new Error("current selection failed");'&&error.location.line===2);assert.equal(preview.status(1).project.files.find(item=>item.name==='app.js').source.includes('var prices=[12,30]'),true);});
  await check('Browser errors recover and results remain bounded',async()=>{assert.equal((await evaluate('40+3')).result,'43');await assert.rejects(evaluate('"x".repeat(20000)'),/result exceeds 16 KiB/);assert.equal((await evaluate('42')).result,'42');});
  await check('Stop closes the browser process and releases its quota',async()=>{const stopped=await preview.stop(1);assert.equal(stopped.memory.processExited,true);assert.equal(preview.activeCount(),0);assert.equal(memory.status().jobs,0);});
  await check('Unsaved HTML, CSS and classic JavaScript are used on refresh',async()=>{await start('index.html',[{path:entry,source:html.replace('Order report','Current HTML')},{path:path.join(root,'style.css'),source:'body{background:rgb(1,2,3)}'},{path:path.join(root,'app.js'),source:'var prices=[13,30];document.getElementById("revenue").textContent=prices.reduce((a,b)=>a+b,0);'}]);assert.equal((await evaluate('[document.querySelector("h1").textContent,document.querySelector("output").textContent,getComputedStyle(document.body).backgroundColor]')).result,'["Current HTML","43","rgb(1, 2, 3)"]');});
  await check('Navigation cannot move the preview to another renderer or host URL',async()=>{const old=raw().getURL(),pid=raw().getOSProcessId();await evaluate('location.href="https://example.com/";42');await sleep(50);assert.equal(raw().getURL(),old);assert.equal(raw().getOSProcessId(),pid);});
  await check('Opening a JavaScript file provides a real DOM context',async()=>{write('standalone.js','document.body.textContent="JS preview";globalThis.answer=42;');await start('standalone.js');assert.equal((await evaluate('[document.body.textContent,answer]')).result,'["JS preview",42]');});
  await check('An initial inline CPU loop is stopped by the loading deadline',async()=>{write('loop.html','<script>while(true){}</script>');await assert.rejects(start('loop.html'),/1500 ms|terminated|closed|detached/);assert.equal(memory.status().jobs,0);});
  await check('An unresolved browser Promise is stopped and its quota is released',async()=>{await start();await assert.rejects(evaluate('new Promise(()=>{})'),/1500 ms|terminated|closed|detached/);assert.equal(preview.activeCount(),0);assert.equal(memory.status().jobs,0);});
  await check('Actual Stop cancels an active browser evaluation',async()=>{await start();const running=evaluate('new Promise(resolve=>setTimeout(()=>resolve(42),1000))');const observed=running.catch(error=>error);await sleep(50);const stopped=await preview.stop(1);assert((await observed) instanceof Error);assert.equal(stopped.memory.processExited,true);});
  await check('A browser CPU loop cannot block the editor or retain the job',async()=>{await start();await assert.rejects(evaluate('while(true){}'),/1500 ms|terminated|closed|detached|timed out/);assert.equal(preview.activeCount(),0);assert.equal(memory.status().jobs,0);});
  await check('Quota failure during page startup is visible and later previews recover',async()=>{write('memory.html','<script>globalThis.big=new Uint8Array(1536*1024*1024);</script>');let failed=false;try{const loaded=await start('memory.html');failed=loaded.errors.some(error=>/allocation|memory|Array buffer/i.test(error.message));}catch(error){failed=/memory|terminated|closed|detached/i.test(error.message);}assert(failed);await start();assert.equal((await evaluate('21*2')).result,'42');});
  await check('Concurrent preview replacement leaves only the newest renderer',async()=>{const previous=start(),newest=start();await assert.rejects(previous,/replaced/);await newest;assert.equal(preview.activeCount(),1);assert.equal(memory.status().jobs,1);});
  await check('Interactive preview expires at its finite 30-second lifetime',async()=>{await start();await sleep(31000);assert.equal(preview.activeCount(),0);assert.equal(memory.status().jobs,0);assert.match(events.at(-1).reason,/30000 ms/);});
  result={passed:true,checks,captures,events:events.map(({kind,status,rendererPid})=>({kind,status,rendererPid}))};
 }catch(error){result={passed:false,checks,error:error.stack};console.error(error);}
 await preview.shutdown();result.diagnostics=preview.diagnostics();await memory.stop();if(host&&!host.isDestroyed())host.destroy();result.cleanup={active:preview.activeCount(),...memory.status()};result.passed=result.passed&&result.cleanup.active===0&&result.cleanup.jobs===0&&result.cleanup.pending===0&&!result.cleanup.helperPid;
 fs.writeFileSync(path.join(policy.root,'preview-result.json'),JSON.stringify(result,null,2));clearTimeout(deadline);app.exit(result.passed?0:1);
}).catch(error=>{console.error(error);app.exit(1);});
