(async()=>{
 const checks=[];const check=(name,ok)=>{if(!ok)throw Error(name);checks.push(name);console.info('Revival project check: '+name);};
 const click=id=>document.getElementById(id).click();
 const name=(dialog,value)=>{document.getElementById(dialog+'-name').value=value;};
 const active=()=>ltProofUI.connect();
 const treeFile=path=>lt.objs.sidebar.workspace.find_by_path(path);
 testMenuClick('New project...');name('project-create','working-project');click('project-choose-location');
 document.getElementById('project-start-type').value='js';document.getElementById('project-start-type').dispatchEvent(new Event('change',{bubbles:true}));
 check('New project asks for a location',document.getElementById('project-location').textContent===window.testProjectParent);
 click('project-create-submit');
 const project=ltProjects.info().current,index=project.path+'\\index.js';
 check('Created folder is the active project: '+(document.querySelector('#project-create .project-form-error')?.textContent||''),project.name==='working-project'&&!document.getElementById('project-create')?.open);
 check('Original workspace tree contains only the chosen starting file',!!treeFile(index)&&!treeFile(project.path+'\\README.md')&&!treeFile(project.path+'\\package.json')&&!treeFile(project.path+'\\totals.cjs')&&!treeFile(project.path+'\\totals.test.cjs'));
 check('Blank JavaScript starting file opened in the original editor',active().getValue()===''&&document.getElementById('proof-versions').textContent.includes('index.js'));
 active().setValue('const prices = [12, 30];\nconsole.log("Project is running");\n({total: prices.reduce((sum, n) => sum + n, 0), itemCount: prices.length});');testMenuClick('Save file');
 let run=await ltProofUI.runJavaScript();check('Single-file project runs with real output and console',run.accepted&&JSON.parse(run.result.result).total===42&&run.result.logs[0]==='log: Project is running');
 active().setValue(active().getValue().replace('[12, 30]','[12, 31]'));testMenuClick('Save file');run=await ltProofUI.runJavaScript();
 check('Edited project code saves and runs',run.accepted&&JSON.parse(run.result.result).total===43&&ltProof.read(index).includes('[12, 31]'));
 testMenuClick('New file in project...');name('project-file','report.js');click('project-file-submit');
 const report=project.path+'\\report.js';
 check('New project file appears in original tree and editor',!!treeFile(report)&&active().getValue()===''&&document.getElementById('proof-versions').textContent.includes('report.js'));
 active().setValue('const values = [20, 23];\nvalues.reduce((sum, n) => sum + n, 0);');testMenuClick('Save file');run=await ltProofUI.runJavaScript();
 check('Second file can be edited, saved and run',run.accepted&&run.result.result==='43'&&ltProof.read(report).includes('[20, 23]'));
 testMenuClick('New file in project...');name('project-file','report.js');click('project-file-submit');
 check('Duplicate file shows an error and keeps code',document.querySelector('#project-file .project-form-error').textContent.includes('already exists')&&ltProof.read(report).includes('[20, 23]'));click('project-file-cancel');
 const file=treeFile(index);lt.object.__GT_content(file).querySelector('p').click();active();
 check('Tree file click switches the original editor buffer',active().getValue().includes('[12, 31]'));
 ltProof.write(project.path+'\\external.js','40+2');
 check('A file written outside the editor awaits refresh',!treeFile(project.path+'\\external.js'));
 testMenuClick('Refresh project files');check('Refresh reloads external files into the tree',!!treeFile(project.path+'\\external.js'));
 testMenuClick('New project...');name('project-create','working-project');click('project-choose-location');click('project-create-submit');
 check('Duplicate project shows actionable error',document.querySelector('#project-create .project-form-error').textContent.includes('already exists'));click('project-create-cancel');
 testMenuClick('Open project...');const other=ltProjects.info().current;
 check('Open project uses the chosen existing folder',other.name==='existing-project'&&active().getValue().trim()==='17');
 run=await ltProofUI.runJavaScript();check('Existing project runs without scaffolding overwrite',run.accepted&&run.result.result==='17');
 testMenuClick(project.name+' ('+project.path+')');
 check('Recent project reopening restores its tree and saved code',ltProjects.info().current.path===project.path&&active().getValue().includes('[12, 31]'));
 run=await ltProofUI.runJavaScript();check('Reopened project still runs saved version',run.accepted&&JSON.parse(run.result.result).total===43);
 check('Project menus keep the renderer sandboxed',typeof require==='undefined'&&typeof ltProjectFiles.create==='function');
 check('Right panel contains project context without action buttons',document.getElementById('project-name').textContent==='working-project'&&document.querySelectorAll('#proof-calculation button, #proof-calculation select').length===0);
 return {passed:true,checks,project:project.path,index,report,result:run.result};
})()
