'use strict';
process.env.LT_REVIVAL_TEST='1';process.env.LT_REVIVAL_AUTO_LIVE='0';
const {app}=require('electron'),fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const core=path.resolve(__dirname,'../../deploy/core'),policy=require(core+'/proof-policy.cjs'),projects=require(core+'/revival-projects.cjs');
const focusedVerification=process.env.LT_REVIEWER_VERIFICATION_PROOF==='1',migratedProfile=process.env.LT_REVIEWER_PROFILE_PROOF==='1',profile=require(core+'/revival-assistant-profile.cjs');
const profileTemp=migratedProfile?fs.mkdtempSync(path.join(require('node:os').tmpdir(),'lt-reviewer-native-profile-')):null;
if(migratedProfile){const directory=profile.directory;profile.directory=legacy=>directory(legacy,{test:false,localAppData:profileTemp});}
const evidenceName=focusedVerification?'reviewer-verification-native':migratedProfile?'reviewer-profile-native':'reviewer-native';
const base=path.join(policy.root,'reviewer-native-fixtures'),root=path.join(base,crypto.randomUUID()),html=path.join(root,'index.html');fs.mkdirSync(root,{recursive:true});
const initial='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:16px;font:16px Arial}.wide{width:700px}</style><h1>Counter</h1><div class="wide">Content</div><button id="increment" onclick="document.getElementById(\'count\').textContent=Number(document.getElementById(\'count\').textContent)+1">Increment</button><output id="count">0</output><p style="margin-top:1200px">Footer</p>';
fs.writeFileSync(html,initial);fs.writeFileSync(path.join(root,'package.json'),JSON.stringify({scripts:{test:'node --test counter.test.cjs'}}));fs.writeFileSync(path.join(root,'counter.test.cjs'),"require('node:test')('responsive source',()=>require('node:assert/strict').match(require('node:fs').readFileSync('index.html','utf8'),/width:100%/));");
function tree(dir){const result=new Map();if(!fs.existsSync(dir))return result;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);assert(!entry.isSymbolicLink());if(entry.isDirectory())for(const item of tree(file))result.set(...item);else result.set(file,fs.readFileSync(file));}return result;}
const originalProject=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null,cacheDir=profile.directory(path.join(policy.user,'assistant')),saved=tree(cacheDir),ltcache=path.join(policy.user,'ltcache'),savedCache=tree(ltcache);
// Start with an empty test workspace; restore the exact cached workspace in finish.
const workspace=path.join(ltcache,"workspace");for(const file of savedCache.keys())if(path.dirname(file)===workspace&&path.extname(file)===".clj")fs.unlinkSync(file);projects.activate(root);
const result={passed:false,checks:[],requests:[]};let host,backend,ending=false,step=0,uncertain=false;
const choice=(q,value)=>({type:'choice',choice:value,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===value?1:0]))});
require(core+'/revival-assistant-ollama.cjs').create=()=>({models:async()=>[{name:'coder-fixture',digest:'coder'},{name:'text-reviewer',digest:'text'},{name:'image-reviewer',digest:'image'}],show:async m=>({capabilities:m==='coder-fixture'?['tools']:['decision',...(m==='image-reviewer'?['vision']:[])]}),unload:async()=>{},processes:async()=>[],decision:async body=>{
 const v=body.state.current,category=uncertain?'uncertain':v.overflow?'overflow':v.clipped.length?'clipping':v.controls.some(e=>e.id==='increment'&&e.visible)&&v.controls.some(e=>e.id==='count'&&e.visible)?'clean':'missing_control';
 result.requests.push({model:body.model,images:body.images?.length||0,viewport:v.name,bytes:Buffer.byteLength(JSON.stringify(body))});if(body.model==='image-reviewer'){assert(body.images.length>0);for(const image of body.images)assert(Buffer.from(image,'base64').subarray(1,4).equals(Buffer.from('PNG')));}else assert(!body.images);
 if(focusedVerification&&body.state.acceptance?.length){assert(body.state.controls?.every(c=>c.passed));assert(body.state.tests.passed);assert(body.state.behavior.some(c=>c.checkId==='increment-action'));}const insufficient=/No interaction checks were performed|requirements have not been supplied/.test(body.state.criterion);
 return {model:body.model,answers:{category:choice(body.questions.category,category),requirement:choice(body.questions.requirement,insufficient?'uncertain':category==='clean'?'met':category==='uncertain'?'uncertain':'unmet')}};
},chat:async()=>{
 const actions=[...(focusedVerification?[{name:'set_review_criteria',arguments:{checks:[{id:'increment-control',kind:'control',selector:'#increment',description:'Increment is visible'},{id:'count-control',kind:'control',selector:'#count',description:'Count is visible'},{id:'increment-action',kind:'behavior',description:'Clicking Increment increases the count by one'},{id:'source-tests',kind:'test',description:'Counter source tests pass'}]}}]:[]),{name:'read_file',arguments:{path:html}},{name:'edit_file',arguments:{path:html,old_text:'width:700px',new_text:'width:100%;max-width:100%'}},{name:'run_command',arguments:{command:'node --test counter.test.cjs',cwd:root,purpose:'test'}},{name:'start_preview',arguments:{path:html}},...['desktop','mobile'].map(viewport=>({name:'check_preview',arguments:{...(focusedVerification?{check_id:'increment-action'}:{}),viewport,label:'Increment updates the visible count',source:'(()=>{const count=document.getElementById("count"),before=Number(count.textContent);document.getElementById("increment").click();return {passed:Number(count.textContent)===before+1,details:"Increment click updates count at "+innerWidth+" pixels"};})()'}}))];
 return step<actions.length?{message:{role:'assistant',tool_calls:[{function:actions[step++]}]}}:{message:{role:'assistant',content:'Fixed responsive width and verified Node tests.'}};
}});
const deadline=setTimeout(()=>finish(Error('Reviewer native proof exceeded six minutes')),360000),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function finish(error){if(ending)return;ending=true;clearTimeout(deadline);if(error){result.error=error.stack;result.runtime=backend?.assistant.runtime.state();result.failureSession=result.runtime?.sessionId?backend.assistant.store.load(result.runtime.sessionId):null;result.failedPreview=host?require(core+'/revival-preview.cjs').status('assistant:'+host.webContents.id):null;fs.writeFileSync(path.join(policy.root,evidenceName+'-progress.json'),JSON.stringify(result,null,2));console.error(error);}try{await backend.assistant.shutdown();await require(core+'/revival-preview.cjs').shutdown();await require(core+'/proof-memory.cjs').stop();if(originalProject)fs.writeFileSync(projects.statePath,originalProject);else fs.rmSync(projects.statePath,{force:true});for(const [dir,snapshot]of [[cacheDir,saved],[ltcache,savedCache]]){for(const file of tree(dir).keys())if(!snapshot.has(file))fs.unlinkSync(file);for(const [file,bytes]of snapshot){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes);}}assert.equal(path.dirname(path.resolve(root)),path.resolve(base));fs.rmSync(root,{recursive:true});if(profileTemp){const resolved=fs.realpathSync(profileTemp);assert.equal(path.dirname(resolved),fs.realpathSync(require('node:os').tmpdir()));assert(path.basename(resolved).startsWith('lt-reviewer-native-profile-'));fs.rmSync(resolved,{recursive:true});}result.cleanup={profileTempRemoved:!profileTemp||!fs.existsSync(profileTemp),...backend.assistant.diagnostics(),...require(core+'/proof-memory.cjs').status()};assert.equal(result.cleanup.active,0);assert.equal(result.cleanup.jobs,0);assert.equal(result.cleanup.views,0);assert(!result.cleanup.helperPid);result.passed=!error;}catch(e){result.cleanupError=e.stack;}fs.writeFileSync(path.join(policy.root,evidenceName+'-result.json'),JSON.stringify(result,null,2));app.exit(result.passed?0:1);}
app.on('browser-window-created',(_event,window)=>{if(host)return;host=window;host.setSkipTaskbar(true);host.showInactive();host.webContents.once('did-finish-load',()=>setTimeout(async()=>{const ui=s=>host.webContents.executeJavaScript(s),until=async(fn)=>{const end=Date.now()+180000;while(!await fn()){if(Date.now()>end)throw Error('Native reviewer condition timed out');await sleep(25);}},check=async(name,fn)=>{await fn();result.checks.push(name);fs.writeFileSync(path.join(policy.root,evidenceName+'-progress.json'),JSON.stringify(result,null,2));console.error(name);};try{
 host.unmaximize();host.setBounds({x:20,y:20,width:1440,height:1000});host.show();host.moveTop();host.focus();await until(()=>ui('!!document.getElementById("assistant-dock")'));await ui('ltProjects.openedFolder('+JSON.stringify(projects.info().current)+');ltAssistantUI.show("chat",false);ltAssistantUI.action("models")');const session=backend.assistant.store.conversation(root);await ui('ltAssistantUI.load('+JSON.stringify(session)+')');const run={owner:host.webContents.id,session,abort:new AbortController()};backend.assistant.runtime.settings({model:'coder-fixture',reviewerModel:'text-reviewer'});await ui('ltReviewerUI.apply('+JSON.stringify(backend.assistant.runtime.settings())+')');console.error('Starting the native preview');await backend.assistant.preview.start(run,{path:html});console.error('Native preview ready');
 await check('Native automatic review discovers independent text and image models without a selector',async()=>{await ui('ltReviewerUI.refresh()');assert(await ui('ltReviewerUI.refresh().then(models=>models.some(m=>m.mode==="Text + images"))'));assert(await ui('document.querySelectorAll("#assistant-preview-pane button").length===1&&!document.querySelector(".reviewer-toolbar")'));assert.equal(backend.assistant.runtime.settings().model,'coder-fixture');});
 await check('Desktop and mobile evidence records actual sizes and restores the original viewport and scroll',async()=>{const preview=require(core+'/revival-preview.cjs'),wc=preview.view('assistant:'+run.owner).webContents;const before=await wc.executeJavaScript('scrollTo(0,200);({width:innerWidth,height:innerHeight,scroll:scrollY})');const e=await backend.assistant.preview.evidence(run,{images:true,signal:run.abort.signal,checks:[{id:'required-increment',selector:'#increment'},{id:'missing-control',selector:'#not-present'}]});assert(e.viewports.every(v=>v.dom.requiredControls.find(c=>c.id==='required-increment').passed&&!v.dom.requiredControls.find(c=>c.id==='missing-control').passed));assert.equal(e.viewports[0].dom.width,1280);assert.equal(e.viewports[1].dom.width,390);assert(!e.viewports[0].dom.overflow);assert(e.viewports[1].dom.overflow);assert(e.viewports.every(v=>v.performance.frames>5));const after=await wc.executeJavaScript('({width:innerWidth,height:innerHeight,scroll:scrollY})');assert.deepEqual(after,before);const {nativeImage}=require('electron');assert.equal(nativeImage.createFromBuffer(Buffer.from(e.images[0],'base64')).getSize().width,1280);assert.equal(nativeImage.createFromBuffer(Buffer.from(e.images[1],'base64')).getSize().width,390);result.viewportSamples=e.viewports.map(v=>({name:v.name,performance:v.performance}));e.images.length=0;const hidden=await backend.assistant.preview.fixture(run,initial.replace('<button id=','<div style="opacity:0"><button id=').replace('</button>','</button></div>'),{images:false,sampleMs:100});assert(hidden.viewports.every(v=>v.dom.elements.find(e=>e.id==='increment')?.visible===false));});
 await check('Manual text review uses the native UI and never persists screenshots',async()=>{await ui('ltReviewerUI.run("review")');await until(()=>!backend.assistant.runtime.activeCount());assert.equal(backend.assistant.runtime.state().status,'completed');const saved=backend.assistant.store.load(session.id);assert(saved.reviewReports.at(-1).findings.some(f=>f.category==='overflow'));assert(!saved.reviewReports.at(-1).imageReviewCompleted);assert(!JSON.stringify(saved).includes('iVBOR'));});
 await check('Image reviewer receives actual native PNG captures while report storage stays image-free',async()=>{backend.assistant.runtime.settings({reviewerModel:'image-reviewer'});await backend.assistant.runtime.review(run.owner,{sessionId:session.id});await until(()=>!backend.assistant.runtime.activeCount());assert(backend.assistant.store.load(session.id).reviewReports.at(-1).imageReviewCompleted);assert(!JSON.stringify(backend.assistant.store.load(session.id)).includes('iVBOR'));});
 await check('Stop during sampling restores the borrowed manual preview without closing it',async()=>{await backend.assistant.preview.stop(run);await ui('ltPreview.openLive('+JSON.stringify(html)+',900000)');const preview=require(core+'/revival-preview.cjs'),wc=preview.view(run.owner).webContents,before=await wc.executeJavaScript('({width:innerWidth,height:innerHeight})');await backend.assistant.runtime.review(run.owner,{sessionId:session.id});await sleep(1000);await backend.assistant.runtime.stop(run.owner);assert.equal(preview.view(run.owner).webContents,wc);assert.deepEqual(await wc.executeJavaScript('({width:innerWidth,height:innerHeight})'),before);await ui('ltPreview.stop(false)');await backend.assistant.preview.start(run,{path:html});});
 if(!focusedVerification)await check('Twelve native fixed cases and three full measurement cycles gate reviewer qualification',async()=>{backend.assistant.runtime.settings({reviewerModel:'text-reviewer'});await backend.assistant.runtime.review(run.owner,{sessionId:session.id,mode:'validate'});await until(()=>!backend.assistant.runtime.activeCount());const saved=backend.assistant.store.load(session.id),receipt=saved.events.findLast(e=>e.type==='review-validation')?.receipt;assert(receipt,backend.assistant.runtime.state().reason);assert(receipt.passed,JSON.stringify(receipt.checks));assert.equal(receipt.correct,12);assert.equal(receipt.uncertaintyChecks.length,2);assert(receipt.uncertaintyChecks.every(c=>c.passed));assert.equal(receipt.cycles.length,3);});
 if(migratedProfile||focusedVerification){
 if(migratedProfile)await check('Native reviewer qualification uses the production migrated profile with no legacy fixture path',async()=>{assert(backend.assistant.store.directory.startsWith(profileTemp+path.sep));assert.notEqual(backend.assistant.store.directory,path.join(policy.user,'assistant'));});
 await check('A task sent through normal Chat declares checks, edits, tests before preview startup and completes both viewport reviews',async()=>{
  host.focus();const visible=require(core+'/revival-preview.cjs').view('assistant:'+run.owner);visible.webContents.focus();visible.webContents.setBackgroundThrottling(false);if(focusedVerification){await backend.assistant.preview.stop(run);assert(!require(core+'/revival-preview.cjs').view('assistant:'+run.owner));}step=0;
  const saved=backend.assistant.store.load(session.id);await ui('ltAssistantUI.load('+JSON.stringify(saved)+');void 0');backend.assistant.runtime.settings({reviewerModel:'text-reviewer'});await ui('ltReviewerUI.apply('+JSON.stringify(backend.assistant.runtime.settings())+');ltReviewerUI.refresh()');await ui('ltAssistantUI.action("models")');await ui('document.getElementById("assistant-model").value="coder-fixture";document.getElementById("assistant-model").onchange()');assert.equal(await ui('document.getElementById("assistant-model").value'),'coder-fixture');await ui('ltReviewerUI.refresh()');assert.equal(await ui('ltReviewerUI.taskEnabled()'),true);await ui('document.getElementById("assistant-input").value="Fix the responsive width and verify the counter interactions";ltAssistantUI.send()');await until(()=>!backend.assistant.runtime.activeCount());
  assert.equal(backend.assistant.runtime.state().status,'completed',backend.assistant.runtime.state().reason);const completed=backend.assistant.store.load(session.id),report=completed.reviewReports.at(-1);assert.equal(report.status,'passed');if(focusedVerification){assert(report.tests.passed);assert.equal(report.criteria.checks.length,4);assert(report.evidence.viewports.every(v=>v.dom.requiredControls.every(c=>c.passed)));}assert(completed.journal.some(j=>j.status==='saved'));assert(completed.commands.some(c=>c.exitCode===0&&c.command.includes('node --test')));assert(report.behavior.every(c=>c.passed));assert.deepEqual(report.behavior.map(c=>c.viewport),['desktop','mobile']);assert(fs.readFileSync(html,'utf8').includes('width:100%'));
 });
 }else await check('Automatic correction makes an actual journaled mobile fix, runs tests and behavior assertions at both sizes',async()=>{host.focus();const visible=require(core+'/revival-preview.cjs').view('assistant:'+run.owner);visible.webContents.focus();visible.webContents.setBackgroundThrottling(false);await sleep(200);await backend.assistant.runtime.review(run.owner,{sessionId:session.id,mode:'improve',goal:'Fix clear layout defects.'});await until(()=>!backend.assistant.runtime.activeCount());assert.equal(backend.assistant.runtime.state().status,'completed',backend.assistant.runtime.state().reason);assert(fs.readFileSync(html,'utf8').includes('width:100%'));const saved=backend.assistant.store.load(session.id);assert(saved.journal.some(j=>j.status==='saved'));assert(saved.commands.some(c=>c.exitCode===0&&c.command.includes('node --test')));const report=saved.reviewReports.at(-1);assert.equal(report.status,'passed');assert.deepEqual(report.behavior.map(c=>c.viewport),['desktop','mobile']);assert(report.behavior.every(c=>c.passed&&c.revision===report.evidence.revision));assert(!report.unverified.some(s=>s.includes('interaction')));});
 await check('Uncertain judgments pause without authoring extra source edits',async()=>{uncertain=true;const bytes=fs.readFileSync(html);await backend.assistant.runtime.review(run.owner,{sessionId:session.id,mode:'improve'});await until(()=>!backend.assistant.runtime.activeCount());assert.equal(backend.assistant.runtime.state().status,'paused');assert(fs.readFileSync(html).equals(bytes));uncertain=false;});
 await check('Actual settings retain independent internal reviewer settings on Cancel and Save',async()=>{await ui('ltAssistantUI.action("settings");void 0');await sleep(200);assert(await ui('!!document.getElementById("assistant-settings-reviewer")'));await ui('document.getElementById("assistant-settings-reviewer").value="image-reviewer";document.getElementById("assistant-settings").close();void 0');assert.equal(backend.assistant.runtime.settings().reviewerModel,'text-reviewer');await ui('ltAssistantUI.action("settings");void 0');await sleep(200);await ui('document.getElementById("assistant-settings-reviewer").value="image-reviewer";document.getElementById("assistant-settings").querySelector("form").requestSubmit();void 0');await until(()=>ui('!document.getElementById("assistant-settings")'));assert.equal(backend.assistant.runtime.settings().reviewerModel,'image-reviewer');assert.equal(backend.assistant.runtime.settings().model,'coder-fixture');});
 await check('Development-server evidence binds transformed HTML and rejects later source edits',async()=>{await backend.assistant.preview.stop(run);const serverFile=path.join(root,'review-server.cjs');fs.writeFileSync(serverFile,'const fs=require("fs"),http=require("http");const server=http.createServer((_,res)=>{res.setHeader("content-type","text/html");res.end(fs.readFileSync("index.html","utf8").replace("<h1>","<meta name=transformed content=yes><h1>"));});server.listen(0,"127.0.0.1",()=>console.log("http://127.0.0.1:"+server.address().port));');const job=await backend.assistant.commands.start(run.owner,{command:'node review-server.cjs',cwd:root,purpose:'server',background:true},run.abort.signal);await until(()=>backend.assistant.commands.status(job.id,run.owner)?.stdout?.includes('http://127.0.0.1:'));const url=backend.assistant.commands.status(job.id,run.owner).stdout.match(/http:\/\/127\.0\.0\.1:\d+/)[0];await backend.assistant.preview.start(run,{job_id:job.id,url});const e=await backend.assistant.preview.evidence(run,{images:false,signal:run.abort.signal});assert.equal(e.viewports[0].dom.width,1280);assert.equal(e.viewports[1].dom.width,390);assert(await backend.assistant.preview.current(run,e));assert.equal(await backend.assistant.preview.testRevision(run),require(core+'/revival-assistant-verification.cjs').projectRevision(root));const source=fs.readFileSync(html);try{fs.appendFileSync(html,'<!-- Later edit -->');assert(!await backend.assistant.preview.current(run,e));}finally{fs.writeFileSync(html,source);}await backend.assistant.preview.stop(run);await backend.assistant.commands.stop(run.owner,job.id);await backend.assistant.preview.start(run,{path:html});});
 result.profile={migrated:migratedProfile,directory:backend.assistant.store.directory,legacy:path.join(policy.user,'assistant')};
 result.screenshot=path.join(policy.root,evidenceName+'.png');fs.writeFileSync(result.screenshot,(await require('./native-page-capture.cjs').captureNativePage(host.webContents)).toPNG());await finish();
 }catch(e){await finish(e);}},800));});backend=require(core+'/main.js');
