'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const core=path.resolve(__dirname,'../../deploy/core'),root=fs.mkdtempSync(path.join(os.tmpdir(),'lt-reviewer-')),checks=[];
const check=async(name,fn)=>{await fn();checks.push(name);},until=async(fn)=>{const end=Date.now()+5000;while(!fn()){if(Date.now()>end)throw Error('Reviewer check timed out');await new Promise(r=>setTimeout(r,5));}};
const choices=(q,value,p=1)=>({type:'choice',choice:value,confidence:p,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===value?p:(1-p)/(Object.keys(q.criteria).length-1)]))});
const answer=(body,category='clean',requirement='met',p=1)=>({model:body.model,answers:{category:choices(body.questions.category,category,p),requirement:choices(body.questions.requirement,requirement,p)}});
function evidence(category='clean'){return {previewId:'preview',revision:'revision',capturedAt:new Date().toISOString(),sources:[],images:['cG5n','cG5n'],viewports:['desktop','mobile'].map(name=>({name,width:name==='desktop'?1280:390,height:name==='desktop'?800:844,dom:{text:'Counter',overflow:category==='overflow',elements:[{tag:'BUTTON',id:'increment',text:'Increment',visible:category!=='missing_control'},{tag:'OUTPUT',id:'count',text:'0',visible:true}],width:name==='desktop'?1280:390},errors:[],logs:[],performance:{frames:300,p95FrameMs:16,medianFrameMs:16,longTasks:0,longTaskMs:0}}))};}
function setup({category='clean',images=false,probability=1}={}){
 const store=require(core+'/revival-assistant-store.cjs').create(path.join(root,crypto.randomUUID()));store.settings({model:'coder',reviewerModel:'judge'});let currentCategory=category,digest='v1',calls=[],unloaded=[];
 const client={models:async()=>[{name:'coder',digest:'coder'},{name:'judge',digest}],show:async m=>({capabilities:m==='coder'?['tools']:['decision',...(images?['vision']:[])]}),unload:async m=>unloaded.push(m),decision:async body=>{calls.push(body);return answer(body,currentCategory,currentCategory==='clean'?'met':'unmet',probability);},chat:async()=>({message:{role:'assistant',content:'Done'}})};
 const preview={evidence:async()=>{assert.equal(unloaded.at(-1),'coder','Release coding before browser measurements');const e=evidence(currentCategory);if(!images)e.images=[];return e;},current:async()=>true,stop:async()=>{},fixture:async(_run,html)=>{const e=evidence();e.html=html;return e;}};
 const options={store,client,preview,editor:async(_owner,op)=>op==='context'?{buffers:[]}:null,commands:{stop:async()=>{},shutdown:async()=>{}},createProject:async()=>{},notify:()=>{}};
 const reviewer=require(core+'/revival-reviewer.cjs').create(options);
 return {options,store,client,preview,reviewer,calls,unloaded,category:value=>currentCategory=value,digest:value=>digest=value};
}
async function main(){
 await check('Production-required review cannot be disabled by a task flag and selects an installed reviewer automatically',async()=>{const a=setup();a.store.settings({reviewerModel:null});const runtime=require(core+'/revival-assistant.cjs').create({...a.options,requireReview:true});await runtime.start(1,{root,text:'Fix clear defects.',reviewAndImprove:false});await until(()=>!runtime.activeCount());assert.equal(runtime.settings().reviewerModel,'judge');assert.equal(runtime.state().status,'completed',runtime.state().reason);assert.equal(a.calls.length,2);assert.equal(runtime.load(runtime.state().sessionId).reviewReports.at(-1).status,'passed');await runtime.shutdown();});
 await check('Required review blocks coding before inference when no local decision model is installed',async()=>{const a=setup();let chats=0;a.client.models=async()=>[{name:'coder'}];a.client.chat=async()=>{chats++;return {message:{role:'assistant',content:'Done'}}};const runtime=require(core+'/revival-assistant.cjs').create({...a.options,requireReview:true});await assert.rejects(runtime.start(1,{root,text:'Build a page',reviewAndImprove:false}),/requires an installed local Ollama decision model/);assert.equal(chats,0);assert.equal(runtime.activeCount(),0);await runtime.shutdown();});
 await check('Decision transport uses System One and preserves the explicit unload policy',async()=>{let request;const client=require(core+'/revival-assistant-ollama.cjs').create({fetchImpl:async(url,options)=>{request={url,options};return {ok:true,json:async()=>answer(JSON.parse(options.body))};}});const body={model:'judge',state:'Observed evidence',questions:require(core+'/revival-reviewer.cjs').questions(),keep_alive:'1m'};await client.decision(body);assert.equal(request.url.pathname,'/v1/systemone');assert.equal(JSON.parse(request.options.body).keep_alive,'1m');assert.equal(JSON.parse(request.options.body).stream,undefined);});
 await check('Removed Clef models never reach the decision transport',async()=>{let requests=0;const client=require(core+'/revival-assistant-ollama.cjs').create({fetchImpl:async()=>{requests++;throw Error('Must not request removed models');}});for(const model of ['clef:latest','clef-flash:latest','cloudflare/clef-flash:9b'])await assert.rejects(()=>client.decision({model,state:'evidence',questions:require(core+'/revival-reviewer.cjs').questions()}),/Clef support is temporarily removed/);assert.equal(requests,0);});
 await check('Clef and renamed Clef weights are excluded from both catalogs and cannot start tasks',async()=>{const a=setup(),show=a.client.show;a.client.models=async()=>[{name:'coder',digest:'coder'},{name:'judge',digest:'judge'},{name:'clef-flash:latest',digest:'clef'},{name:'renamed-reviewer',digest:'alias'}];a.client.show=async name=>name==='renamed-reviewer'?{capabilities:['tools','decision'],model_info:{'qwen35.decision.type':'clef'}}:show(name);a.store.settings({model:'coder',reviewerModel:'renamed-reviewer'});const runtime=require(core+'/revival-assistant.cjs').create(a.options);assert.deepEqual((await runtime.models()).map(m=>m.name),['coder','judge']);assert.equal(runtime.settings().reviewerModel,null);assert.equal(runtime.settings().model,'coder');assert.deepEqual((await runtime.reviewerModels()).map(m=>m.name),['judge']);await assert.rejects(runtime.start(1,{root,text:'test',model:'renamed-reviewer'}),/Clef support is temporarily removed/);assert.equal(runtime.activeCount(),0);await runtime.shutdown();});
 await check('Saved Clef selections reset while coding settings and conversation history are retained',()=>{const a=setup(),file=path.join(a.store.directory,'settings.json'),session=a.store.conversation(root);fs.writeFileSync(file,JSON.stringify({...a.store.settings(),model:'coder',reviewerModel:'clef-flash:latest'}));assert.equal(a.store.settings().reviewerModel,null);assert.equal(JSON.parse(fs.readFileSync(file)).reviewerModel,null);assert.equal(a.store.settings().model,'coder');assert.equal(a.store.load(session.id).id,session.id);assert.throws(()=>a.store.settings({reviewerModel:'clef:27b'}),/Clef support is temporarily removed/);});
 await check('Malformed decisions, missing answers, invalid distributions and oversized requests are rejected',()=>{const protocol=require(core+'/revival-reviewer-protocol.cjs'),body={model:'judge',state:'evidence',questions:require(core+'/revival-reviewer.cjs').questions()};for(const value of [{},answer(body,'not_an_option'),{...answer(body),model:'other'},{...answer(body),answers:{}}])assert.throws(()=>protocol.validateResponse(body,value));assert.throws(()=>protocol.validateRequest({...body,state:'a'.repeat(65536)}));assert.throws(()=>protocol.validateRequest({...body,images:['data:image/png;base64,cG5n']}));assert.throws(()=>protocol.validateRequest({...body,tools:[]}));});
 await check('Stop cancels a decision while waiting for HTTP headers',async()=>{const http=require('http'),server=http.createServer(()=>{});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const client=require(core+'/revival-assistant-ollama.cjs').create({baseURL:'http://127.0.0.1:'+server.address().port}),abort=new AbortController(),pending=client.decision({model:'judge',state:'evidence',questions:require(core+'/revival-reviewer.cjs').questions()},{signal:abort.signal});setTimeout(()=>abort.abort(Error('stopped')),20);await assert.rejects(pending,/stopped|abort/i);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
 await check('A decision deadline reports timeout separately from caller cancellation',async()=>{const http=require('http'),server=http.createServer(()=>{}),originalTimeout=AbortSignal.timeout;await new Promise(r=>server.listen(0,'127.0.0.1',r));try{AbortSignal.timeout=ms=>{assert.equal(ms,300000);return originalTimeout.call(AbortSignal,20);};const client=require(core+'/revival-assistant-ollama.cjs').create({baseURL:'http://127.0.0.1:'+server.address().port}),body={model:'judge',state:'evidence',questions:require(core+'/revival-reviewer.cjs').questions()};await assert.rejects(client.decision(body),/five-minute request deadline/);const abort=new AbortController(),reason=Error('Review cancelled explicitly');abort.abort(reason);await assert.rejects(client.decision(body,{signal:abort.signal}),error=>error===reason);}finally{AbortSignal.timeout=originalTimeout;server.closeAllConnections();await new Promise(r=>server.close(r));}});
 await check('Metadata excludes coding models and detects image support independently',async()=>{const a=setup({images:true});const list=await a.reviewer.models();assert.equal(list.length,1);assert.equal(list[0].mode,'Text + images');assert.equal(list[0].validation,'Untested');});
 await check('Installed vision projector enables images when decision capabilities omit vision',async()=>{const a=setup();a.client.show=async()=>({capabilities:['decision'],projector_info:{'clip.has_vision_encoder':true}});assert((await a.reviewer.selected('judge')).images);a.client.show=async()=>({capabilities:['decision'],model_info:{'general.tags':['multimodal']}});assert.equal((await a.reviewer.selected('judge')).images,false);});
 await check('Transformed server responses bind to the latest raw source revision',()=>{const collector=require(core+'/revival-reviewer-evidence.cjs'),file=path.join(root,'server-source.html'),source='<h1>Current</h1>';fs.writeFileSync(file,source);const sha=crypto.createHash('sha256').update(source).digest('hex'),state={project:{mode:'server',files:[{path:file,origin:'http',source:'old transform',sha256:'old',sourceSha256:'old'},{path:file,origin:'http',source:'new transform',sha256:'transformed',sourceSha256:sha}]}};assert(collector.sourceCurrent(state,[{path:file,source}]));assert.equal(collector.sourceFiles(state).length,1);assert.equal(collector.sources(state)[0].sha256,sha);fs.writeFileSync(file,source+'changed');assert(!collector.sourceCurrent(state));});
 await check('Untested installed reviewers allow coding tasks and automatic review without qualification',async()=>{const a=setup();assert.equal((await a.reviewer.selected('judge')).validation,'Untested');const runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.start(1,{root,text:'Ordinary task'});await until(()=>!runtime.activeCount());await runtime.start(1,{root,text:'Improve',reviewAndImprove:true});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'completed');assert.equal(a.calls.length,2);const session=a.store.load(runtime.state().sessionId);assert.equal(session.reviewReports[0].model,'judge');a.store.settings({reviewerModel:'missing'});await assert.rejects(runtime.start(1,{root,text:'Unavailable reviewer',reviewAndImprove:true}),/unavailable/);});
 await check('Text reviews never send images, preserve valid JSON, and label image verification unavailable',async()=>{const a=setup(),session=a.store.conversation(root),run={session,abort:new AbortController()},model=await a.reviewer.selected('judge'),result=await a.reviewer.review(run,{model});assert(a.calls.every(b=>b.images===undefined&&Buffer.byteLength(JSON.stringify(b))<=6000));assert.equal(result.report.imageReviewCompleted,false);assert.equal(result.report.status,'passed');assert(result.report.unverified.length);assert.deepEqual(a.unloaded,['coder','judge']);});
 await check('Image reviews send real ordered baseline and current images outside persisted reports',async()=>{const a=setup({images:true}),run={session:a.store.conversation(root),abort:new AbortController()},model=await a.reviewer.selected('judge'),baseline=evidence();baseline.images=['YmFzZTE=','YmFzZTI='];const {report}=await a.reviewer.review(run,{model,baseline});assert.deepEqual(a.calls[0].images,['YmFzZTE=','cG5n']);assert(!JSON.stringify(report).includes('cG5n'));assert(report.imageReviewCompleted);});
 await check('Explicit screenshot requirements stay unverified with a text-only reviewer',async()=>{const a=setup(),run={session:a.store.conversation(root),abort:new AbortController()},result=await a.reviewer.review(run,{model:await a.reviewer.selected('judge'),locked:require(core+'/revival-reviewer.cjs').criteria('Visually verify the screenshot')});assert.equal(result.report.status,'uncertain');assert.equal(require(core+'/revival-reviewer.cjs').criteria('Verify screenshots').requireImages,true);});
 await check('Required interaction checks must be current and pass at both sizes',async()=>{const a=setup(),session=a.store.conversation(root),run={session,abort:new AbortController()},model=await a.reviewer.selected('judge'),locked=require(core+'/revival-reviewer.cjs').criteria('Verify clicking Increment updates the count');let result=await a.reviewer.review(run,{model,locked});assert.equal(result.report.status,'uncertain');session.behaviorChecks=['desktop','mobile'].map(viewport=>({revision:evidence().revision,viewport,passed:true,label:'Increment',details:'Count updated'}));result=await a.reviewer.review(run,{model,locked});assert.equal(result.report.status,'passed');assert.equal(require(core+'/revival-reviewer.cjs').criteria('Redesign the header').preserveDesign,false);});
 await check('Deterministic errors and failed tests override favorable reviewer answers',async()=>{const a=setup();a.preview.evidence=async()=>{const e=evidence();e.viewports[0].errors=[{message:'Actual error'}];return e;};const session=a.store.conversation(root);session.commands=[{command:'node --test',purpose:'test',exitCode:1,status:'failed'}];const result=await a.reviewer.review({session,abort:new AbortController()},{model:await a.reviewer.selected('judge')});assert.equal(result.report.status,'needs_correction');assert(result.report.findings.some(f=>f.category==='runtime_error'));assert(result.report.findings.some(f=>f.category==='tests'));});
 await check('Ambiguous or low-probability reviewer decisions pause correction',async()=>{const a=setup({probability:.6}),result=await a.reviewer.review({session:a.store.conversation(root),abort:new AbortController()},{model:await a.reviewer.selected('judge')});assert.equal(result.report.status,'uncertain');});
 await check('Source changes during inference invalidate the result and release image memory',async()=>{const a=setup({images:true});let captured;a.preview.evidence=async()=>captured=evidence();a.preview.current=async()=>false;await assert.rejects(a.reviewer.review({session:a.store.conversation(root),abort:new AbortController()},{model:await a.reviewer.selected('judge')}),/stale/);assert.equal(captured.images.length,0);assert.equal(a.unloaded.at(-1),'judge');});
 await check('Unbound development-server source remains uncertain despite favorable decisions',async()=>{const a=setup();a.preview.evidence=async()=>({...evidence(),sourceBindingSupported:false,images:[]});const {report}=await a.reviewer.review({session:a.store.conversation(root),abort:new AbortController()},{model:await a.reviewer.selected('judge')});assert.equal(report.status,'uncertain');assert(report.uncertain.some(s=>s.includes('source files')));});
 await check('Manual review is persisted without screenshots and survives restart',async()=>{const a=setup({images:true}),runtime=require(core+'/revival-assistant.cjs').create(a.options),session=a.store.conversation(root);await runtime.review(1,{sessionId:session.id,mode:'review'});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'completed');const saved=a.store.load(session.id);assert(saved.reviewReports.length===1);assert(!JSON.stringify(saved).includes('cG5n'));});
 await check('Stop and Pause apply to reviewer requests, preserving paused restart recovery',async()=>{const a=setup();let signal;a.client.decision=async(_b,options)=>new Promise((_resolve,reject)=>{signal=options.signal;signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});const runtime=require(core+'/revival-assistant.cjs').create(a.options),session=a.store.conversation(root);await runtime.review(1,{sessionId:session.id});await until(()=>!!signal);runtime.pause(1);assert.equal(runtime.state().status,'pausing');await runtime.stop(1);assert(signal.aborted);assert.equal(runtime.state().status,'stopped');});
 await check('A validated reviewer can drive journaled actual file corrections and complete rechecks',async()=>{const a=setup({category:'overflow'}),model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));const target=path.join(root,'correct-'+crypto.randomUUID()+'.html');fs.writeFileSync(target,'width:700px');let step=0;a.client.chat=async()=>{const actions=[{name:'read_file',arguments:{path:target}},{name:'edit_file',arguments:{path:target,old_text:'width:700px',new_text:'width:100%'}}];if(step<2)return {message:{role:'assistant',tool_calls:[{function:actions[step++]}]}};a.category('clean');return {message:{role:'assistant',content:'Fixed'}};};const runtime=require(core+'/revival-assistant.cjs').create(a.options),s=a.store.conversation(root);await runtime.review(1,{sessionId:s.id,mode:'improve'});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'completed');assert.equal(fs.readFileSync(target,'utf8'),'width:100%');assert.equal(a.store.load(s.id).journal[0].status,'saved');assert.equal(a.store.load(s.id).reviewReports.length,2);});
 await check('Repeated correction findings cannot create an endless loop',async()=>{const a=setup({category:'overflow'}),model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));const runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.review(1,{root,mode:'improve'});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'paused');assert(runtime.state().round<=3);assert.match(runtime.state().reason,/persist|Three/);});
 await check('New instructions pause locked corrections and Resume uses fresh criteria',async()=>{const a=setup({category:'overflow'}),model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));let release;a.client.chat=async()=>new Promise(resolve=>release=()=>resolve({message:{role:'assistant',content:'Ready'}}));const runtime=require(core+'/revival-assistant.cjs').create(a.options),session=a.store.conversation(root);await runtime.review(1,{sessionId:session.id,mode:'improve'});await until(()=>!!release);const next='Verify screenshots of the revised header';await runtime.start(1,{sessionId:session.id,text:next});assert.equal(runtime.state().status,'pausing');assert.notEqual(a.store.load(session.id).reviewTask.criteria.goal,next);release();await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'paused');assert.match(runtime.state().reason,/request changed/);await runtime.resume(1,{sessionId:session.id});await until(()=>!runtime.activeCount());assert.equal(a.store.load(session.id).reviewTask.criteria.goal,next);assert.equal(runtime.state().round,0);assert.match(runtime.state().reason,/image verification/);});
 await check('Changing a model digest invalidates its diagnostic receipt without blocking selection',async()=>{const a=setup(),m=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[m.key]:{passed:true}}));assert.equal((await a.reviewer.selected('judge')).validation,'Validated');a.digest('v2');const changed=await a.reviewer.selected('judge');assert.equal(changed.validation,'Untested');assert.notEqual(changed.key,m.key);});
 await check('Interrupted revalidation revokes an earlier passing receipt without blocking selection',async()=>{const a=setup(),model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));a.preview.fixture=async()=>{throw Error('Interrupted fixture');};await assert.rejects(a.reviewer.qualify({session:a.store.conversation(root),abort:new AbortController()},model),/Interrupted fixture/);assert.equal((await a.reviewer.selected('judge')).validation,'Untested');});
 await check('Text qualification rejects confident guesses when behavior receipts or acceptance criteria are missing',async()=>{const a=setup(),model=await a.reviewer.selected('judge'),fixtures=require(core+'/revival-reviewer-fixtures.cjs').fixtures;let calls=0,acknowledgeMissing=false;a.preview.fixture=async()=>evidence();a.client.decision=async body=>{const index=calls++,fixture=fixtures[Math.floor(index/2)],category=index<24?(fixture.id==='overflow-mobile'&&index%2===0?'clean':fixture.expected):'clean',missing=/No interaction checks were performed|requirements have not been supplied/.test(body.state.criterion);return answer(body,category,missing&&acknowledgeMissing?'uncertain':category==='clean'?'met':'unmet');};const run={session:a.store.conversation(root),abort:new AbortController()};let receipt=await a.reviewer.qualify(run,model);assert.equal(receipt.correct,12);assert(receipt.cycles.every(c=>c.passed));assert.equal(receipt.uncertaintyChecks.length,2);assert(receipt.uncertaintyChecks.every(c=>!c.passed));assert.equal(receipt.passed,false);assert.equal((await a.reviewer.selected('judge')).validation,'Untested');calls=0;acknowledgeMissing=true;receipt=await a.reviewer.qualify(run,model);assert.equal(receipt.passed,true);assert.equal((await a.reviewer.selected('judge')).validation,'Validated');});
 await check('Reviewer settings are additive and do not change the coding selection',()=>{const a=setup();a.store.settings({reviewerModel:'other'});const reopened=require(core+'/revival-assistant-store.cjs').create(a.store.directory);assert.equal(reopened.settings().model,'coder');assert.equal(reopened.settings().reviewerModel,'other');});
 await check('The time budget aborts inference and pauses rather than reporting user Stop',async()=>{const a=setup();a.options.reviewBudgetMs=30;a.client.decision=async(_body,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));const runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.review(1,{root});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'paused');assert.match(runtime.state().reason,/budget/);});
 await check('Distinct findings still stop after exactly three correction rounds',async()=>{const a=setup(),model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));let decisions=0;a.client.decision=async body=>answer(body,['clipping','overflow','missing_control','other'][Math.floor(decisions++/2)%4],'unmet');const runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.review(1,{root,mode:'improve'});await until(()=>!runtime.activeCount());assert.equal(runtime.state().round,3);assert.match(runtime.state().reason,/Three correction rounds/);assert.equal(decisions,8);});
 await check('A changed source invalidates scripted behavior assertions',async()=>{const a=setup(),session=a.store.conversation(root);session.behaviorChecks=[{revision:'old',passed:false,viewport:'mobile',label:'old failed click',details:'old'}];const {report}=await a.reviewer.review({session,abort:new AbortController()},{model:await a.reviewer.selected('judge')});assert.equal(report.behavior.length,0);assert.equal(report.status,'passed');});
 await check('Edits during a passing test command invalidate its verification receipt',async()=>{const a=setup(),caseRoot=path.join(root,'test-race-'+crypto.randomUUID());fs.mkdirSync(caseRoot);fs.writeFileSync(path.join(caseRoot,'package.json'),JSON.stringify({scripts:{test:'node --test'}}));const model=await a.reviewer.selected('judge');fs.writeFileSync(path.join(a.store.directory,'reviewer-validation.json'),JSON.stringify({[model.key]:{passed:true}}));let step=0,revision='before',runtime;a.preview.testRevision=async()=>revision;a.options.commands.start=async()=>{revision='after';const value={id:'test-race',command:'node --test',cwd:caseRoot,purpose:'test',status:'completed',exitCode:0};runtime.commandEvent(1,{type:'command',command:value});return value;};a.client.chat=async()=>step++===0?{message:{role:'assistant',tool_calls:[{function:{name:'run_command',arguments:{command:'node --test',cwd:caseRoot,purpose:'test'}}}]}}:{message:{role:'assistant',content:'Done'}};runtime=require(core+'/revival-assistant.cjs').create(a.options);const session=a.store.conversation(caseRoot);await runtime.review(1,{sessionId:session.id,mode:'improve'});await until(()=>!runtime.activeCount());const saved=a.store.load(session.id);assert.equal(saved.testSourceRevision,null);assert.equal(saved.reviewReports.at(-1).tests.receipts[0].exitCode,0);assert.equal(saved.reviewReports.at(-1).tests.passed,false);assert.equal(runtime.state().status,'paused');});
 await check('Confident clean judgments cannot approve a missing named control at either size',async()=>{
  const a=setup(),locked={...require(core+'/revival-reviewer.cjs').criteria('The Counter requires Increment'),checks:[{id:'increment',kind:'control',selector:'#increment',description:'Increment is visible'}]};
  a.preview.evidence=async(_run,options)=>{assert.deepEqual(options.checks,locked.checks);const e=evidence();for(const v of e.viewports)v.dom.requiredControls=[{id:'increment',passed:v.name==='desktop'}];return e;};
  const {report}=await a.reviewer.review({session:a.store.conversation(root),abort:new AbortController()},{model:await a.reviewer.selected('judge'),locked});assert.equal(report.status,'needs_correction');assert(report.findings.some(f=>f.checkId==='increment'&&f.viewport==='mobile'));
 });
 await check('Named behavior checks require individual current receipts at both sizes and retain the latest result',async()=>{
  const a=setup(),session=a.store.conversation(root),locked={...require(core+'/revival-reviewer.cjs').criteria('Verify interactions'),checks:[{id:'increment',kind:'behavior',description:'Increment increases count'},{id:'reset',kind:'behavior',description:'Reset clears count'}]};
  session.behaviorChecks=['desktop','mobile'].map(viewport=>({viewport,checkId:'increment',label:'Increment',details:'passed',passed:true,revision:'revision'}));
  let result=await a.reviewer.review({session,abort:new AbortController()},{model:await a.reviewer.selected('judge'),locked});assert.equal(result.report.status,'uncertain');assert(result.report.uncertain.every(s=>s.includes('reset')));
  for(const viewport of ['desktop','mobile'])session.behaviorChecks.push({viewport,checkId:'reset',label:'Reset',details:'failed earlier',passed:false,revision:'revision'},{viewport,checkId:'reset',label:'Reset',details:'passed on recheck',passed:true,revision:'revision'});
  result=await a.reviewer.review({session,abort:new AbortController()},{model:await a.reviewer.selected('judge'),locked});assert.equal(result.report.status,'passed');assert.equal(result.report.behavior.length,4);
 });
 await check('Tests run before preview startup are source-bound and survive restart without automatic replay',async()=>{
  const a=setup(),caseRoot=path.join(root,crypto.randomUUID());fs.mkdirSync(caseRoot);fs.writeFileSync(path.join(caseRoot,'case.test.cjs'),'tests');let step=0,started=false,runtime;
  a.options.commands.start=async(_owner,args)=>{assert(!started);const value={id:'before-preview',...args,status:'exited',exitCode:0};runtime.commandEvent(1,{type:'command',command:value});return value;};a.preview.start=async()=>{started=true;return {status:'running'};};
  a.client.chat=async()=>{const calls=[{name:'run_command',arguments:{command:'node --test case.test.cjs',purpose:'test'}},{name:'start_preview',arguments:{path:path.join(caseRoot,'index.html')}}];return step<calls.length?{message:{role:'assistant',tool_calls:[{function:calls[step++]}]}}:{message:{role:'assistant',content:'Done'}};};
  runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.start(1,{root:caseRoot,text:'Verify source tests',reviewAndImprove:true});await until(()=>!runtime.activeCount());assert.equal(runtime.state().status,'completed',runtime.state().reason);const session=runtime.load(runtime.state().sessionId);assert(session.commands[0].sourceRevision);assert(session.reviewReports.at(-1).tests.passed);
  const restored=require(core+'/revival-assistant-store.cjs').create(a.store.directory).load(session.id),revision=require(core+'/revival-assistant-verification.cjs').projectRevision(caseRoot);assert(require(core+'/revival-reviewer.cjs').testEvidence({session:restored},revision).passed);fs.writeFileSync(path.join(caseRoot,'case.test.cjs'),'changed');assert(!require(core+'/revival-reviewer.cjs').testEvidence({session:restored},require(core+'/revival-assistant-verification.cjs').projectRevision(caseRoot)).passed);
 });
 await check('Acceptance criteria lock before edits and cannot be changed during correction or an interaction check',async()=>{
  const a=setup(),tools=require(core+'/revival-assistant-tools.cjs').create({files:{},commands:{},editor:()=>{},preview:a.preview,notify:()=>{}}),criteria=require(core+'/revival-reviewer.cjs').criteria('Increment count'),run={id:'criteria-run',session:{root,journal:[],reviewTask:{}},reviewTask:{round:0,criteria},abort:new AbortController()},checks=[{id:'increment',kind:'behavior',description:'Increment increases count'}];
  await tools.execute({function:{name:'set_review_criteria',arguments:{checks}}},run);assert(run.reviewTask.criteria.declared);await assert.rejects(tools.execute({function:{name:'set_review_criteria',arguments:{checks:[]}}},run),/locked/);await assert.rejects(tools.execute({function:{name:'check_preview',arguments:{check_id:'unknown',viewport:'mobile',label:'Unknown',source:'({passed:true,details:"Unknown"})'}}},run),/locked behavior/);
  run.reviewTask.criteria=criteria;run.reviewTask.round=1;await assert.rejects(tools.execute({function:{name:'set_review_criteria',arguments:{checks}}},run),/locked/);run.reviewTask.round=0;run.session.journal=[{runId:run.id,status:'saved'}];await assert.rejects(tools.execute({function:{name:'set_review_criteria',arguments:{checks}}},run),/locked/);
 });
 await check('Resume preserves declared requirements while gathering fresh evidence in a bounded session',async()=>{
  const a=setup(),session=a.store.conversation(root),criteria={...require(core+'/revival-reviewer.cjs').criteria('Verify Counter'),checks:[{id:'increment',kind:'behavior',description:'Increment increases count'}],declared:true};session.status='paused';session.model='coder';session.reviewTask={mode:'task',criteria};a.store.save(session);const runtime=require(core+'/revival-assistant.cjs').create(a.options);await runtime.resume(1,{sessionId:session.id});await until(()=>!runtime.activeCount());assert.deepEqual(runtime.load(session.id).reviewTask.criteria.checks,criteria.checks);assert.equal(runtime.state().round,0);assert.equal(runtime.state().status,'paused');assert.match(runtime.state().reason,/increment/);
 });
 fs.rmSync(root,{recursive:true});console.log(JSON.stringify({passed:true,checks},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
