'use strict';
const assert=require('assert/strict'),path=require('path'),vm=require('vm'),fs=require('fs');
const serverWatches=require('../../deploy/core/revival-server-watches.cjs'),watches=require('../../deploy/core/proof-watches.cjs'),browser=require('../../deploy/core/revival-browser-watches.cjs'),compiler=require('../../deploy/core/node_modules/esbuild'),mapping=require('../../deploy/core/node_modules/@jridgewell/trace-mapping'),html=require('../../deploy/core/revival-html-watches.cjs'),acorn=require('../../deploy/core/node_modules/acorn');
const root=path.resolve(__dirname,'../../.revival/server-watch-compiler'),file=path.join(root,'helper.js'),origin='http://compiler/',checks=[];
const input=(source,text='n * 2',expression)=>[{path:file,source,watches:[{id:'selected',from:source.indexOf(text),to:source.indexOf(text)+text.length,...(expression?{expression}:{})}]}];
function compile(source,extra={}){const code=compiler.transformSync(source,{sourcefile:'helper.js',loader:'js',sourcemap:'inline',format:'iife',banner:'// compiler header\n// second header',...extra}).code,encoded=code.match(/base64,([^\s]+)/)[1];return {code,map:new mapping.TraceMap(JSON.parse(Buffer.from(encoded,'base64').toString('utf8')),origin+'compiled.js')};}
function execute(watcher,transformed,n=21){const observed=[],sandbox={[watcher.watch.key]:(id,value,token)=>{observed.push({id,value,token});return value;}};vm.runInNewContext(transformed.source,sandbox);return {value:sandbox.double(n),observed};}
const resolve=address=>address===origin+'helper.js'?file:null;
function check(label,fn){fn();checks.push(label);}
const original='function double(n){return n * 2;}globalThis.double=double;';
check('Real compiler source maps identify a complete lexical expression',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original),transformed=watcher.transform(compiled.code,compiled.map,null,resolve),run=execute(watcher,transformed);assert.equal(run.value,42);assert.equal(run.observed[0].value,42);assert.equal(run.observed[0].token,watcher.watch.specs[0].captureToken);assert.equal(watcher.bindings()[0].status,'bound');});
check('Exact raw server JavaScript also captures watches without a source map',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),run=execute(watcher,watcher.transform(original,null,file,resolve));assert.equal(run.value,42);assert.equal(run.observed.length,1);});
check('Custom compiled watches preserve the original program return value',()=>{const watcher=serverWatches.create(root,input(original,'n * 2','__SELECTION__ + 1'),path.resolve),compiled=compile(original),run=execute(watcher,watcher.transform(compiled.code,compiled.map,null,resolve));assert.equal(run.value,42);assert.equal(run.observed[0].value,43);});
check('Minified compiler output retains complete expression watches',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original,{minify:true}),run=execute(watcher,watcher.transform(compiled.code,compiled.map,null,resolve));assert.equal(run.value,42);assert.equal(run.observed.length,1);});
check('Saved server output cannot masquerade as a newer unsaved watched source',()=>{const watcher=serverWatches.create(root,input(original.replace('n * 2','n * 3'),'n * 3'),path.resolve),compiled=compile(original),transformed=watcher.transform(compiled.code,compiled.map,null,resolve);assert.equal(transformed.source,compiled.code);assert.equal(watcher.bindings()[0].status,'stale');});
check('Compiler maps without one expression retain a visible mapping failure',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original),map=new mapping.TraceMap({version:3,sources:['helper.js'],sourcesContent:[original],names:[],mappings:'AAAA'},origin+'compiled.js'),transformed=watcher.transform(compiled.code,map,null,resolve);assert.equal(transformed.source,compiled.code);assert.equal(watcher.bindings()[0].status,'unmapped');});
check('Source and configuration updates preserve the collector key and change observation tokens',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),key=watcher.watch.key,token=watcher.watch.specs[0].captureToken;watcher.update(input(original,'n * 2','__SELECTION__ + 1'));assert.equal(watcher.watch.key,key);assert.notEqual(watcher.watch.specs[0].captureToken,token);assert.equal(watcher.watch.revision,1);});
check('Queued old collector messages cannot overwrite a newer watch plan',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),old=JSON.stringify({revision:0,values:[{id:'selected',result:'42',captureToken:watcher.watch.specs[0].captureToken}]});watcher.update(input(original.replace('n * 2','n * 3'),'n * 3'));assert.equal(browser.decode(old,watcher.watch),null);});
check('Current HTTP collector observations validate their exact source/configuration identity',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),token=watcher.watch.specs[0].captureToken;assert.equal(browser.decode(JSON.stringify({revision:0,values:[{id:'selected',result:'42',captureToken:token}]}),watcher.watch)[0].result,'42');assert.throws(()=>browser.decode(JSON.stringify({revision:0,values:[{id:'selected',result:'42',captureToken:'wrong'}]}),watcher.watch),/identity changed/);});
check('Watch plans cannot cross the server project root',()=>{const sibling=path.join(root,'..','outside.js');assert.throws(()=>serverWatches.create(root,[{...input(original)[0],path:sibling}],path.resolve),/leaves its project/);});
check('Windows CRLF saving retains editor expression offsets across several lines',()=>{const original='function double(n){\n return n * 2;\n}\nglobalThis.double=double;\n',watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original.replace(/\n/g,'\r\n')),run=execute(watcher,watcher.transform(compiled.code,compiled.map,null,resolve));assert.equal(run.value,42);assert.equal(run.observed[0].value,42);});
const htmlFile=path.join(root,'index.html'),document='<!doctype html>\r\n<title>compiled HTML 😀</title>\r\n<script type="module">\r\nfunction double(n){return n * 2;}globalThis.double=double;\r\n</script>\r\n<script type="module">function triple(n){return n * 3;}globalThis.triple=triple;</script>',htmlInputs=[{path:htmlFile,source:document,watches:['n * 2','n * 3'].map((text,index)=>({id:'inline'+index,from:document.indexOf(text),to:document.indexOf(text)+text.length}))}];
function compileBlock(document,index){const block=html.blocks(document)[index],compiled=compile(block.source),decoded=mapping.decodedMappings(compiled.map).map(line=>line.map(segment=>segment.slice())),position=html.originalLocation(document,block.from);
 for(const line of decoded)for(const segment of line)if(segment.length>1){if(segment[2]===0)segment[3]+=position.column;segment[2]+=position.line-1;}
 const map=new mapping.TraceMap({version:3,sources:['index.html'],sourcesContent:[document],names:compiled.map.names,mappings:decoded},origin+'compiled.js');return {code:compiled.code,map};}
const resolveHTML=address=>address===origin+'index.html'?htmlFile:null;
check('Compiler-relocated inline HTML expressions bind to their original full-document coordinates',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve),compiled=compileBlock(document,0),run=execute(watcher,watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML));assert.equal(run.value,42);assert.equal(run.observed[0].id,'inline0');assert.equal(watcher.bindings()[0].status,'bound');});
check('Separate modules from one HTML file retain each other\'s bound observations',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve),first=compileBlock(document,0),second=compileBlock(document,1);watcher.transform(first.code,first.map,htmlFile,resolveHTML);const transformed=watcher.transform(second.code,second.map,htmlFile,resolveHTML),observed=[],sandbox={[watcher.watch.key]:(id,value)=>{observed.push({id,value});return value;}};vm.runInNewContext(transformed.source,sandbox);assert.equal(sandbox.triple(21),63);assert.equal(observed[0].id,'inline1');assert(watcher.bindings().every(item=>item.status==='bound'));});
check('Relocated HTML modules cannot claim a changed unsaved source identity',()=>{const changed=document.replace('n * 2','n * 4'),watcher=serverWatches.create(root,[{...htmlInputs[0],source:changed}],path.resolve),compiled=compileBlock(document,0);assert.equal(watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML).source,compiled.code);assert(watcher.bindings().every(item=>item.status==='stale'));});
function bodyBlock(document,index,extra={}){const block=html.blocks(document)[index],compiled=compile(block.source,extra),raw={version:3,sources:['index.html'],sourcesContent:[block.source],names:compiled.map.names,mappings:mapping.decodedMappings(compiled.map)};return {code:compiled.code,map:new mapping.TraceMap(raw,origin+'compiled.js')};}
check('Script-body maps restore CRLF and UTF-16 selections in the original HTML',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve),compiled=bodyBlock(document,0),run=execute(watcher,watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source:document})));assert.equal(run.value,42);assert.equal(run.observed[0].id,'inline0');assert.equal(watcher.bindings()[0].status,'bound');});
check('Separate script-body maps preserve each original inline binding',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve);for(let index=0;index<2;index++){const compiled=bodyBlock(document,index);watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source:document}));}assert(watcher.bindings().every(item=>item.status==='bound'));});
check('Identical script bodies cannot invent a unique original HTML selection',()=>{const repeated=document.replace('function triple(n){return n * 3;}globalThis.triple=triple;',html.blocks(document)[0].source),text='n * 2',watcher=serverWatches.create(root,[{path:htmlFile,source:repeated,watches:html.blocks(repeated).map((block,index)=>({id:'duplicate'+index,from:block.from+block.source.indexOf(text),to:block.from+block.source.indexOf(text)+text.length}))}],path.resolve),compiled=bodyBlock(repeated,0),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source:repeated}));assert.equal(transformed.source,compiled.code);assert(watcher.bindings().every(item=>item.status==='unmapped'&&item.reason.includes('one original')));});
check('An unchanged body cannot claim unsaved changes elsewhere in its original HTML',()=>{const changed=document.replace('compiled HTML','unsaved HTML'),watcher=serverWatches.create(root,[{...htmlInputs[0],source:changed,watches:['n * 2','n * 3'].map((text,index)=>({id:'inline'+index,from:changed.indexOf(text),to:changed.indexOf(text)+text.length}))}],path.resolve),compiled=bodyBlock(document,0),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source:document}));assert.equal(transformed.source,compiled.code);assert(watcher.bindings().every(item=>item.status==='stale'));});
check('Missing original HTML snapshots leave script-body watches explicitly unmapped',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve),compiled=bodyBlock(document,0),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML);assert.equal(transformed.source,compiled.code);assert(watcher.bindings().every(item=>item.status==='unmapped'));});
check('Recovered omitted source contents bind without changing the original map',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original),map=new mapping.TraceMap({version:3,sources:['helper.js'],names:compiled.map.names,mappings:mapping.decodedMappings(compiled.map)},origin+'compiled.js'),run=execute(watcher,watcher.transform(compiled.code,map,file,resolve,null,()=>({source:original,mappedSource:original})));assert.equal(run.value,42);assert.equal(run.observed[0].value,42);assert.equal(map.sourcesContent,undefined);});
check('Unavailable recovered contents keep the actual recovery reason visible',()=>{const watcher=serverWatches.create(root,input(original),path.resolve),compiled=compile(original),map=new mapping.TraceMap({version:3,sources:['helper.js'],names:compiled.map.names,mappings:mapping.decodedMappings(compiled.map)},origin+'compiled.js'),transformed=watcher.transform(compiled.code,map,file,resolve,null,()=>({reason:'Recovered source does not match the compiler map'}));assert.equal(transformed.source,compiled.code);assert.equal(watcher.bindings()[0].status,'unmapped');assert.match(watcher.bindings()[0].reason,/does not match/);});
check('Different recovered HTML bodies sharing one URL retain their source ordinals',()=>{const watcher=serverWatches.create(root,htmlInputs,path.resolve),first=bodyBlock(document,0),second=bodyBlock(document,1),decoded=mapping.decodedMappings(first.map).map(line=>line.map(segment=>segment.slice())),offset=first.code.split('\n').length-1;for(const [line,segments] of mapping.decodedMappings(second.map).entries()){decoded[offset+line]||=[];for(const segment of segments){const copy=segment.slice();if(copy.length>1)copy[1]=1;if(copy.length===5)copy[4]+=first.map.names.length;decoded[offset+line].push(copy);}}for(let index=0;index<decoded.length;index++)decoded[index]||=[];const map=new mapping.TraceMap({version:3,sources:['index.html','index.html'],sourcesContent:[null,null],names:[...first.map.names,...second.map.names],mappings:decoded},origin+'compiled.js'),blocks=html.blocks(document),transformed=watcher.transform(first.code+second.code,map,htmlFile,resolveHTML,null,(_address,index)=>({source:document,mappedSource:blocks[index].source})),observed=[],sandbox={[watcher.watch.key]:(id,value)=>{observed.push({id,value});return value;}};vm.runInNewContext(transformed.source,sandbox);assert.equal(sandbox.double(21),42);assert.equal(sandbox.triple(14),42);assert.deepEqual(observed.map(item=>item.id),['inline0','inline1']);assert(watcher.bindings().every(item=>item.status==='bound'));});
check('Decoded SVG script-body compiler maps bind authored entity expressions',()=>{const source='<svg><script type="module"><![CDATA[globalThis.double=n=>n * 2;]]>globalThis.entity=21 &lt; 22;</script></svg>',text='21 &lt; 22',watcher=serverWatches.create(root,[{path:htmlFile,source,watches:[{id:'entity',from:source.indexOf(text),to:source.indexOf(text)+text.length}]}],path.resolve),compiled=bodyBlock(source,0),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source})),observed=[],sandbox={[watcher.watch.key]:(id,value)=>{observed.push({id,value});return value;}};vm.runInNewContext(transformed.source,sandbox);assert.equal(sandbox.entity,true);assert.deepEqual(observed,[{id:'entity',value:true}]);assert.equal(watcher.bindings()[0].status,'bound');});
check('Real esbuild SVG module body maps bind complete import.meta.url expressions',()=>{const source='<svg><script type="module"><![CDATA[globalThis.moduleURL=import.meta.url;]]></script></svg>',text='import.meta.url',watcher=serverWatches.create(root,[{path:htmlFile,source,watches:[{id:'moduleURL',from:source.indexOf(text),to:source.indexOf(text)+text.length}]}],path.resolve),compiled=bodyBlock(source,0,{format:'esm'}),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source})),original=acorn.parse(compiled.code,{ecmaVersion:'latest',sourceType:'module'}).body.find(node=>node.type==='ExpressionStatement').expression.right;assert.equal(watcher.bindings()[0].status,'bound');assert.equal(transformed.instrument.specs.length,1);assert.deepEqual({from:transformed.instrument.specs[0].from,to:transformed.instrument.specs[0].to},{from:original.start,to:original.end});assert.equal(compiled.code.slice(original.start,original.end),text);const observed=acorn.parse(transformed.source,{ecmaVersion:'latest',sourceType:'module'}).body.find(node=>node.type==='ExpressionStatement').expression.right;assert.equal(observed.type,'CallExpression');assert.equal(observed.callee.name,watcher.watch.key);assert.equal(observed.arguments[1].type,'MemberExpression');assert.equal(observed.arguments[1].object.type,'MetaProperty');assert.equal(observed.arguments[1].property.name,'url');});
check('Real esbuild SVG module body maps bind entire top-level await expressions',()=>{const source='<svg><script type="module"><![CDATA[globalThis.awaited=await Promise.resolve(21 * 2);]]></script></svg>',text='await Promise.resolve(21 * 2)',watcher=serverWatches.create(root,[{path:htmlFile,source,watches:[{id:'awaited',from:source.indexOf(text),to:source.indexOf(text)+text.length}]}],path.resolve),compiled=bodyBlock(source,0,{format:'esm'}),transformed=watcher.transform(compiled.code,compiled.map,htmlFile,resolveHTML,null,()=>({source})),original=acorn.parse(compiled.code,{ecmaVersion:'latest',sourceType:'module'}).body.find(node=>node.type==='ExpressionStatement').expression.right;assert.equal(original.type,'AwaitExpression');assert.equal(watcher.bindings()[0].status,'bound');assert.equal(transformed.instrument.specs.length,1);assert.deepEqual({from:transformed.instrument.specs[0].from,to:transformed.instrument.specs[0].to},{from:original.start,to:original.end});assert.equal(compiled.code.slice(original.start,original.end),text);const observed=acorn.parse(transformed.source,{ecmaVersion:'latest',sourceType:'module'}).body.find(node=>node.type==='ExpressionStatement').expression.right;assert.equal(observed.type,'CallExpression');assert.equal(observed.callee.name,watcher.watch.key);assert.equal(observed.arguments[1].type,'AwaitExpression');assert.equal(observed.arguments[1].argument.type,'CallExpression');assert.equal(observed.arguments[1].argument.callee.object.name,'Promise');assert.equal(observed.arguments[1].argument.callee.property.name,'resolve');});
const result={passed:true,checks};fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'../server-watch-compiler-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
