'use strict';
process.env.LT_REVIVAL_TEST='1';
const assert=require('assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path');
const syntax=require('../../deploy/core/revival-syntax.cjs'),watches=require('../../deploy/core/proof-watches.cjs'),html=require('../../deploy/core/revival-html-watches.cjs'),esbuild=require('../../deploy/core/node_modules/esbuild'),policy=require('../../deploy/core/proof-policy.cjs');
const checks=[],key='__lt_watch_'+'a'.repeat(32),spec=(source,text,id='value',last=false)=>{const from=last?source.lastIndexOf(text):source.indexOf(text);assert(from>=0,'Fixture selection exists: '+text);return {id,from,to:from+text.length};};
async function check(name,fn){try{await fn();checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
async function execute(source,selections,filename='report.ts',options={}){const instrument=watches.instrument(source,selections,key,undefined,{filename,...options}),values=[],context={[key]:(id,value)=>{values.push({id,value});return value;}};const generated=await esbuild.transform(instrument.source,{loader:options.loader||syntax.loader(filename),target:'es2022',jsxFactory:'h',jsxFragment:'Fragment'});vm.runInNewContext(generated.code,context,{timeout:100});return {instrument,values,context,generated};}
function reject(source,text,filename='report.ts'){assert.throws(()=>watches.instrument(source,[spec(source,text)],key,undefined,{filename}),/complete value expression|Unexpected|Missing/);}
(async()=>{let result;try{
 await check('The grammar contract infers JSX, TSX, TS, MTS and CTS while preserving ordinary JS',()=>{for(const [filename,expected] of [['report.js','js'],['report.jsx','jsx'],['report.ts','ts'],['report.tsx','tsx'],['report.mts','ts'],['report.cts','ts']])assert.equal(syntax.loader(filename),expected);assert.equal(syntax.parse('let n=42;').body[0].type,'VariableDeclaration');assert.equal(syntax.parse('const n: number=42;',{loader:'ts'}).body[0].type,'VariableDeclaration');assert.throws(()=>syntax.parse('42',{loader:'other'}),/grammar/);});
 await check('Typed parsing returns original ESTree positions and separates declarations from values',()=>{const source='interface Box<T> {value:T}\r\nconst n: number = 21 * 2;',tree=syntax.parse(source,{filename:'report.ts',preserveParens:true});assert.equal(tree.type,'Program');assert.equal(tree.body[0].type,'TSInterfaceDeclaration');const value=tree.body[1].declarations[0].init;assert.equal(source.slice(value.start,value.end),'21 * 2');assert.equal(value.loc.start.line,2);assert(syntax.isTypeOnly(tree.body[0]));});
 await check('Typed dynamic imports retain ESTree dependency nodes and erased imports retain module grammar',()=>{const tree=syntax.parse('const pending=import("./helper.ts");',{filename:'report.ts'});assert.equal(tree.body[0].declarations[0].init.type,'ImportExpression');assert.equal(tree.body[0].declarations[0].init.source.value,'./helper.ts');const erased=syntax.parse('import type {Shape} from "missing";const n:number=42;',{filename:'report.ts'});assert.equal(erased.sourceType,'module');assert.equal(erased.body[0].importKind,'type');assert(syntax.isTypeOnly(erased.body[0]));});
 await check('Original typed and JSX tokens retain CRLF and UTF-16 emoji boundaries without comments',()=>{const source='// ignored\r\nconst text: string = "😀";\r\nconst view=<span>{text}</span>;',tokens=[...syntax.tokens(source,{filename:'report.tsx'})];assert(tokens.every(token=>token.end>token.start));assert(tokens.every(token=>!source.slice(token.start,token.end).startsWith('//')));const emoji=tokens.find(token=>source.slice(token.start,token.end)==='"😀"');assert(emoji);assert.equal(emoji.end-emoji.start,4);assert(tokens.some(token=>source.slice(token.start,token.end)==='span'));});
 await check('Exact original expression selection unwraps transparent typed assertions and instantiation',()=>{const source='let n=42; const a=(n as number);const b=n!;const c=n satisfies number;function f<T>(v:T){return v;}const d=f<number>;',cases=[['(n as number)','Identifier'],['n!','Identifier'],['n satisfies number','Identifier'],['f<number>','Identifier']];for(const [text,type] of cases){const selected=spec(source,text);const node=syntax.expression(source,selected.from,selected.to,{filename:'report.ts'});assert.equal(syntax.runtimeExpression(node).type,type);}const partial=spec(source,'as number');assert.throws(()=>syntax.expression(source,partial.from,partial.to,{filename:'report.ts'}),/complete/);});
 await check('Interfaces and generic functions execute watched original runtime expressions once',async()=>{const source='interface Box<T>{value:T} function twice<T extends number>(value:T):number{return value*2;} globalThis.result=twice<number>(21);',run=await execute(source,[spec(source,'value*2')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.value),[42]);assert.equal(run.instrument.filename,'report.ts');});
 await check('As, angle casts, non-null and satisfies watches preserve their real values',async()=>{const source='let n:number=42; const a=n as number; const b=<number>n; const c=n!; const d=n satisfies number;globalThis.result=[a,b,c,d];',run=await execute(source,['n as number','<number>n','n!','n satisfies number'].map((text,index)=>spec(source,text,'cast'+index)));assert.deepEqual(Array.from(run.context.result),[42,42,42,42]);assert.deepEqual(run.values.map(item=>item.value),[42,42,42,42]);});
 await check('Enum initializers and namespace values retain their actual runtime initialization',async()=>{const source='enum Factor {Base=20+1} namespace Report {export const total=Factor.Base*2;} globalThis.result=Report.total;',run=await execute(source,[spec(source,'20+1','enum'),spec(source,'Factor.Base*2','namespace')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.value),[21,42]);});
 await check('Watched enum side effects and explicit computed increments execute once without changing reverse names',async()=>{const source='let calls=0;function seed(){calls++;return 20;}enum Factor{Base=seed(),Next=Base+1}globalThis.result=[Factor.Base,Factor.Next,Factor[20],Factor[21],calls];',run=await execute(source,[spec(source,'seed()','seed',true)]);assert.deepEqual(Array.from(run.context.result),[20,21,'Base','Next',1]);assert.deepEqual(run.values.map(item=>item.value),[20]);reject('enum Label{"report"="value"}','"report"');});
 await check('Watched constant enum members preserve every original implicit increment and reverse name',async()=>{for(const name of ['Base','Factor','"__proto__"','"report-value"']){const source='enum Factor{'+name+'=20,Next,Last,Reset=40,After}globalThis.result=[Factor.Next,Factor.Last,Factor.After,Factor[20],Factor[21],Factor[22]];',run=await execute(source,[spec(source,'20')]);assert.deepEqual(Array.from(run.context.result),[21,22,41,name.replaceAll('"',''),'Next','Last']);assert.deepEqual(run.values.map(item=>item.value),[20]);}});
 await check('Enum instrumentation remains private to namespace, exported and repeated local declarations',async()=>{for(const source of ['namespace Report{export enum Factor{Base=20,Next}}globalThis.result=Report.Factor.Next*2;','function report(){const enum Factor{Base=20,Next}return Factor.Next*2;}globalThis.result=[report(),report()];']){const run=await execute(source,[spec(source,'20')]);assert.deepEqual(Array.isArray(run.context.result)?Array.from(run.context.result):run.context.result,source.startsWith('namespace')?42:[42,42]);assert.equal(run.values.length,source.startsWith('namespace')?1:2);}const source='export enum Factor{Base=20,Next}';const instrument=watches.instrument(source,[spec(source,'20')],key,undefined,'report.ts'),generated=await esbuild.transform(instrument.source,{loader:'ts',format:'cjs'}),context={module:{exports:{}},[key]:(_id,value)=>value};vm.runInNewContext(generated.code,context,{timeout:100});assert.equal(context.module.exports.Factor.Next,21);assert.deepEqual(Object.keys(context.module.exports),['Factor']);});
 await check('Watched string enum constants preserve direct and cross-enum aliases without extra reverse keys',async()=>{const source='enum A{Ready="ready",Alias=Ready,Joined="r"+"eady"}enum B{Ready=A.Ready}globalThis.result=[Object.keys(A).join(","),Object.keys(B).join(","),A.Ready,A.Alias,A.Joined,B.Ready];',run=await execute(source,[spec(source,'"ready"'),spec(source,'"r"','partial')]);assert.deepEqual(Array.from(run.context.result),['Ready,Alias,Joined','Ready','ready','ready','ready','ready']);assert.deepEqual(run.values.map(item=>item.value),['ready','r']);});
 await check('Original computed string-valued enum emission remains unchanged by watches',async()=>{const source='const label="ready";enum A{Ready=label}globalThis.result=[Object.keys(A).join(","),A.Ready,A.ready];',run=await execute(source,[spec(source,'label','label',true)]);assert.deepEqual(Array.from(run.context.result),['Ready,ready','ready','Ready']);assert.deepEqual(run.values.map(item=>item.value),['ready']);});
 await check('Implicit members after computed or string enum initializers retain original undefined values and keys',async()=>{for(const initializer of ['Number("20")','"ready"']){const source='enum Factor{Base='+initializer+',Next,Last}globalThis.result=[Factor.Base,Factor.Next,Factor.Last,Object.keys(Factor).join(","),Factor.undefined];',original={},built=await esbuild.transform(source,{loader:'ts',target:'es2022'});vm.runInNewContext(built.code,original,{timeout:100});const run=await execute(source,[spec(source,initializer)]);assert.deepEqual(Array.from(run.context.result),Array.from(original.result));assert.equal(run.values.length,1);}});
 await check('Watched constants preserve unwatched cross-enum implicit aliases including negative and nonfinite numbers',async()=>{for(const initializer of ['20','-20','1/0','0/0']){const source='enum A{Base='+initializer+'}enum B{Base=A.Base,Next,Last}globalThis.result=[A.Base,B.Base,B.Next,B.Last,Object.keys(A).join(","),Object.keys(B).join(",")];',original={},built=await esbuild.transform(source,{loader:'ts',target:'es2022'});vm.runInNewContext(built.code,original,{timeout:100});const run=await execute(source,[spec(source,initializer)]);assert.deepEqual(Array.from(run.context.result),Array.from(original.result));assert.equal(run.values.length,1);}});
 await check('Constant initializer captures leave later override and prototype enum read folding unchanged',async()=>{for(const source of ['enum E{A=20}(E as any).A=42;globalThis.result=E.A;','enum A{"__proto__"=20}enum B{Alias=A.__proto__}globalThis.result=B.Alias;']){const original={},built=await esbuild.transform(source,{loader:'ts',target:'es2022'});vm.runInNewContext(built.code,original,{timeout:100});const run=await execute(source,[spec(source,'20')]);assert.equal(run.context.result,original.result);assert.equal(run.context.result,20);assert.deepEqual(run.values.map(item=>item.value),[20]);assert(run.instrument.source.startsWith(source.slice(0,source.indexOf('}')+1)));}});
 await check('Deferred partial and nested enum captures retain bare member values and original source offsets',async()=>{const source='// 😀\r\nenum E{A=20,B=(A+1),C=B+1}globalThis.result=E.C;',run=await execute(source,[spec(source,'(A+1)','outer'),spec(source,'A+1','inner'),spec(source,'A+1','value'),spec(source,'A','member',true),spec(source,'B+1','next')]);assert.equal(run.context.result,22);assert.deepEqual(run.values.map(item=>item.id),['member','value','inner','outer','next']);assert.deepEqual(run.values.map(item=>item.value),[20,21,21,21,22]);const copied=run.instrument.edits.filter(edit=>edit.copy);assert(copied.length);for(const edit of copied){assert.equal(run.instrument.source.slice(edit.start,edit.end),source.slice(edit.at,edit.at+edit.end-edit.start));assert.equal(watches.offset(run.instrument,edit.start),edit.at);assert.equal(watches.offset(run.instrument,edit.end-1),edit.at+edit.end-edit.start-1);}});
 await check('Deferred custom enum expressions keep local bindings and shorthand values in their original lexical scope',async()=>{const source='enum E{A=20,B=A+1}globalThis.result=E.B;',selection=spec(source,'A+1','custom');selection.expression='(()=>{const A=1;return {A,B};})()';const run=await execute(source,[selection]);assert.equal(run.context.result,21);assert.deepEqual(JSON.parse(JSON.stringify(run.values[0].value)),{A:1,B:21});});
 await check('Shadowed Infinity and NaN enum initializers stay at their real evaluation site',async()=>{for(const name of ['Infinity','NaN']){const source='function report(){let '+name+'=20;enum E{A='+name+',B=('+name+'=42)}return E.A;}globalThis.result=report();',selection=spec(source,name,'global',false);selection.from=source.indexOf('A='+name)+2;selection.to=selection.from+name.length;const run=await execute(source,[selection]);assert.equal(run.context.result,20);assert.deepEqual(run.values.map(item=>item.value),[20]);}});
 await check('Deferred enum captures cannot become an isolated file result expression',async()=>{const modules=require('../../deploy/core/proof-modules.cjs'),source='enum E{A=20}',original=await modules.prepare(source,{loader:'ts'}),watched=await modules.prepare(source,{loader:'ts',watches:[spec(source,'20')]});assert.equal(original.resultExport,'namespace');assert.equal(watched.resultExport,'namespace');assert.equal(syntax.parse(watched.watch.source,{loader:'ts'}).body.at(-1).type,'BlockStatement');const selected='enum E{A=20}42;',prepared=await modules.prepare(selected,{loader:'ts',watches:[spec(selected,'20')]});assert.equal(prepared.resultExport,'default');});
 await check('Constant custom enum observations explicitly run after later dynamic members without changing program values',async()=>{const source='let calls=0;enum E{A=20,B=++calls}globalThis.result=[E.A,E.B,calls];',constant=spec(source,'20','constant');constant.expression='calls';const original={},built=await esbuild.transform(source,{loader:'ts',target:'es2022'});vm.runInNewContext(built.code,original,{timeout:100});const run=await execute(source,[constant,spec(source,'++calls','dynamic')]);assert.deepEqual(Array.from(run.context.result),Array.from(original.result));assert.deepEqual(run.values.map(item=>item.id),['dynamic','constant']);assert.deepEqual(run.values.map(item=>item.value),[1,1]);});
 await check('Imported and loop-local Infinity bindings do not masquerade as global compiler constants',async()=>{const imported='import {Infinity} from "./live.js";enum E{A=Infinity,B=Number(42)}',selected=spec(imported,'Infinity','imported',true),instrument=watches.instrument(imported,[selected],key,undefined,'report.ts');assert(instrument.source.includes('A='+key+'('));const source='for(const Infinity of [1]){}enum E{A=Infinity,B}globalThis.result=E.B;',run=await execute(source,[spec(source,'Infinity','global',true)]);assert.equal(run.context.result,Infinity);assert.deepEqual(run.values.map(item=>item.value),[Infinity]);assert(run.instrument.source.includes('enum E{A=Infinity,B}{'));});
 await check('Type aliases, interface members, annotations, erased imports and ambient declarations reject watches',()=>{for(const [source,text] of [['type Shape={value:42};','42'],['interface Box<T>{value:T}','T>'],['const n:number=42;','number'],['import type {Shape} from "missing";','"missing"'],['declare const n:42;','42'],['declare namespace Report {const n:42;}','42'],['type Shape=typeof Math.PI;','Math.PI']])reject(source,text);});
 await check('Typed variable, function, enum, namespace and class names remain bindings',()=>{for(const [source,text] of [['const n:number=42;','n'],['function twice(n:number){return n*2}','n:number'],['enum Factor {Base=21}','Factor'],['enum Factor {Base=21}','Base'],['namespace Report {export const n=42}','Report'],['class Report {value=42}','Report']])reject(source,text);});
 await check('Typed parameter default expressions execute in their original local scope',async()=>{const source='function twice(value:number=20+1):number{return value*2;}globalThis.result=twice();',run=await execute(source,[spec(source,'20+1','default'),spec(source,'value*2','body')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.value),[21,42]);});
 await check('Parameter properties retain constructor assignment and default evaluation',async()=>{const source='class Report {constructor(public value:number=20+1){}}globalThis.result=new Report().value*2;',run=await execute(source,[spec(source,'20+1')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.value),[21]);reject(source,'value:number');});
 await check('Assertions and parentheses cannot hide a method reference whose receiver would change',async()=>{const source='const obj={value:42,run(){return this.value}};globalThis.result=(obj.run as ()=>number)();';for(const text of ['obj.run','obj.run as ()=>number','(obj.run as ()=>number)'])reject(source,text);const generated=await esbuild.transform(source,{loader:'ts'}),context={};vm.runInNewContext(generated.code,context,{timeout:100});assert.equal(context.result,42);});
 await check('Typed assignments, update operands and loop targets reject instrumentation through wrappers',()=>{for(const [source,text] of [['let obj:{value:number}|null={value:1};obj!.value=42;','obj!'],['let n:number=0;for(n of [42]){}','n of'],['let obj={value:1};(obj.value as number)=42;','obj.value as number']])reject(source,text);const source='let n:number=1;n++;';assert.throws(()=>watches.instrument(source,[spec(source,'n','target',true)],key,undefined,'report.ts'),/complete value/);});
 await check('Whole JSX fragments, attributes and later callbacks preserve native value order',async()=>{const source='const h=(tag,props,...children)=>({tag,props:props||{},children});const Fragment="fragment";let clicks=0;const view=<><button data-v={21*2} onclick={()=>++clicks}>report</button></>;globalThis.result=view.children[0].props["data-v"];globalThis.clicked=view.children[0].props.onclick();',element='<><button data-v={21*2} onclick={()=>++clicks}>report</button></>',run=await execute(source,[spec(source,element,'fragment'),spec(source,'21*2','attribute'),spec(source,'++clicks','callback')],'report.jsx');assert.equal(run.context.result,42);assert.equal(run.context.clicked,1);assert.deepEqual(run.values.map(item=>item.id),['attribute','fragment','callback']);assert.equal(run.values[1].value.tag,'fragment');});
 await check('JSX names and unbraced attribute strings cannot become invalid rewritten syntax',()=>{const source='const view=<button label="report" value={42}/>;';for(const text of ['button','label','"report"'])reject(source,text,'report.jsx');});
 await check('JSX empty comment containers stay erased and cannot become runtime watch calls',()=>{const source='const view=<span>{/* no runtime value */}</span>;',node=syntax.parse(source,{filename:'report.jsx'}).body[0].declarations[0].init.children[0].expression;assert.equal(node.type,'JSXEmptyExpression');assert(!syntax.isExpression(node));assert.throws(()=>watches.instrument(source,[{id:'empty',from:node.start,to:node.end}],key,undefined,'report.jsx'),/complete value/);});
 await check('Typed class names stay syntax while computed property and initializer values execute',async()=>{const source='const key="value";class Report {value:number=21;[key+"Other"]:number=21;}globalThis.result=new Report().value+new Report().valueOther;';reject(source,'value');const run=await execute(source,[spec(source,'key+"Other"','key'),spec(source,'21','initializer')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.id),['key','initializer','initializer']);});
 await check('CommonJS TypeScript export assignments can watch their runtime expression',async()=>{const source='const n:number=21;export=n*2;',instrument=watches.instrument(source,[spec(source,'n*2')],key,undefined,'report.cts'),generated=await esbuild.transform(instrument.source,{loader:'ts',format:'cjs'}),values=[],context={module:{exports:null},[key]:(_id,value)=>{values.push(value);return value;}};vm.runInNewContext(generated.code,context,{timeout:100});assert.equal(context.module.exports,42);assert.deepEqual(values,[42]);});
 await check('Typed JSX component callbacks execute expressions beside their original props',async()=>{const source='interface Props{value:number} const h=(tag:any,props:any,...children:any[])=>typeof tag==="function"?tag(props):({tag,props,children});const Fragment="fragment";function Report(props:Props){return <span>{props.value*2}</span>;}globalThis.result=(<Report value={21}/>).children[0];',run=await execute(source,[spec(source,'props.value*2')],'report.tsx');assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.value),[42]);});
 await check('Nested typed watches retain original ranges, evaluation order and one result',async()=>{const source='globalThis.result=((21+0) as number)*2;',run=await execute(source,[spec(source,'(21+0) as number','outer'),spec(source,'21+0','inner')]);assert.equal(run.context.result,42);assert.deepEqual(run.values.map(item=>item.id),['inner','outer']);for(const item of run.instrument.specs){const insertion=run.instrument.edits.find(edit=>edit.at===item.from);assert(insertion);assert.equal(watches.offset(run.instrument,insertion.start),item.from);}assert.equal(watches.offset(run.instrument,run.instrument.source.indexOf('21+0')),source.indexOf('21+0'));});
 await check('Typed custom expressions report a derived value without replacing the original result',async()=>{const source='const n:number=21;globalThis.result=n;',selection=spec(source,'n','custom',true);selection.expression='(__SELECTION__ as number)*2';const run=await execute(source,[selection]);assert.equal(run.context.result,21);assert.deepEqual(run.values.map(item=>item.value),[42]);});
 await check('Configuration retains typed grammar and follows strict directives',async()=>{const source='"use strict";interface Shape{value:number}globalThis.result=21*2;',instrument=watches.configure(watches.instrument(source,[spec(source,'21*2')],key,undefined,'report.ts'),'globalThis.configured=true');assert(instrument.source.indexOf('globalThis.configured')>instrument.source.indexOf('"use strict";'));assert.equal(instrument.filename,'report.ts');const generated=await esbuild.transform(instrument.source,{loader:'ts'}),context={[key]:(_id,value)=>value};vm.runInNewContext(generated.code,context,{timeout:100});assert.equal(context.result,42);assert.equal(context.configured,true);});
 await check('CRLF and emoji offsets map inserted code and rejected types to the original buffer',async()=>{const source='// 😀 original\r\nconst n:number=21;\r\nglobalThis.result=n*2;\r\n',selected=spec(source,'n*2'),run=await execute(source,[selected]);assert.equal(run.context.result,42);const at=run.instrument.source.indexOf('n*2');assert.equal(watches.offset(run.instrument,at),selected.from);const type=spec(source,'number');assert.throws(()=>watches.instrument(source,[type],key,undefined,'report.ts'),error=>error.pos===type.from&&error.loc.line===2&&error.loc.column===8);});
 await check('Plan and HTML dispatch carry the original typed filename without changing hashes or disk',()=>{const source='const n:number=21;globalThis.result=n*2;',filename=path.join(policy.root,'typed-plan','report.ts'),plan=watches.plan(source,[spec(source,'n*2')],[],filename,path.resolve,undefined,html.instrumentSource);assert.equal(plan.files[0].filename,filename);assert.equal(plan.files[0].originalSource,source);assert.equal(plan.specs[0].path,filename);assert.equal(plan.specs[0].sourceSha256,require('crypto').createHash('sha256').update(source).digest('hex'));});
 await check('Legacy JavaScript and HTML handlers retain scope, strictness and receiver guards',()=>{const source='function twice(n){return n*2;}globalThis.result=twice(21);',instrument=watches.instrument(source,[spec(source,'n*2')],key),context={[key]:(_id,value)=>value};vm.runInNewContext(instrument.source,context,{timeout:100});assert.equal(context.result,42);const handler='return n*2;',watched=watches.instrument(handler,[spec(handler,'n*2')],key,undefined,{handler:true});assert.equal(vm.runInNewContext('(function(n){'+watched.source+'})(21)',context,{timeout:100}),42);reject('const obj={run(){return this}};(obj.run)();','obj.run','report.js');});
 result={passed:true,checks};
 }catch(error){result={passed:false,checks,error:error.stack};process.exitCode=1;}finally{esbuild.stop();}
 fs.mkdirSync(policy.root,{recursive:true});fs.writeFileSync(path.join(policy.root,'typed-syntax-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})();
