'use strict';
process.env.LT_REVIVAL_TEST='1';
const assert=require('assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const watch=require('../../deploy/core/proof-watches.cjs'),modules=require('../../deploy/core/proof-modules.cjs'),projects=require('../../deploy/core/revival-projects.cjs'),policy=require('../../deploy/core/proof-policy.cjs');
const checks=[];async function check(name,fn){try{await fn();checks.push(name);}catch(error){error.message=name+': '+error.message;throw error;}}
const spec=(source,text,id='value',expression)=>({id,from:source.indexOf(text),to:source.indexOf(text)+text.length,...(expression?{expression}:{})});
function execute(source,input){const prepared=watch.instrument(source,input),values=[];const result=vm.runInNewContext(prepared.source,{[prepared.key]:(id,value)=>{values.push({id,value});return value;}},{timeout:100});return {result,values,prepared};} // Authored fixtures only; real execution is verified in Electron.
const root=path.join(policy.root,'watch-tests',crypto.randomUUID()),saved=fs.existsSync(projects.statePath)?fs.readFileSync(projects.statePath):null;
(async()=>{try{
 await check('A watched expression preserves its program result',()=>{const source='let x=20;x+22;',output=execute(source,[spec(source,'x+22')]);assert.equal(output.result,42);assert.equal(output.values[0].value,42);});
 await check('A watch evaluates side effects once',()=>{const source='let x=40;const a=++x;a+x;',output=execute(source,[spec(source,'++x')]);assert.equal(output.result,82);assert.equal(output.values[0].value,41);});
 await check('Function-local watches run at their actual scope',()=>{const source='function twice(n){return n*2;}twice(21);',output=execute(source,[spec(source,'n*2')]);assert.equal(output.result,42);assert.equal(output.values[0].value,42);});
 await check('Local globalThis bindings do not shadow instrumentation',()=>{const source='const globalThis={};let n=42;n;',output=execute(source,[{id:'value',from:source.lastIndexOf('n;'),to:source.lastIndexOf('n;')+1}]);assert.equal(output.result,42);assert.equal(output.values[0].value,42);});
 await check('Nested watches retain expression evaluation order',()=>{const source='let n=20;n+22;',output=execute(source,[spec(source,'n+22','outer'),{id:'inner',from:9,to:10}]);assert.equal(output.result,42);assert.deepEqual(output.values.map(item=>item.id),['inner','outer']);});
 await check('Parenthesized and semicolon selections work',()=>{const source='(20+22);',output=execute(source,[{id:'value',from:0,to:source.length}]);assert.equal(output.result,42);});
 await check('Custom watch placeholders preserve the original value',()=>{const source='let x=21;x;',output=execute(source,[{id:'custom',from:9,to:10,expression:'__SELECTION__ * 2'}]);assert.equal(output.result,21);assert.equal(output.values[0].value,42);});
 await check('Binding and reference selections cannot change program semantics',()=>{for(const [source,text] of [['let value=42;','value'],['let obj={x:1};obj.x=42;','obj.x'],['const obj={run(){return this}};obj.run();','obj.run'],['const x=42;({x});','x}'],['let x=42;delete globalThis.x;','globalThis.x']])assert.throws(()=>watch.instrument(source,[spec(source,text)]));});
 await check('Invalid ids, ranges and excessive watches fail closed',()=>{for(const input of [[{id:'__proto__',from:0,to:50}],[{id:'x',from:-1,to:1}],Array.from({length:65},(_,i)=>({id:'x'+i,from:0,to:2}))])assert.throws(()=>watch.instrument('42',input));});
 await check('Instrumentation positions map back to the original source',()=>{const source='let x=20;\nx+22;\nthrow new Error("after");',p=watch.instrument(source,[spec(source,'x+22')]),index=p.source.indexOf('new Error'),before=p.source.slice(0,index),point=watch.position(p,before.split('\n').length,index-(before.lastIndexOf('\n')+1),source);assert.deepEqual(point,{line:3,column:6});});
 await check('Unknown and oversized watch replies are rejected',()=>{const p=watch.instrument('42',[{id:'x',from:0,to:2}]);assert.throws(()=>watch.validate([{id:'bad',result:'42'}],p));assert.throws(()=>watch.validate([{id:'x',result:'x'.repeat(1025)}],p));assert.deepEqual(watch.validate([{id:'x',result:'42'}],p),[{id:'x',result:'42'}]);});
 fs.mkdirSync(root,{recursive:true});projects.activate(root);const entry=path.join(root,'index.js');fs.writeFileSync(entry,'');fs.writeFileSync(path.join(root,'answer.cjs'),'module.exports=42;');
 await check('Linked watches retain the exact original source snapshot',async()=>{const source='const n=require("./answer.cjs");n;',p=await modules.prepare(source,{path:entry,watches:[{id:'value',from:source.lastIndexOf('n;'),to:source.lastIndexOf('n;')+1}]});assert.equal(p.project.modules.find(item=>item.path===entry).source,source);const values=[];globalThis[p.watch.key]=(id,value)=>{values.push(value);return value;};try{const result=await import('data:text/javascript;base64,'+Buffer.from(p.code).toString('base64'));assert.equal(result.default,42);assert.deepEqual(values,[42]);}finally{delete globalThis[p.watch.key];}});
 await check('Runtime errors after instrumentation keep original columns',async()=>{const source='require("./answer.cjs");\n(()=>{throw new Error("watch error")})();',p=await modules.prepare(source,{path:entry,watches:[spec(source,'new Error("watch error")')]});globalThis[p.watch.key]=(_id,value)=>value;try{await import('data:text/javascript;base64,'+Buffer.from(p.code).toString('base64'));assert.fail('Expected error');}catch(error){const mapped=modules.runtimeError(p,{error:error.message,stack:error.stack});assert.equal(mapped.location.line,2);assert.equal(mapped.location.column,13);assert.equal(mapped.location.source,source);}finally{delete globalThis[p.watch.key];}});
 const helper=path.join(root,'helper.cjs'),helperSource='module.exports=n=>n*2;';fs.writeFileSync(helper,helperSource);
 await check('Imported function watches observe caller values and original sources',async()=>{const p=await modules.prepare('require("./helper.cjs")(21);',{path:entry,watchFiles:[{path:helper,source:helperSource,watches:[spec(helperSource,'n*2','dependency')]}]}),values=[];globalThis[p.watch.key]=(id,value)=>{values.push({id,value});return value;};try{assert.equal((await import('data:text/javascript;base64,'+Buffer.from(p.code).toString('base64'))).default,42);assert.deepEqual(values,[{id:'dependency',value:42}]);assert.equal(p.project.modules.find(item=>item.path===helper).source,helperSource);assert.equal(p.watch.specs[0].path,helper);}finally{delete globalThis[p.watch.key];}});
 await check('A watched unsaved dependency overrides disk without saving it',async()=>{const source='module.exports=n=>n*3;',p=await modules.prepare('require("./helper.cjs")(14);',{path:entry,watchFiles:[{path:helper,source,watches:[spec(source,'n*3','unsaved')]}]});globalThis[p.watch.key]=(_id,value)=>value;try{assert.equal((await import('data:text/javascript;base64,'+Buffer.from(p.code).toString('base64'))).default,42);assert.equal(p.project.modules.find(item=>item.path===helper).source,source);assert.equal(fs.readFileSync(helper,'utf8'),helperSource);}finally{delete globalThis[p.watch.key];}});
 await check('Imported instrumentation errors map to the original dependency column',async()=>{const source='module.exports=n=>{const value=n*2;throw new Error("dependency watch");};',p=await modules.prepare('require("./helper.cjs")(21);',{path:entry,watchFiles:[{path:helper,source,watches:[spec(source,'n*2','mapped')]}]});globalThis[p.watch.key]=(_id,value)=>value;try{await import('data:text/javascript;base64,'+Buffer.from(p.code).toString('base64'));assert.fail('Expected dependency error');}catch(error){const failure=modules.runtimeError(p,{error:error.message,stack:error.stack});assert.equal(failure.location.path,helper);assert.equal(failure.location.column,source.indexOf('new Error')+1);assert.equal(failure.location.source,source);}finally{delete globalThis[p.watch.key];}});
 await check('Watch graphs reject duplicate ids, duplicate paths and outside files',async()=>{const outside=root+'-outside';fs.mkdirSync(outside);projects.activate(outside);projects.activate(root);for(const watchFiles of [[{path:helper,source:helperSource,watches:[spec(helperSource,'n*2','value')]}],[{path:helper,source:helperSource,watches:[spec(helperSource,'n*2','first')]},{path:helper,source:helperSource,watches:[spec(helperSource,'n*2','second')]}],[{path:path.join(outside,'outside.cjs'),source:'42;',watches:[{id:'outside',from:0,to:2}]}]])await assert.rejects(modules.prepare('42;',{path:entry,watches:[{id:'value',from:0,to:2}],watchFiles}),/Duplicate|leaves the open project/);});
 await check('The watch count budget applies to the whole project graph',()=>{assert.throws(()=>watch.plan('42;',Array.from({length:64},(_,index)=>({id:'entry'+index,from:0,to:2})),[{path:helper,source:helperSource,watches:[spec(helperSource,'n*2','extra')]}],entry),/across the execution graph/);});
 await check('Multiple context values retain thread and process identity',()=>{const p=watch.plan('42;',[{id:'context',from:0,to:2}],[],entry),merged=watch.mergeContexts(p,[{pid:200,threadId:2,values:[{id:'context',result:'44'}]},{pid:200,threadId:1,values:[{id:'context',result:'42'}]}]);assert.match(merged[0].result,/thread 1.*42[\s\S]*thread 2.*44/);assert.deepEqual(merged[0].contexts.map(item=>item.threadId),[1,2]);assert.throws(()=>watch.mergeContexts(p,[{pid:200,threadId:1,values:[{id:'forged',result:'42'}]}]));});
 console.log(JSON.stringify({passed:true,checks:checks.length}));
}finally{modules.stop();if(saved)fs.writeFileSync(projects.statePath,saved);else if(fs.existsSync(projects.statePath))fs.unlinkSync(projects.statePath);}})().catch(error=>{console.error(error);process.exitCode=1;});
